---
apiVersion: v1
kind: Pod
metadata:
  name: kata-fuse-probe
  labels:
    app.kubernetes.io/name: kata-fuse-probe
spec:
  runtimeClassName: kata
  restartPolicy: Never
  nodeSelector:
    kata.spruyt-labs/ready: "true"
  containers:
    - name: probe
      image: docker.io/library/fedora:41
      command: ["sleep", "600"]
      securityContext:
        privileged: true
