---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: claude-mcp-config
data:
  mcp.json: |
    {
      "mcpServers": {,
        "context7": {
          "baseUrl": "https://mcp.context7.com/mcp",
          "headers": {
            "CONTEXT7_API_KEY": "$${CONTEXT7_API_KEY}"
          }
        },
        "homeassistant": {
          "url": "http://192.168.1.97:8123/api/mcp",
          "headers": {
            "Authorization": "Bearer $${HA_API_KEY}"
          }
        },
        "kubectl": {
          "type": "http",
          "url": "http://kubectl-mcp-server.kubectl-mcp.svc:8000/mcp"
        },
        "victoriametrics": {
          "type": "http",
          "url": "http://mcp-victoriametrics.observability.svc:8080/mcp"
        },
        "github": {
          "type": "http",
          "url": "http://github-mcp-server.github-mcp.svc:8082/mcp",
          "headers": {
            "Authorization": "Bearer $${GITHUB_MCP_TOKEN}"
          }
        },
        "discord": {
          "type": "http",
          "url": "http://discord-mcp.discord-mcp.svc:8080/mcp"
        }
      }
    }
