# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
type: Opaque
stringData:
    virtual-key: ENC[AES256_GCM,data:duwS0ti7Ufqm6gezzVX1WSvpVGgmo+bwOA==,iv:50hZ5zV6HMBQLWAZgB/GJwvTtjOc0d1JaMct3XGFAWw=,tag:1mvrbHO49jMVTeVmlqsy2g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNlNrZEVtRkVZZVdBOXND
            UWhJN1VXdVgzNEkwaVEwR1BmVmQ3N1lpV1g4ClBVSzdwZitHUDlOaU5zZWpSQVp1
            cTBOcWl3Z0R5TzdlMklHVzVPbU5FLzQKLS0tIFhmdFpIcFZDSnFEUEdFUVBkMlVk
            c0RlRVgyaWtDT2pNdWRNT3Y1N1NsaEkKdyuJ9C7SYMrn4ldDJ1w2sh5oJFFx949O
            Zn5ahjAzuy9EAbVds8k8AHevIQvI4ya6AlzOtIVtBwTLO53uA94snQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:40:50Z"
    mac: ENC[AES256_GCM,data:JT+24E5xC0Olr/bs8lHCSHQrv0cFWWoUTjiblLA0sxStWhab6dlufZgCrGB/IuSr+jbIVdKLT/9nzthVF1hQSw+CnG+Hk7CRurL9XQ9TRhkBEiK7SYxA7H9b49YCBja8tCC0IqbdUlssJYvl1bBflHYQxOvgXLNjBdKyYMfblCU=,iv:nXJlsO3+R1a89CAWCy1rp4Qq2nH5NupVRDcHAqAIHwc=,tag:wWCKEbPDz21AWPyAasYVCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
