# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik-coder-oauth
    namespace: authentik-system
stringData:
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:FE+Qryq6LS0Y87+G9asKAVgHpCLSvbcFmGXFk+tiHGc=,iv:fpKzuRFLE6O80En8RvEPMdB0dfzPN+r9cRsJaG14rqY=,tag:irWOvL/r5UTbn5XX+WBwEA==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:B18J/EbQKCmMxfdfikAGg/LOVHW5x4mJCM/SUazoMPGY0tfK0aCzUvsST8PxctEJgZIMLDRtLWmAvs4SGFNH6QlxMtXODEbaEDl3mfmYdzsMs5uEVOXaMpqWZLbFodVVK3xt41d6HzlGILNRbaL8Kjh09NoDgLd73WsJHmhBL+M=,iv:D7q+GwhNfbJnpvCLN8X2UrWPbgXSdzuKfiONDKCUegY=,tag:Ul0wVJm7+3o62ctDgh6dBQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNWNkS1pycDNBeHAwbVlx
            Q0dMN0NBV1J6SWJKRHdaaXNQR3FQNFdJbmpjCmRPRnp0RWM2a1NhYk90TnpPNERC
            Wk1kaG0xbVU3ZnFsSDJ0RE5UT05HN1EKLS0tIFA5Z3dBTTk4WUNKaU5sS2FhRE1m
            T2I0b0RURDFNajJIMlg4U3BOVGY2VFEKWQyJsNS8nBiwS/Hm1vw13mAOyPKsGVWB
            8jMyPbf5bbBh5oyd3o50e4ptOxRp2I/NG68+Qq4qlPhglIb3KCmNPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T06:55:50Z"
    mac: ENC[AES256_GCM,data:t22KfuXiWCZDzt5JjRfSjIXcUPOwXp+E8n2h7dxV1SC7Lrstk/9PXIaIMk2wuXv6plnw4x3LH6nV2Jw4DanoELXkWlR6OHUqMJwLZoxgTUYT5NTjY+iFeba5i6e5zKp+o69TmBDSsk/uwbIJ/vhJED7nsG0zRalxZJ3Jrk1LXUo=,iv:N17rpRm6puW1hX+TPhDjfY9albHdqZLKfbWzF9blomU=,tag:E7zrp6BF52Lx+0L5a9dMRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
