# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik-blueprints
    namespace: authentik-system
type: Opaque
stringData:
    grafana-sso.yaml: ENC[AES256_GCM,data:5VWdDMsqgD9Npnx/K/7Fgg5OIyr9xFv19JLqqUrWZC/uWE048XocbI4j90u1JtLT3rLxWxn80Aa0dKo5s4rjQADvIYPqhU21RKBS/1xEBVdbPYCFwqrPVFlMGrbZcok0oJLnohFLfXraHDLvg7FwzR4WjpqZ/0b1m9n78aq+fNKmm9Pg+zuWWmRHW8vlddjOltLawsPk72qTjSt7hIIYUReQ8PRFcOeXCu4X0sCIkxkZyTRXQYPno46PHW+dbRpXOQp4h8sjNJdUr7klbrFNqp7vaymyjWa9fQcOfGCSiotdnRaM8R8W9OGDKmjrVIC6RK0mfXQUkglHWrLzUPBFYaMIGCnnJkd++K9iY7iY15PtCZPkYgoLpqo+h1N/xD5NO6Qp21zobqnDjmIrzxL9S/pCJIjDh+vERyxEN4OeYtxBWZ/e5ZZi/ttyWP/nwgfD3ulbdkz90o0EszaQ8BehvMGD8wCj2EXdJEQXM87sB6UcgKP+lIMFIDB9Ubg6niMqG3h2DHeHbNFaFJBIX/jY4xfegCGM3kgkKFOsZqABCfGnJqh3jhy6kQwgFSGDVW9U+HANtcrkBQmtFJ0k3qEyN8inX2N+DNbepqMzPJKyxIK1vcNCq5JeoxQiyOmk2+8lMGJIXeC2sjR6c4l8/2RsdHPxSq/EQ5+/KwYoNsWLtKy+sH9xyW4mHGkAFZojNUlTlwsLcJ/xDENIQYWVnQorsDlPdKXuFu7KjCK+TUa8iPYel+99KbwsDEuScjoiLNsUgIYtVfGorypOejmUlsTmelC8Jt02GPtnP8Z7upcVltLPWtKu1NuIMGpmrSeBJSSSYePdk27ZcFm+SlCYBTNTGkKQbv+Iq3RK3JlLr3dEhd94IkDuG5al9Z+lSDu+1Ue6x5boK+MI2105ysvMTwSZi2qRpN7RR2gVi2hCiFZQ9qXXzZEuP5pEctrrGcJQgexx0t6CpfSgrd8Amgiuca9BOdA98Am5+wR5FR8uM7SBKiAPcndViu43Xdc5UDLiC18ferwSKVZLB+6T+DydNBVRAhx7lOjpQBODsX9EKzcIEljZMZMvEJ0QQO3GDlzYUcSA5t6jvhkjnXkqpq7vPD7EspAYUfcluvyyWrG66/7vxU056tuASCMnkA8/LYdPzokmJWsp6dPyEzSuLUK7iQwYcv6O+Bhbk2Ge4OTiNbD65qVzIPYAaf/W4a4k1HjhqeFPg6e/QJF/MMdajwyYAWiAHxfflt8kPKYuQ0Rh9t7nXIipTtKHBwEbzSM3Bb72giJUIvGSaJWYuEAvo8mcUjZoziXM9UBkNAcuTU0UdxLE5grBy3W8bOFEEdRno8yBMUQHSaZFG9herL5sjH85QvSg6HUepYelxSnxRvR9Pjb239iLbVetWUY2zjwV0Lx/QeEXkv6YxuXDY2X+WvtTf7z/eNS4icAB85pJMrqVOPU7Puxv2vk1IpeOXes3Ia4=,iv:l5iFD9r2dJvdZol0UC4CJhILyjStzqEADAhh1DnAKCk=,tag:8SX4qYPTy+SCJ8Mww9VpyQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNTBqTVlVc3BHaDUyQ3JT
            SU1DZHJJNFd0clVpeVkwb0ljWXRLWk0rcFRBCjkwRk9XU3J2RHl4RFpCVW0rL0xj
            UzdOODdOdVllUjlpcU1GMEt4dkpiVTQKLS0tIDlpMHhoZThKN1JoVUl1bVUweVZp
            V09UYXVIUzVKWjA2TndYNmtIbEpLR00K0RDcMvaO96pJJT1kgg29c2LW9zRYsnZs
            lW9ukkyVLHv/1hFURJMxGGiOQvXe8ExFbmJEMuRRrcdCaE15wbMmvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T03:42:49Z"
    mac: ENC[AES256_GCM,data:sUm8e6GkpB1vslQNXNvvV3tgoKb7fuPVfUz1c6467j/TDv0QRIFdWy98rPqnlnqDmrE3hL8magI0XJC+CfMeNOR3gHbQylbT6CZAXcnYr5cLLDe/V3aJS2L0r8Lj1Skpv83FrUnvl1jsMrNI+uqEjL8DKdntJLNEGiEvEfaj05c=,iv:YuibT+fsUlflXhTJg0IiRQEXdMQi3kzXJOj5FT+c2pg=,tag:MIjRqzsJR+hYBp7kRL+qRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
