# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik-system
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:FiAOg8vCRWh+apmJ2zwMH0VXZIqecX9hep2zhvKnnTXQzpLIaQxtkfLmpXuISFgtoM+RwR7WrhDxaQZV/zdw7A==,iv:2liRgU2opi1GOhM9cCIWu0E8qBJEVb/A71rIPqgfXVA=,tag:DpdhPEwXr1iKKK5nKThP5g==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:IIWytCM4pMdJ1YOeF6PPMeawYt/NY4aG2KyHafibdedhKMq1IVMmk77rQS/lSlaBRUOpZW/T+h8iRO+qTQElgQ==,iv:/C9W+FOHB4pimkrxW6P3r/a7lkx+IxL9tb4fTXPsB/Y=,tag:NpnEhPAfRiAGFXtHC2VNQg==,type:str]
    AUTHENTIK_API_TOKEN: ENC[AES256_GCM,data:3dUwZmRI+6Pjeuh3LBs1Q0DEePAuI8QTBcfEKF3CUTbmMHxn1TlB7qfIknqCJeWrBslv45dUC1AgAydc,iv:SbCNENniMeF3D0jpTFu4izR0/IX6BZL8fOskhQdLLMU=,tag:kSzwtpQ9pMJsppFT8vQF2w==,type:str]
    #ENC[AES256_GCM,data:Rsz/4JvlxDwkLmlTeZVFlSjLJoMd+CaoA7oUD5iduqtNbSe3CA==,iv:e1K3sC2RsIy+5/aIa5hZ4/CDOHaaNbgg3IhjRQozc1I=,tag:00yZYJDp4E3D9d7CSH33KQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RpHySvm43gqDJ+Luih0TE79BJTg=,iv:R0jA2hNopLTgOro7LewNAp+s4tt3gfdookVZANL5wiI=,tag:CzYdXKmLxuOMcwRRrnmoDg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ra9Oa0m/SjUDvJGa2bVmpv0rhidWziIBtPt0iuodAOrli9Xe7lAXuQ==,iv:KWxRXN2BRt68EdhRoG9wJYMEO0nBquk496X5Ey65Deg=,tag:0ZPWyKZXwHaGejvMGj/sGg==,type:str]
    #ENC[AES256_GCM,data:noKWqfiOcq5x28gjBJc8I25yl3He4sdTAeOU86VN,iv:l+3CM/pt8WH3HctUd5wvxApjyjNyecNqdl/+cZtc5mg=,tag:zCKFxo6yK3z4WRdCmaucsg==,type:comment]
    #ENC[AES256_GCM,data:SFb8nUrJ4pC82cisE4aFuNLd+JTW+hhpGbZUgg==,iv:fRWTNRsSeQ3F5aX6DIktm3pOAo5yDZbDP0roDnL1AFs=,tag:wSLRIuMwIYctuL3YFgOPKg==,type:comment]
    #ENC[AES256_GCM,data:O/5D/I5BzbSajfdUrtwgwbtH2fn0qHdi,iv:BkY+dBPXjaEuzvk6LQ0d/1YzyEP7mNLjKOg6Xcs/E3A=,tag:xl+Cah71H5x52P/Hd5xSUQ==,type:comment]
    #ENC[AES256_GCM,data:CHiEUADioGIiRVFstY29Qd8F0/wZ4vP8HuGFYkCu,iv:ECSVTgdSBDWQVROOI6gYncObf0GVQczGTPMo8ALuq9A=,tag:xsu+8ClH2Vdp1lwvZ6TTxQ==,type:comment]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTFlSdUZ2OXlobWRGMzEy
            bmxPUGVGVGpJeTVoMGpUcTdHWStrUGtxMjBrCnQ0SStCRW5GdmRYcW1LK3pmUUZU
            TVZtT1hFZHhTQUZlN0JsM3k0c1JPbEUKLS0tIDdibGFNZnJkdE16NUZKdjVSdDJ5
            YW5aMDhjcDlqUThZNjh5cWlaUnJTZEEKJpgX1sfs9TyTjUri34IuoWJS3x+HQEq7
            g6Kma2FOy6P1G7YA9Vgk2IyB50FtNzNxuB7CaMVEWwin7oJl7ZFgKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T11:00:54Z"
    mac: ENC[AES256_GCM,data:yCjTRLAKWkNjT2QPZS1XppZ7QahI0yAvITdJDWFe5IbhFnD/9+YzPe914+/ER6ZiMu2mZNKmuD+nKOpkGQ8+7IoIYg6/gqc4t8sWgiwaPXV7+E4vZrAAkPf2TBJvOsYINx1FW7TvWlDdVZunZAZ25o6SFFQphLSQQ9MPp2+cXjE=,iv:3ma05SazMibYZ6HCTZtPd/UrnHwzG0oATts9ZNbHYN8=,tag:jmZpO1UydSsKkBvhQ48JTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
