# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik-system
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:g8rt7UOziv7zOZtXU4ZtNqivnnM1Apiv14A6fZ9N7unb0NJzZjK/JFbDZbehYdF7Z2UvON4fTLbA+V+fwMi12A==,iv:MV4GZaC29Joo2sYMb7n2qct2Yh9y6GzcnZct87bj+6s=,tag:x2Y6zuJqKKWGVg9+ZiN+DQ==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:mQJQoAfY1aPksRVxeMjC6eVxqVannCFLOY0uEiLbGoQqDtRmmOlocLUjV46ApOVVp12An6G16C9JoMmGsomiOA==,iv:UY+oMBYuy2gIU7Km9IUthSUJbSBH4yOim4uaz/PvsQE=,tag:U8ximaVJbsK9YZs6HbP8xg==,type:str]
    #ENC[AES256_GCM,data:UYekBZwO2g3rgfl0ClxiHTsyI9FseO87U6kNgSh4lj+AQRpwwg==,iv:u6SQEcc+SoE8IHhz7eZBYM2mK+XWp3j+kP6XG8zyDCY=,tag:oOTLND9pT/HhsW0FoPQsew==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C4TPlvTPPoCLy7GtM0NSr5uTK+o=,iv:liNcYvOVMnGPTYMqV46hRu0NJSZREdtXY7fgAa5xOvA=,tag:PJ4vxl1TAJFdCd+mCSCfMA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:i3OSqhItxWlJ6nnjhgVSd3ipiaDmxxLNE5WbdoOLKozD2WgAUZg3ig==,iv:XujBCcrHBXMWF+A03oYJnjcjqdgmKmVJ9rPCsEC5zms=,tag:zzAqyvElDPL66bQ2RBlcfg==,type:str]
    #ENC[AES256_GCM,data:O3kcYzDjmgO0SyqSs1QtIIbZ,iv:FVlYiHRu/7dtwhKNNF3lXh8uz/eeDISzdwkvGecG3ag=,tag:WXf7yXp40w5zkisLo0DgZQ==,type:comment]
    #ENC[AES256_GCM,data:ogl80rC+TlnORfCJm+hkbQW7ZPA09o64oYDsG6h/fQgNSvZYmcGRl6QoLydtLw3K,iv:98WTc3meJFlujiBABJUQvctAYzyyI5GQpjhwi0Mv/yQ=,tag:8qsheytOySpdzwiI1WA1xQ==,type:comment]
    GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:QFCGqjlxJLqsLh9TeCFoghGNBviIj/hHTdmwj1Hi8xU=,iv:X7NYK0AAh87RBiXgGJxuusx/DFy+GYGBlsQlWiPyoEs=,tag:dU8sB8C6hDlkGv1e1tjZ3Q==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TVmGHUN6B9kiQHUUvNpIYad9mBYSt+5WSy+5ZI1J4sWGUMlGXWe/IEPTx4dXPYafW/ZJN4zp3qJAz5GjigQWng==,iv:05EzcY7uH0Vx8yBPba62wzxvGnx86J+tkXM9uY0C6IQ=,tag:mHTUqzOA0hIOnFSSQS8Gxg==,type:str]
    #ENC[AES256_GCM,data:YDt0Fj22LUT7x5fBuZRjGZbyUGo6aC8uRE7g/RVB,iv:iJHZvi+FiIMSqG0DFoZI8xoqWyCGHQ5p0rfnE+oOB6k=,tag:DA5ZCdvIYBGN884JyD3D6w==,type:comment]
    #ENC[AES256_GCM,data:BBEjl3ZqsFXAbyna/3WCrx8qfFUi1rSRIi9YXw==,iv:yslFt25R3dFOXHl17X5dYL/v4AJugKaSgcHGM7+MVVo=,tag:9s2xBn8gkNOYooshCVhfCg==,type:comment]
    #ENC[AES256_GCM,data:aYjVxAPEzWM+8hi3uZSWsUNLsW0Sslzk,iv:N3NSBT6jE7W5x6qkzkugs832o3MFG+4IUQe+k3cJyFw=,tag:XbMUxRqqvBj8ETMtnYIJBQ==,type:comment]
    #ENC[AES256_GCM,data:wy0nKe0ejsIE61G/5fdEbXTR0tTiiMDFTrjTHtkp,iv:mnjmsBAEQrlMM3N8a/O3COaok42zqgGrdPJhbNxhCaU=,tag:i2tG19keudnn/TN0vTaeQg==,type:comment]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdDhuQ1lxUEliQ0hKczJU
            VGIzeEU5UlhlUDY4YXZmaW5oUmZtTjVEbGtRCmRXRnpXN3FMaGFIQXdHTC9FbjZK
            ejI0d2VUMlZoSXNSbGp0cS9MN05sUnMKLS0tIDI4bXVIU2ZZTHYyaVdvVHF3a2Jq
            UG4xY0tkZHd1RDdKL1dIOGN0WXZrOW8KJGq/rUK3QxNcZJ0x6fXx47KkyBPQqpXB
            97/kBnBGrMmQCVbtMgwePcSwllqkEDPf9p601yb2gvWvnbicfAQ+RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T04:22:50Z"
    mac: ENC[AES256_GCM,data:OTXrRJIADMspmZkNTkhVGCW9Bcjz5CQrzbOtPF7//Iini2fsXMsmlryLm0Rh2KX99+3deEqlPdDmzO+rCenZb9PgkVND8dyTzQsMHdTs5bR+UQDP9mDD9stqO3bUDMXzOLgaKdvCvXdHKkdvfbydumtploJLzBKLAmycV2jX254=,iv:rOjh4q33+kTRoSNEHBsrEKw1LC5dZGCbNpdYq3VMKhE=,tag:FF+dhIWHm1AtZ0UjqjnKzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
