# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik-system
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:jYCy0xDLqecuKPcym+nYw7/N3OtWI9TCFeTd7FTyogCNvS/uTuw2OrEjRxvHvurIxNgNBZEPwXTCXh2hAfmZnA==,iv:K5Jjw5FC4QQgvBznwXFIXKOkHWacfrDf7gPsXHqbigo=,tag:HiD+HrGvKThAO4n5ttJ4GQ==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:HUEY/kaYlPZVUQLSKSNHXv9WKDnjTc5Q2RT9UPVhkzzYngf9UcpAmou+TKMBpR4kj071kWQIGM7hbfHAiU7/1A==,iv:KqOMhkFiPAWmtQ6ObInKOeqOZjpPOFhZp47+RvmlKDw=,tag:QmFalyklhw3Sj028G0DoNA==,type:str]
    OAUTH_ROTATION_API_TOKEN: ENC[AES256_GCM,data:X+5L7sYcBq2W5uw1Jp7ylI4rdHxZQrHOrkYA/tmIlTFBFlkrQxe12CFeQ1+xUpW9kGLn5XvfRVb9pm9t,iv:YxjDb+GOuenu8OOxFqCTkig4kHftldsRcHLodxTbzTo=,tag:IaShgqVo1VuMN4Od5VlQFQ==,type:str]
    #ENC[AES256_GCM,data:XmGn8+p+KPjt+CEWi7LbxnQeLXkRoPo/sG9cAjQPQlDE7euxdA==,iv:7joThqD85OOr2QvN46advBDRvNPY4gIleGndQ4NvSck=,tag:gA85e/Y6+u/Qwtdz2aHCfQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KMwOhWiwIECkBZxipXWu67WVoVU=,iv:yfVC4/GFO3UxkZc2MUN4/QXOkZ0h3xGKpgoRYWbuz88=,tag:Ssx+YtPzNFLVNofbUm8Lhw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vaT47rPL5BPiz8n2GOZYELpSJSU4fN8CJhFk9lFNXzwMs+igzscPbQ==,iv:A+JIW/siS4p1y75LcYUriPSM6A1AATh/aPKOWC0az68=,tag:8zbnWjqJui4Mc9b2lCq/hA==,type:str]
    #ENC[AES256_GCM,data:QwvbS4Q=,iv:p1roDJkSj5o9JjcIzEXp53IataFxBrVb8gOilt5LlKo=,tag:2+3IabMZ6JnLFbiTY8GQFw==,type:comment]
    SMTP_HOST: ENC[AES256_GCM,data:NlWJ+M9Uj7W52qT/ypYzE+Pd7MQ=,iv:oZZN3xHt4kjf7ZuX+/ioBkQ6Mwj+bARs/2hc7Z1rQDU=,tag:FfP13RV9YLfOxDiaGdhXNQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:WOzS,iv:fxdo5UleJ06mR2/GGK/OaJJESJtOoCblmHd95tiC/vg=,tag:UO8hqm7g9j1rgyqoNGC8Og==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:6YZYtwOl7GzGnnYrWXKlRrw3bfHFqdDz,iv:ExT1uj9OFQmQ8DyyCoLD9iqEHGFi+EWroc12Ufps7/g=,tag:weWq39ck7tLZU/FfIVAa6Q==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0gGOKCKov6zQJFq08XyuFGr3HqwiT/dcW11KhAlkkAUjwkX797vTfKUJKMpyTdmawAGYUky8ONfQfYE2Vfg1Dd6fXf+baXtLfcauY2Jec79rrBcy9OTw5lGZ,iv:06AdjFrfJqJNcM91TrSVu3Eu6KOpXNs+mkMwzXrzfW0=,tag:S2KCCSng5zIC4FHNH7WR9g==,type:str]
    SMTP_USE_TLS: ENC[AES256_GCM,data:+9DKiw==,iv:TIY5l1lRtNTI68nPnuZE/QUtIAYucyKiDOH2kgvMq2U=,tag:/k2nEBsFSYMoblDTJKHiLQ==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:JRGu2IbnPmSPEVeHTsMnYr0enun/758=,iv:vcH/WuW+SfuNWm7a/IzYfAxXOP29fcABJkI9Fk1mE88=,tag:rz5APTyYCgpBhMuWM2JlYg==,type:str]
    #ENC[AES256_GCM,data:Q2qKrE4k5LqUNkpTUKsn422YRiC6GOLQ3dkfLTfW,iv:ztIde5TCjF/djlIl6GcRViRWCKQPgj18IPxUGZQ2YnI=,tag:BXQiC0Gtdoyb86jSghx/Nw==,type:comment]
    #ENC[AES256_GCM,data:kIQvpFiOr9csqrJxKFrGpDRpKvNvGFDQw88Qhw==,iv:0795BWRS3v1+Tta+lGeasOl1UrNEKzFjAfuZMUvI8aE=,tag:KepVbfWLbblgTVY0YvciSQ==,type:comment]
    #ENC[AES256_GCM,data:efro/i2KpBIsdgaLPbLfK6JsXY7JrQOo,iv:j07pmbWqSLQFo0WwbAz8zR30MoRv9toMMRwSBW+eGyg=,tag:nNKB20TC0bJsQQV4mGNl0Q==,type:comment]
    #ENC[AES256_GCM,data:dzyrH9+tCcGtskvT73kpKSmkFGBU/uldw0VRxIyg,iv:gu1kyK0nlwqDWOiPREZx6XRkpBw4tGFOIpBqLEoWIQI=,tag:LINqL3xH/IkBJtbJKpr3Ww==,type:comment]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMmd1WkI0ekcwRUhOaGV0
            d0F6dWJiQ2I1L1QzQlIwM3NhbFBwVU9MbEFnCm9oL3dYb054UGRyaDA3YkxZZ3l1
            N3pxbmZFTHdvNDh2WUVvZ3R6dkxUSEUKLS0tIGNYTE0rNFVONkJRcWgyUEVjaWk1
            MnlBNkQ1dmJsZ0lxeXc2VHFnU3pDc0UKNtxnDDEDPxUt4SaJAjsfYQlooelck4pE
            Bp0EuSvw3LrUx3F27+YLiWGivCcmYjAEIW7NsINcHD68buLC7HgXjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T10:46:23Z"
    mac: ENC[AES256_GCM,data:RtLnwXp3+s6lk+ru3pKMmSuuAjh4LWNM8ttbSEiN0HFnkIRdv+0575xeTQc/UQ5iD7FA5BJlBZRopAIOFbdQhI/eekUXZS+Bb3Mn8cUsF2veYVJ2YkGTpqQC0LuRX7SedC3FArBFpnvdkANDTeeBBK1mBcGmPzEsfvNBXHaXm/8=,iv:oM4QgRUd5gwztggeRFzDmDpjAK6EjE9ItZU+Nl/3ZnY=,tag:TCKcUL59/iFJ70864ikTEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
