---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-cnpg-aws-object-store
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://spruyt-labs-470715245270-prod-cnpg-backup/object-store
    s3Credentials:
      accessKeyId:
        name: authentik-secrets
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: authentik-secrets
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
# ---
# # yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/barmancloud.cnpg.io/objectstore_v1.json
# apiVersion: barmancloud.cnpg.io/v1
# kind: ObjectStore
# metadata:
#   name: authentik-cnpg-azure-object-store
#   namespace: authentik-system
# spec:
#   retentionPolicy: 7d
#   configuration:
#     destinationPath: "<destination path here>"
#     azureCredentials:
#       connectionString:
#         name: authentik-secrets
#         key: AZURE_CONNECTION_STRING
#       storageAccount:
#         name: nauthentik8n-secrets
#         key: AZURE_STORAGE_ACCOUNT
#       storageKey:
#         name: authentik-secrets
#         key: AZURE_STORAGE_KEY
#       storageSasToken:
#         name: authentik-secrets
#         key: AZURE_STORAGE_SAS_TOKEN
#     data:
#       compression: bzip2
#     wal:
#       compression: bzip2
#       maxParallel: 8
