---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-secrets.sops.yaml
  # Created once by Flux (ssa: IfNotPresent), then managed by oauth-secret-rotation CronJob
  - ./authentik-grafana-oauth.sops.yaml
  # Created once by Flux (ssa: IfNotPresent), then managed by oauth-secret-rotation CronJob
  - ./authentik-vaultwarden-oauth.sops.yaml
  # Created once by Flux (ssa: IfNotPresent), then managed by oauth-secret-rotation CronJob
  - ./authentik-headlamp-oauth.sops.yaml
  - ./authentik-cnpg-object-stores.yaml
  - ./external-secrets-rbac.yaml
  - ./authentik-cnpg-cluster.yaml
  # Dont need pooling yet, if pooling is needed when load increase can look at enabling.
  # - ./authentik-cnpg-poolers.yaml
  - ./authentik-cnpg-scheduled-backups.yaml
  - ./release.yaml
  - ./oauth-secret-rotation
  - ./network-policies.yaml
configMapGenerator:
  - name: authentik-values
    namespace: authentik-system
    files:
      - values.yaml
  - name: authentik-blueprints
    namespace: authentik-system
    options:
      disableNameSuffixHash: true
    files:
      - blueprints/grafana-sso.yaml
      - blueprints/vaultwarden-sso.yaml
      - blueprints/oauth-rotation-service-account.yaml
      - blueprints/n8n-sso.yaml
      - blueprints/ceph-dashboard-sso.yaml
      - blueprints/headlamp-sso.yaml
      - blueprints/hubble-sso.yaml
      - blueprints/redisinsight-sso.yaml
      - blueprints/flux-sso.yaml
      - blueprints/firefly-iii-sso.yaml
configurations:
  - ./kustomizeconfig.yaml
