# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-ssh-rotation-token
    namespace: github-system
stringData:
    GITHUB_PAT: ENC[AES256_GCM,data:wGG16JLnJKUAKqbryDyZQMw90WZff9fWy31OEe6yYhHkX4sNj5Fa4w==,iv:kyPUeKvMVkXAwm8xFrXGD+JA+ikdu4vPVENEgbMJcB0=,tag:AcGZWluyRreCn3qkOeW6yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ejNiYW16dWRsaDFlbmFy
            ZzlrNUtYbi9EWUw5dVd5THA0RFBHUU5WSEd3ClE3YXRVM0pCRU0xdFBxSkhWRnlU
            UlBKRnZkeDkraW9UVnpPVmcwd2J1RXcKLS0tIGh0R2lSczFDVS9ESkFTYmZXUU9k
            dUNTeEdXYVFiZU9jd0lvK3JGVkxMSEUKDlv3wB5HmF6UvLwU1DOeRDK5Ia+VpgCK
            m4PJRYPuumWx4e7Oe8KZTk58yyY2IhqJGYyy7cvPCWHI7ump4ZjiMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T07:45:03Z"
    mac: ENC[AES256_GCM,data:4Z5NNaaVnUVSGDQ7ZNZ0Ya1s1EIOV6v7bQKGuD7itcr0puDjKoRq1eQtVmpSagIl0qA/RXYB8ZilvP8yBnHx5DpMjaeU9fkWVZieFKORb1BgrTguuhEYWk8pbiA2FmUzQ4sAd4NYYRkoZr5O1rJLJO6XSZK2dTR1FE6NRPR4ayQ=,iv:ABocKugfSyz/nlGsGHpJFSS95KL7pBzB3YjxlUWxsMM=,tag:BrLamijmPoV+UBYSg9cA9Q==,type:str]
    version: 3.13.3
