---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/velero.io/schedule_v1.json
# Velero Documentation: https://velero.io/docs/v1.17/api-types/schedule/
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-wide-backups
  namespace: velero
spec:
  paused: true
  schedule: "0 17 * * *" # At 03:00 daily Melbourne (UTC+10)
  skipImmediately: false
  useOwnerReferencesInBackup: true
  template:
    storageLocation: aws-primary
    snapshotMoveData: true
    ttl: 336h0m0s # 14 days
    metadata:
      labels:
        velero.io/backup-type: "Global"
        velero.io/schedule-name: "cluster-wide-backups"
