---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-volume-policy
  namespace: velero
data:
  policy.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          pvcLabels:
            velero.io/backup-volumes: "true"
        action:
          type: snapshot
      - conditions: {}
        action:
          type: skip
