---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-cluster-daily-backup
  namespace: cnpg-system
spec:
  immediate: true
  suspend: false
  schedule: "0 16 * * *" # At 02:00 daily Melbourne (UTC+10)
  cluster:
    name: cnpg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  backupOwnerReference: self
