---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs-app-template
    namespace: flux-system
  values:
    - kind: ConfigMap
      name: whoami-values
