# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
type: Opaque
stringData:
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:C4y4b1IfQLKKp/Xxrm/Y5NdKXHXn20kzfQ==,iv:pk8zaUQ+F/JpTxf6hQZUEWb4JfqUsFeBWkHVxLrj1Gg=,tag:LFFleei4OELL+4+rLt3Z5g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aWZHTitHVlEwNFFCajUr
            UXJjYVVtU2dkRGdRcXViMTFweEg0T0FybERVClNBZkhuZDBFT1hiaStrMno5TjdC
            eURHaVpwMVV4K0dCdzJCSGhYVDNYZzAKLS0tIDFBK0hpNFFkdGdNWkZyUlpGcFo0
            VWZIZnJUSmJIK3BrT2JtVmlUM2FaS2MKcvHy1+42qdwUPxWXYlKzBZFjvi1CprsG
            ik/nsFe9eCTwjYZIhooJsRQ9/mnYlxI7ppNOyYTILC0BIEAt3ERLYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T13:41:37Z"
    mac: ENC[AES256_GCM,data:lVOltXALea/Rtv8yyAnT7BsfpIzdwueneqBvdQwhBdT6hFQBzSXM1iCCG8x6p/z++2SgeaIdVZV1aArZBpr0tpmRAuHiALxB78uX3H5Rc7/HXkdMjE0X1a1s/2DkFtMVUfbXvXer9H9s6kf3opBOx9mXT/AVfBLTnYpbjcfOtZI=,iv:LxDa0NDJ6pnRhEE9KQEReFzBtOcpARPBSv5mrCqOVXQ=,tag:zn+8IrdQESL1WYZVc2WQYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
