# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:1Pap4h5H7ENBOkkae++QuD6YLOTEehGJfcGUn5QCHO3H12klqcXP9gIxGcmuslV6EKwu8jdEOzZeUbI6+awoCAl2AaOFjpMOGQWvoXEHTAiW8EteacF2MpSBbxXVutUv55ivih0d0CvyXv+y/MTwba2Kcac+XKZ0RMf27i3jyyC83clTaWEPPgqm4Es30Pnu+jGRaQvpfWpkggt5oBHR/RggMdJUrR8jhWMfwc52jYeTT8xmDEcMFvJF6FLfqLTpjasGfZ8E21FF/zUCIcDQxNhuFqYBzlVPD+cRLxHFiomX8NsvQFbRtVip3FfVu9r8DRp+LZdIYj/1lh3mvWKP5jgjEqC8dg0+AZKq3tdnnYocDcPxiPROaMbVumcn5nuSGY94qB4xSUsVBnRn33y1I6oO/WTivL/5lSGqBZREzy3e/0qvLXS+OHbTlA8CB5PoZCelQ4bzcF0OwNLVaB7ALkMVsBjHIv0BA5PxBZs9RP8zTo2thHOVYj3MwufopcdBq0bCDhEew+bxGXCQ/QkGkRuADcCwOLtCJbM42GukyYeC+p41TyEitqUZpQUqLE6rg60JosQ/xKy4VWBxgt6LIvMIU2ceYdY46QNNYigtFYCDfgpaglqZHwDIeTmsUPkgCsIxD3l/M4rSTujddSUkVa+v0VRcAoM2foRendZs5zoLG2rh/KXQ2HvIpct+05YU9va1Rc4ShaH6osSZfrldE6prkS+B6ulxVHurLO4I2KP0iKE7s521oJLbnjc4lWBfDfou9foTUpGVubGDEM5DqL9JmJVl8Ml4pyer9Kge/Mp0HUpv4Ajr+X36kOVsi6hVagYLs0ScoC1y+2wU0Cv6pcCIHI2tuVfYZapYBJYTj8MhZEnw4vQ7UAaPG24UTVpKZtSy1z2SCmfN6rHvVG815Vl94Ip4NbUy78siM9ZS/5oTYi7V9TujmegjskJom3SH2I7dqGD6uA9tNHIHs2cSHvEuT1E2pFeWKA7Vw9y8RBsrGRr1tPc0++wWOil4ofDvvM16G32DpQlGqRcp2fb0qxO35UhQOHewINlAwNPKUQA5z0SPr1CpgJ9obf3L1T2A844=,iv:pUtuOUPUzBXfvNuol2svTrcraTjuGGlgGayz2l7Ygf4=,tag:23xunJry596dtAgMip8OBw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVViU2VWcytqRTVkRnV5
            TnJ5VFRDNXA3emx3QjIvNkFmd0RaZEw5OER3CjBuWUtrczRkU3NyMm14YXBOSGta
            aVFyMGhQZGdoSUxPYm1PbldQbVhPWlEKLS0tIGJpaldtQWZzRCtRNzhUVXRJbU0w
            V0d3VVN1V295cEJSS2UxQ0RuTmh1WTgKI+XsfzoaJkoC73zQ+tZtJxyRmM7TiqFM
            1FIU6zhWavK7atLfGfYzE3FDn/jcVnpYLuD26KP+nE5kNJhY1jfZDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T10:35:25Z"
    mac: ENC[AES256_GCM,data:0P/tEa7IF048RavDNiO94CO2cIZicycXCjDn3JrRHdiUGieyrIq5aCje5bjAUKpWY0nhA2hQ+PDtD38tz+qad/K4+AqOXcaOKXRvn8Ucxt43Td2uOAj5xzOgMGx0VmINAeueFy3KGJ1W1XgvzzR3fh/xp0ITFCBArffB9yUaVrA=,iv:R6XocFxWAXcpXfHo0MlT9pZFNqWgzyn6z4w5jY1nVnw=,tag:Z4Ttw+BXBsxwFeqoYflwaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
