# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: monitoring
data:
    alertmanager.yaml: ENC[AES256_GCM,data:UGUXxyg8T2QXggzkPktdIc4CK4ApXJIQEjjl2nArpJS15738iR0e3ax0rfx2DwE8sPa3xYJsvQ37ojl4dFPO8V/C5NEh+CLPEC1TgHBSEkoC7nUmrBZN/YuQHubAfIdREfxEy4uBehJObq8GTJlFk6kTa6+zCpm1mE4qY+yYrMBvs3Zatk5f6pl6/1bqf0qbJgUQmuDlVV3XJI2JQUS7Xs1tEH3aP+mQI8dnfT20HFTO+xRH9jz9QdRE71CY/nOcE4hDQ7351kWquDOlWKU1N7WwFMmYzs874F18Lbq6xcQhq4SsGPbnwcBRnSCFij6cKpIdyBy/sdGSK+J9fBIsrBmoSWw45IGh7zj7Xr2IHzcNpEW0KhMjFYSyUaU0jo6Q+OQssVNUVC3ZKbp+hIYJxWz4QvmZaKySYmaERuO6R6xvxdIf3NpBUw1eH38u7zepDN+q8jvmt6ZhfVClcEyHV0UYfZJNfu5trYldC9No0tz8guKy5gMVtCOnsbTzAPhCukLpn0gEudkq65ec91wT7iQB7fqDVi4iab15vQ8KYvKpublaaBEKkQXro9nGjCDSLITX7JNVRcKi2qS71wmSeTZ1OgetSMRiu7LChFQaMhT0sPuFOVp4sm2Co/1jqh8LXLYso5qCQoKO9DJQqcevL9p3zooMKgT2ncENE8VeXg3WTXH9lSfS/2BBO7iq6wM25ZZqo7AEhBXtXBmm+lkXNwFyvLW7/sjE+mvnd7RNAYwgPpplHvUc4UkFh6itE0g3xvtPfNGNZGvQGbClXIJH2UvmPEbbpsosBH9XrBDES8v9f/q+0hzQkrG1zLG7ecBqcC4QgyXwgKRrcsEL7JkVg3YhTxEN6atILocde4ZcxMo/7X5Ku4OZ4pQMFnpkuuUp0dfoOjViGbOEhm6PulZQ9+StSmtImpN1lqwK1pr6qRynwQI11hBSVEbtVA0TUgR7tTy0y8tBqerwJjJTJ44WGdfDUXkje8qpN5zVw6DM8U+27OTnjtOmmI/goTSJdipXcjrkYqdxgEPj2id/7r/+rhabDWdFBzDS5n9/L7tAbNjoqisXnWkwImkdM7uQy4Y0I2Q=,iv:l5cADZ69WAAmO98/9YrGmaboEAr5FpZu5damCRDzk68=,tag:aaFDY83LxJvSlm+3ofuyhg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydjJhV1lOTjJ5aEVjVzZY
            Q2M3ZzMybDV3MGltaDlacG1aclVVdmJCSEFRCkpVSHNzRXR1ZGdMUWExZjE4N0Z1
            d3RIWFVoTnAxVXI2QXhPZDJlNU9nZ0EKLS0tIHJBTnpkazI5V3d5Si9ETitQM2dj
            dkU0ZGhETXB2dTdUQ0FDZ3hKaTdvTk0K0gQkqxT+Rgm+DnvUUXUfQtdEXL2Cf332
            eav1IyfPUJzDwWHsLF5xC2oG/5POSjw6SntCbf6qEnZQNcLaPRIc1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T10:23:40Z"
    mac: ENC[AES256_GCM,data:G7QVevKdON1qO3U/zj/1DNZbQ2RyaSo1wvCXx9m0m7NDZKzEgqcIBvx+E2/WDuT43ybKLQrN0f1d52MERGtv40uhv4Z2smr+7MLwcrRiZWx9bLbcER43mA/lOIBoS3iuwk1n/9QX6VKO5Q1w3xeg5pk3bKMEqjHyBjH8+GN9Rls=,iv:ks3xCFehNts/8E9a1VBP1MG64vcBMkanoQdDTJCuhbo=,tag:73N8qdY7sn0toWJQyI8WPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
