# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:1oTrV7L+apZBE8mb5t6c9JYdAltvZ+ecbvkaUjK5WuYH/M+4tpptk86Zpg4q5XIUfvSYNVdp3RkQLZDI5tIIXU8S/LbXfVDKv3rDYa21JzibobodVyBr3wbE2vz+d4M7+ySS716vI9ayFaiudMkspB/1l+nQ8pjqwKhxvvTgQSnf9rDHvcOi24mw/ajD3k/WLuSlkeGnjafaX5K3pFFq8dFGtVG8D2UBX1v33H3d1bWEgH8XIrBBzA547HilWtEOEBUu9kgtd/GHo+w36ta1Y4aWsw25tqx3/xgium4/kxxiY1204jDY7Z5XtBwQ8EmuO27VW1h2zAG5kGtx0gJ93HyXHXS6pSehwqwlWpJvTLo0T8/qiDm1k1z3rkxcypPrba28tIyaBFXxUDdL3ghuqpeYI6jApfK75xKIr9NTo6SEeoxNlNvr1jLysF9rWPc4oYwwv856D/MgXYXpKocpUo246Ggpih5gzfk8d3wp1vdVF9cAGIrBQVjk4lOIBTDMcf3u1wvsNVMIW+eT0FNcDLJugwA9X2Z309ieSbLd0DnrNGBqyFIbmqo03nttQYSlh/3I55mGoukLAZmoSNnEN8FOOWzj5no6KA9uQMBLxQcBJUr1a807bbT+OEE6pnbSaAArp2dVvLl3FK+DFtdw0L93IHr5t6BndJjIqJ0UpgoMCED+F3nKqWgV4EAurn6s6ZVMmtihvY/C0i9zWBZlJY2qrDpuSJ76yN2DJ6wp/7O6M7We6oX+sHTQxsLyxML+w2CHt0318208YYXAo7tNW0q/t7X6mIVW9mNg9JVKw2fwS6i1p0Re1ojRO9veGIDWTKJCRK40Dj5IL9Olndjr425DSAh4JBfkmy6h2+dWYmfkS/RPL16ltNmJYtf/qLjiv+NzUkPQ6gUJUKweP0vBgrSHruFiMv9h4OYKopEkUGSvSq4wZGWPwslIQvr12PdBimd/BG9qA1NLpRa9+9IomkKssnxPFojRo9uqrq12aTtQRua5S7GV12sJnFJt4eWAnJrwsEVP/bVkUp2zBZ58HBqMPz+uLa0e0icAnKk+2DuYCEuu4vso1fqPzlHqK9A/ZAE=,iv:SFVt/hidS0Jb18to7feZl7FROxdjTZBddSuhot/ldQc=,tag:0tRsyPO6U/sLLg7/2Ht+FQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVnE3Vk05Rm1UVCtiVUlh
            MWZ3VVM5YTMvRWFUa0ZJWjdXZEIzUWovZHlJCjFwWmpzbWZQQzB1YytuK2RqWmRr
            VnRCWlpiOXVoRkcxakRuMWpacFNZS0UKLS0tIG85b1pvMGlYTGZZVGFCMHBNcVB0
            bjAwcTk2VkRHdlVldXZndk92OGZ5N3MKQIsePZsQlZAsbyqtZAcbUHyZAXOKM0lg
            KIxcTU0gSDS+n43WX6o68vZDLo3TufDzjMhCrG3DIof8LnVNzVqKFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T10:25:17Z"
    mac: ENC[AES256_GCM,data:srTCJcrsMfR4w2m8sDymRRbEm29jyxDWETeTKJsm8bG6Kb1c6d6wXjW5L8KQahryz+qk1vEulejfl1wv4L65MWUx348XQ+GSy6qQ9K00/cep1FeZ09V8TwyoiMkZ8On46ioMWW0vE6M1WWM5QVuVHd4fZXqdi9iejGjpP+GU6fI=,iv:YI77+sMR0MIVJU6pO19a9DpErTDaRBlnUByvQpW8r+Q=,tag:qKW2u9Ro0YIoYEFQD2UAMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
