aws_account_id                      = "470715245270"
tfc_organization_name               = "spruyt-labs"
tfc_project_name                    = "spruyt-labs"
ceph_objectstore_tfc_workspace_name = "ceph-objectstore"
velero_backup_tfc_workspace_name    = "velero-backup"
