aws_account_id                          = "470715245270"
aws_region                              = "ap-southeast-4" # ap-southeast-2 = Sydney ; ap-southeast-4 = Melbourne
tfc_hostname                            = "app.terraform.io"
tfc_organization_name                   = "spruyt-labs"
tfc_project_name                        = "spruyt-labs"
tfc_vcs_repo_github_app_installation_id = "ghain-aVHQfeHpX47cqiGC"
tfc_vcs_repo_branch                     = "main"
tfc_vcs_repo_identifier                 = "anthony-spruyt/spruyt-labs"
ceph_objectstore_tfc_workspace_name     = "ceph-objectstore"
ceph_objectstore_tfc_working_directory  = "/infra/terraform/aws/ceph-objectstore"
ceph_objectstore_tfc_trigger_pattern    = "/infra/terraform/aws/ceph-objectstore/**"
velero_backup_tfc_workspace_name        = "velero-backup"
velero_backup_tfc_working_directory     = "/infra/terraform/aws/velero-backup"
velero_backup_tfc_trigger_pattern       = "/infra/terraform/aws/velero-backup/**"
# workspace_factory_tfc_workspace_name    = "workspace-factory"
# workspace_factory_tfc_working_directory = "/infra/terraform/workspace-factory"
# workspace_factory_tfc_trigger_pattern   = "/infra/terraform/workspace-factory/**"
