# Path to sources
#sonar.sources=.
#sonar.exclusions=
#sonar.inclusions=

# Path to tests
sonar.tests=cluster/apps/litellm/litellm/app/plugins/middleware/tests,cluster/apps/litellm/litellm/app/plugins/chatgpt/tests,cluster/apps/litellm/litellm/app/plugins/hindsight/tests
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=

# Python version
sonar.python.version=3.11

# Terraform AWS provider version
sonar.terraform.provider.aws.version=6.19
