sonar.python.version=3.11
sonar.tests=cluster/apps/litellm/litellm/app/plugins/middleware/tests,cluster/apps/litellm/litellm/app/plugins/chatgpt/tests,cluster/apps/litellm/litellm/app/plugins/hindsight/tests
sonar.terraform.provider.aws.version=6.19
