# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: foundryvtt-secrets
    namespace: foundryvtt
stringData:
    #ENC[AES256_GCM,data:sQl6/0ONQWn3JNJBiMgk/1apJR0ceahZh3PIN2q2+FjF6c2BCK74PqvLLiu60OlLYjACoMSxlSdWg4PRmRhDJdvvwhkI1r5LP+nU6kTpX41rMbNisA==,iv:bCbyz9iHOqBHUMdidSXwTRxYXRLvoOJYJLtQsly3rVk=,tag:hmNmSlOitpPlrp9jOPVajA==,type:comment]
    #ENC[AES256_GCM,data:MDiemfROK18GLZDPzoc5iBhMSItl,iv:gvdOc8OcXqkU2OyhxTm08FLi4TCniPg2Ru9HBzyvZHI=,tag:gAJUz/pvEwm/myJqkmnffA==,type:comment]
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:pxuPu61obw==,iv:5svy3evewR4rC1Db1DTJ6h6pawEhQFWLnczTdtVWOJg=,tag:A2YEfYZgHCjZFQSRZPLykw==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:5BaGQngcS+hQJAYY9h8HTTfj8WR7QlA3MTTruNIRUj32Tz2Mqhe++6QGqvCZFVVJvOGYojsCi02JzifYHCynjg==,iv:o8T0P1XJ03+XB07Lv/ETvzfjDXYBhow2uAHEL/9uOdg=,tag:Wx5tndhigIrq/ZfFi91tvg==,type:str]
    FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:NE0A7OkBBVleRG41gtrV121k76ma6CyBrBVbVevbyhOYfZ0sZ+eAziYk2XFsa61sLDHqa1zxsZUdbuVgMZZvsQ==,iv:JoN/2K+WhkpjB/6ORrfgL8x+zmIRPHFXj78+69e/w+M=,tag:zxZp/fT3pIR34/O8rCO62A==,type:str]
    FOUNDRY_HOSTNAME: ENC[AES256_GCM,data:kOBQ/DfHtn2qXJ5Ek81WVguL,iv:Lep2pLUXijiCM2WNcTeqT6Mq0M2tuk/gMqvKOFKakZM=,tag:LNsnyWhtzPIgcEO25+Tz/Q==,type:str]
    FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:swpyg59q0hTBjvojcSYiT/pnJXdQ327r6dW8FOs=,iv:8BQcwdMXBizam7yqC1k8lSsD4KUzV4REhtscWP0fGvQ=,tag:XbDMXAEVjXsgPkZwH5/Z5w==,type:str]
    FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:iIDLw/um0j837asFd6kR37sqRy88WbkeEmXIkBMQEwrHou4/gtW095C6Q7gnV3avWb7AFb+rdj+7+Sm/yDffaQ==,iv:PfkUoF/C/61/cmlRDG2l2JQmuRcfWArQSfWzPAJ2jk8=,tag:CRhWpablXX3Ukv6AtzZrhg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzBXQlpCa21jd3A4a0hL
            L0s1RGEvdmViS29QZjFvTVRwOFhkdVZ4SnhvCmYwNFYxeS8zbXZob0xZSXdwVXA5
            SlFVaVJWZkdKMGt5SmlIa2NEckVManMKLS0tIHhpd3BIWFd3SExyMnYvM3FZU2lI
            Qm9JZUZuQzlKMCsxUlpsN0NaWkszRjgK9STGVIIhobw30gGL1xo0sUdGy6A5gZy4
            cgR1QTsZndgjqLdMB821vLcMJ3xrFw1w2QZ65ft+5lt9bjNsUgQ6MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T09:22:04Z"
    mac: ENC[AES256_GCM,data:jTbOZxxTqUOLMBhe//vLzWiBaQW+udjRyl5UkklDzvsnqsVYMR07kNAnB7+KPEhj0irndbezLBfByCiql5kSv3eR7Ym1kiOEbSwuBp/v4Ivo7cp8siL1AkAwZuUQI0alS79gsYJH0CHlqAfDTZAkSPQlR2HdOE/w+vSWCYBLYp8=,iv:+Wpu9m5blo9XmBPdv4oOK2ixHQeHH+7y+KcfImun7SI=,tag:zcUoFM23nXhWzUix7NWnLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
