# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:i9SvzwGV2f1LJ08UrVeYYJFPKzRKKi2ma66Qem0VNBKtF6fc00VuhqdHtaxnIFduML2fm/ZofKtuSTvls2TKQjh6C7BB65ucT0Jfhfug2Vmh4gmJvJ3y8Fa5ArUp4j+6MksPCHnAuWhMGR2H6mKYseD/YlzdYx1CFLhYSfn2ign6pDdgArFowcxKPX/vYS+90j3bgCdpOOrbhG0MvGqXJl7pafwbV21Ies1JD4RvNdIrH8fuwBqG2bdZz3OjxRlxHE1EzUQUkEe46bOYwSLGSCoc7EymYBZOJEBHSyIzG5txF+/4YMUvbtaNkJfo1M9P+Z5Oc2IZjL9JeTDdxoG2g4OBBAUaq2BUZRZIn6mSQ9506cjkO6xw3Ve2y0gRG8CU9/4Q04uVM7ygLpBQSo4ZP7zT1arxVNXpM4qDE58FIAEmdahK2l0RfqVIbrGclNhulYotZcKlwZy8srZe2yfqQQsP/H+lxB9b5WEsWRRqU0KeusIm8GZ39+VKfaK0nZ/0FEcW053WP6zuojlAw5xAMijbiR1z8nS3aIR1qMcAEuFKKtdrjacNPm8fVUQIUgKb7iY/e/y7RqSLqTr15dn/5ogWBXnC0UjEVuN7AVNwgc6F9Q4cbVgSKjdfiJtusPKS7dIh4xNoCcYYg+PeuI1pqQ+xBNFuhp72kbjGTjPqeqKBmVAJFKdEQuUck2UpdeY+M7OnVMxGmOWkHeWR0gZ5Gtt9hpcOjPUSf0+b+gADgjSWfGmOkw3KM17mG3l6MXx5QAQrdVM1k1FthOYmfqIzDX6gQ7nYE51b7cesUZ5Kw02v243Z4qnxqHYBjqPhH2C96grUXgNoaresEA8T3Q0Pzka1FwTRV1alIhIOhsVBOXtDOjkcsEU4cxOo3hi/ylIyAg+ilICd6Qixy305Jhl58cyXlHMhfbtI3M/oyEzHAJjDJWcl4mRTSIRI5Fgq1+DC3ZQiF/gyi7bO23qE/xtR5U2LCGVUb6djeaPDbX0+gcYv8vMxTbmaTjUqMSVw+FxEqf40JmKNvBQsAxcTuAJMwTUTydL17KjYycHJYAag938Uzx8wpMfIyz9U04yeaFQstdU=,iv:Qj42mufeSSx7O/xbOCGW1CjUOwqJll7+AAoKxLqhgxQ=,tag:lylSxyJpg4cxhyq8xBZWIA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRlM4REVzN0dLR3hvRzBn
            QVFNaXpHQjArR0pUdlVJSGQ1K2lCLzlYTGl3CjJXS0w5OHcrYVVnZ1p4dTc5VXMz
            YTRZdmlraGczcnRaM3JFSFdCRlFBdzQKLS0tIEtEeWJoS3ZycFJaNExMNmFaMDNh
            TVFoQTVRdFh1NjduRHVOQUxkMEc1blUKYA1yF55ffpEQLaATGMM/F/jovkKmLgmL
            cTkNxdBpQdSlfDU3l+NlYrfMsel1NBwCRyMK0Iyx0T46fdFDJraE6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:56yd3Su05FfaAmchSu2hgcYZjYwFoiM8p+EwwoqsJpd6tGL2Ue+OsUFNWnlrkKLZ6idKoN822R2Z5dAFuIKe7zspED91oS3+rIPZlZWZLd28cD8T8vDxkmoxhNOOnNZqkyySCxrRNdqJj0jfHy/MBCeJmV3Zgy6ZCsP8K8DogIo=,iv:qd/TA+JnVc7hPxNboVGEhC6sV1s8DIrcTUEXFH8TCv4=,tag:Qv/drDhP4Y6Wi87KT7Knfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
