# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:2vmW8+R8kP3KZM2eA3y6qFMMv3M0J6MltNKQLzIZfwVbdpiH0tGUX6tUwmTe+WZihHZGuzqhEj40uOiexcgykaivNknNdBlHDndkNwCrvl1ckBm5G0p01F45OfDoD5ntEZ4I9bRPlHKfFqfvtCLonKmhXeRlt80X9a2YMFPGLmDivzlbMhKA87vqSgppeFcJBaktTYnn7axRWbwbbxjHOFigR18imIed8/n7evPXB7Vt41UEZ2cTUk/9Ib1UgN/7GWVKM1QJ91R5IXvIrZoPjqOTb4LtdoCYDdFNTdc9NH329VWoo4XcXwG2itYPb40Da5WCP58KBKm25TSAMytvY1pkC/konISzo9qniN4Oa6FvanSX/mG3K45vzYkPAmRTprX5mIac0J+DYqAoTA4iXCNcvIC2bzIKvybW2hx7FJqPBlaQMZdNYnByJP5dvNVNDK2o1hbHurD9QD7iBh18MnClnLnC7tlS89Clgvm/4/8Ud+cwlRVwzzh6O1odnDpvLjD4PEKhB0TvVr0oj8ypoOF9wI83Ho+m8GL/X5YBJeYjfRVsc9FZTSyk9CFh4NIPh9zhd2wfcE/i5UA6tQhTv0MDWN63QTVoYnhtO2lNjVKq9d2VJAfw/J8SUFDhDHy8HHbSfAAUGfQhCoUIq2hT/ekmgPMXy+O1WbJ4FFOi3eJdw94AK9oFml7z8tRO/IajZDYH/aP+AqVBYwHU2gqGYjFTGtEJTJYvEbOF3QhYNUf3vRsDPecQ5IsojWVgf1FvmpcxFjRtVHZup8IixsLBKL84wPraS0qCq7x6CAN+b43QqSrQoXBoJiL7xo51Boxhm1bYohiLQv+kSyNjHoRG0hPLD85QEkOEYMk7+U6NfGq1lzPXRh2Dc356uHZihDqkthhh/WrQPTejnaiDhpUUu6QIGmYCQrHWdW1KJ9XaxNs8aoqpc2EXhvA6hEEtKEkHFNBI8TLfSEzCzVVXaU2i+qym4WQhuUFrWB0VIepG+s6nMJV7BZulcEX2ZP+HX7gqxmQMXuIIb+p3r/LO5yUyC8HRXiAh714AGWMynP9Uivl8BJTv0QbnXBk1P8XAYMlueUg=,iv:GAkfUeGdHgC2j1Z7cxpcXplmzPn1CSvWV1iPNTjWyYc=,tag:b6qfK92r827T246qvXKLMw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aXhaS3dnZW4xMHZEbHNi
            KzZzVU1VcU9uaUp0OHAvcDRKVkQzZGpiSWxBCm5UVmZYVGp3Z1kxVG9Ia2d2aFZa
            bUVEd1J0Yy95SklGYjlJL3Z3Y3N5elUKLS0tIFlpZmJudEljYk9iQlNYdE1hY25r
            WjU1eDQ1MVZad282UGx4QXVLbDhoOVEKUK6HVNBBFKp2rNaZgV4sSiK3R10GrYDP
            KLpCgkWV27M2bRh1FSwE33PBF7gN7O1aCLrtvFhf7dcmprqvrw5bAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:50:41Z"
    mac: ENC[AES256_GCM,data:qzU6ZqKlIpQnzK02G/WP2tqq5NXKjV/0J1h99w26NbYPPec5Bq5ItpzL/RNy5ljm8TBpil0/N9qLq45SfN10GodZg+CoEy5MDjf6IlyLEq1b20j0VSEqEJm6TdjkvjhaZWiOvsRFOHu/IzfYatc1GqcglhsmOohRE2U3CXQWpuY=,iv:FqUtXt3QJvcwEJ/edntwa7whKX3OYG6gW8TcWcHyMa4=,tag:xImVQpyFWL09vDBtwlB8MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
