---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-csi-addons
  namespace: flux-system
spec:
  url: https://github.com/csi-addons/kubernetes-csi-addons
  ref:
    tag: v0.13.0
  ignore: |
    # exclude all
    /*
    # include files
    !/deploy/controller/rbac.yaml
    !/deploy/controller/setup-controller.yaml
