# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-logs-single-secrets
    namespace: monitoring
    labels:
        grafana_datasource: "true"
stringData:
    victoria-logs-single-datasource.yaml: ENC[AES256_GCM,data:8i8qp5fi9srLfhiCG8M0y+xlrDXdyOEl12eyBgO12OoBee3v8NBk7jp3kpVeL1IWdp+HMVlXiXW3DWb/bHmmOqbO1mzQPY3lh/r0SML+xuoq+7kSVp26ceYzojvVX9jXK7MfhBHMSe6HGz2aDuaH7vz40RRbzZ+761kecp+nQ3N/87GG8crcsYZuBTI5l/WTqLl2zJwefrr4Bpx1cWtEYKnjFJWX0NtGdfKmHiQXZ/dEOMzosAXKp7f9B3G9jCBJ6JJzwzUUv+4fW2GZhny8FlnS4ErMHw==,iv:JA/f8Miu8Py7ucVhoGIFUQv+Vvf5QK1Tdiv3ngleaY4=,tag:Xj91d7HoziFv8+4weAKDOQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK3JJZWVEbVF5SzdPbFlG
            enZyTEplc2djM2tIYmJWK1dGVTFFQjFjMWpZCnczU2tFKytxUmR2TmMzbkxHdElI
            aWo3T3NTREZOMGNHdW9LcFcwRGg3aTAKLS0tIEVSUk8xSzFZNS93d3JIMVQ4RDd3
            UVNOTXNZdHlwdGtJa3BoN1NjQjVZRm8KKJUw7D21s1i3e/d3kuSWwgQeZ6SHX4jU
            1Qxx6WQNHCP8Eb8dFCCuuQRrJK8kriJHJiYBKzSYnWuYxgsFlsXq+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:3Fk2yno4wj88swWKWy4uPJLfTy8RXUSUuwzjmSw97zAdwAIBpV/gpf5NQ32Msp1bpN8HbAp72joFFTJzzGewnrrDeTqZF95g979QW56AFjrbVKSoKne/VBAm8Vcq8uBjFHEAcvXmUKcXjCI2xSuPDDB1HH8YguWGXSXnWRoBxXI=,iv:7RyFhzZ1yty4bstKIC+cB4woCArEYEwBSJs/uyA2rPs=,tag:vPKAPLI7wpPpDAJtezTVGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
