# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-logs-single-secrets
    namespace: monitoring
    labels:
        grafana_datasource: "true"
stringData:
    victoria-logs-single-datasource.yaml: ENC[AES256_GCM,data:Ou2w3osCej2u8c8cPZB7yEu+pLwO/5c72+A06YEuy9ehseRN9J/M6EMNazjLaECq4pA6BZpjgsnEfUUieDQmtlCH6IJ0ubWiLX/PD9bM8XsHYtMLO8m+eBYG7I4Z8wbUUiq2L9ZF7ism8moC87x8Zv4Q8MTUiPMl2P9j3RHD1HgQKaB5qlZAnVF54AyOTHW64vHlm6nMPZe3uUtTdIR0jZA3SCbiTXvwR6AL8Felrm1KaDJn8Z7k5TIJW1yU28ixTyxCc9RwTIzDa5QF5Yg+j4pa/UB0Og==,iv:8MtYD6z7lvodTTW1/xUwqlHzjlNmQhAHbtL5ztRsOWQ=,tag:zhDjYA6ct3DNhpGJyIwrIA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N2tpaE5oUVlpYzBVbXBG
            dlZKZnV3ZFJJNG11RStWL2Fka0VHRXlyVkU0CnJpbWRKSjF6MTFUY0hBV1BPM3kr
            QTR2VEZnMjIveEZ6L1FUczNjOGtlaDQKLS0tIENEa1VlTnZFZXhNMFlza2QzbjE5
            enIyY1I4bjlFOGZuNUZiN2pqZy9PN0EK9cTxem5UV5u3wF8PV/BmHhWszfEUrYof
            xu/igRXfWqiP9ZtFMHSPLvL0B3khHKKuS8r1Ta7PX09k4zHA8hCBlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:50:41Z"
    mac: ENC[AES256_GCM,data:2gaZ1l+2GZSpNkodAbIiizQ36BMZJx2PRiLaqgrE1+S4EajKMiaialXwXM6hzYjSNcY1TtDd5skk7iayE9jbjgcYinrXTiiNalx45Z8pxaMbn6FWZAlnBYxLqnzUd3PJw44576zfw+FGEZ57jAloGwWRIBbnuExCysUq/heclAs=,iv:hct3nzha37D/UpBdKugYUHn837bj0fYfKjc6pTjDfMU=,tag:CmABoBwvFO1QFJNk5QhxuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
