# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: valkey-secrets
    namespace: valkey-system
type: Opaque
stringData:
    default: ENC[AES256_GCM,data:9i6KVSfrthFZmC0Vhb3kwMOUsAseJ7zlJeYtBttDbWc=,iv:Dop59ofVu9oimcKIskteSVqOhXiRLU4MAhOO2dgcQiI=,tag:jIcC5JjSapCLgHttXGtjVQ==,type:str]
    n8n: ENC[AES256_GCM,data:yUApLMIbQMGrcJImKINEiHLuU2qYidUNJsc0FEc2WA0=,iv:DtarfoAGfZuxHClcq3nK7v57r0VR4cyBc0mktOFwc48=,tag:vKYxXnka2hN0J0z0EG2Cyw==,type:str]
    redisinsight: ENC[AES256_GCM,data:jXcGPZfLa4583hxamQ6+CRodjZsdJcCKwWz1fJOEB30=,iv:mzKpNb9iDl6foZlseSc68OXWuWYKV3/YdLwEQw7iVT0=,tag:cKGa+twfWF77C+aGbl1UMg==,type:str]
    authentik: ENC[AES256_GCM,data:qf8oPwSq1u0VT066oYCnz1GJi1YyGETmT1BZt4i/D+cz31O50hLCPDk/j7sqWedow5ypBR+nrEIPdWjKg3llzw==,iv:Km4pcqRe+CE7sTB3qB8IKAEnexw7waoOnLkPPeAQRCY=,tag:lHEpqdMnEbvOwwnbys2IOw==,type:str]
    metrics: ENC[AES256_GCM,data:Tg0wDy/h8lkwDWFXagHfBaf66GPNCPVSxqVmKX+iOrY=,iv:o/RZcnKsAaWQAdAF9cA3ur7r3PyC7Fb3gV19cUTMhtI=,tag:bKyAlcddiR5cdHOeBGdVng==,type:str]
    #ENC[AES256_GCM,data:620ILV3ZtnqRYERbJgyWky3nc+KGGp2pYVJjPUCqSA==,iv:MTrRo53qXRWxxHGCvkJHD5yuby/PoxfkImaA3Qc5dEk=,tag:t+ITSMIg2Rf12JC64chnrw==,type:comment]
    metrics-password-file: ENC[AES256_GCM,data:2fOsTEZgFUiWU/5S6aNHKn7lUbwqHvAtCPC7XX7bXV3Og6byf2dzmldzpO8iW5Dgufcn5xBHRE7FxexwX6SB2sx3mZb/zOuDQhOwJ8i2CBtFIXqTnzp8HXGuNQ==,iv:74Aj01DwGJRfamu/KV5j4xkz+BiUzavl04XcuHUpoAs=,tag:UYzmcwqdsT9KlGzgdTLmUQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1ltWXlhVmZTRjJSOWJF
            YWltdnR5SjFOdjRwalZrWW5sZ0hNYWN3RUNFCndLdmdaQ0xRK0xIK2NlSC95VEc3
            aHRyc2RpR21zUElDZWFSa2F3VklvUFEKLS0tIFVsOG5hU0RxbThUQUdtbm9TTE1h
            WUlrMkoyMkx1ejJRbzJMYkJJeVFpU1EKNVV+enLHZmP0vRMwYifqjvahrGGV3jux
            olyzTZXy0HFTvB1tpLItNEwXiLp9BQbwvoKNENud1HwPpiL835dFqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T12:33:09Z"
    mac: ENC[AES256_GCM,data:PctzYdKQinzuYv9lOF1CiwZCBQsbpBd7SkpZJNAiicm0v4QzxRLunNRMNOxOzR1/71O6VfpBtgb+jd0VS5mVe/rVURZ0mjyBrMLOmkRSIsXLJFotL3CpNDU5G7viYzxRAmJXfuU3FQ/5ZX1eQ3c15qnURVG9qOwjgYL9gM2EZwY=,iv:wxYNoAsAjqxG121gHCmylDASckgJUF0YJlEP0wiixz8=,tag:8oet7zNSJaqE0Q5cYK9bjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
