# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: valkey-secrets
    namespace: valkey-system
type: Opaque
stringData:
    default: ENC[AES256_GCM,data:aifrHFoskzd8O3DjK8fqiUA9ji+ew1noyRcCTgrmjak=,iv:vMIYtFe87BZvkl2eDPlx5Yuh1M4AbgHr+EM1FvKEIhM=,tag:Vu138nj2cXR7VhBc7cpy0A==,type:str]
    n8n: ENC[AES256_GCM,data:Fp9zvmrYmVrww+M1n12HVCEYnrBsjWSYXY2I1UcqLz0=,iv:uwrAU/NPWLcxeAFHti9jvpzj1C6gdfZADQCbkTfwEiw=,tag:q4oKMGJyR8wRZzCGESNs3Q==,type:str]
    redisinsight: ENC[AES256_GCM,data:bT5ys2Zb50enUpmIqi1B46hvaU/ZNsZy4029Xx7up78=,iv:YNeAv/7eINTeH5uBxwS0iCgNwHCQVsNP4IB4ZY+WYAw=,tag:mhaVVm9RXtgPfoKZh5w7/w==,type:str]
    authentik: ENC[AES256_GCM,data:AijN3qHIbEA8Wq82x7ZF3bBSnzSMklt0hq95sPz7x8PkDPro6JnbUtrUchnynfLyNqK/+cWVMqNckPiw00faTQ==,iv:PWyiTliztHFf+mweHcn1cfv2dXDfijP4zGaU1hq3VUU=,tag:cHiPXYPnVTf2CvJ/47N0mg==,type:str]
    metrics: ENC[AES256_GCM,data:qFFAwv3KebTIMrawcijrfl5OowkY2llzdw56syV5tpk=,iv:NLiGtdGWycgu5dPqMXfN1EP35GM8bSLD8RXPcLBdDZ0=,tag:apQDxZnD93d7U3vcn0psBA==,type:str]
    #ENC[AES256_GCM,data:rS1ql+PRH3T7MFOdV0HOof5ikkrTtLH6d7Vft1IqPA==,iv:PVLQdsYyEiaD/BciY81skT12yERjLzslUtTZ/UoIKBQ=,tag:DQrMHpo1Lc0zinhgwPAqhQ==,type:comment]
    metrics-password-file: ENC[AES256_GCM,data:37ohr0RRzpzkpaIKcCByVUdweHw08QsLo8MIlxJ2BAu7l/FaNQj7EVT8ThwPJyfGg176aSt5ZmJl6JCt6oelGwxhijt7lw==,iv:GUOIETlkO5oKec7T+JrR0mq8CGFglrR7YQSVidGL7Fs=,tag:IX+rSNecF4mBQy0QyXtuSg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXhwZU5hTFpqR0haVnBD
            T0Z3WUxxRW1Gc0pjSlFNNGwvZDdBcDNlbG5JCjArZDgrQjgyVGpvbVRTSXFPMTdH
            MTJZVDhBZWdjNi9mVHBvR0VHYjI2bDgKLS0tIGxtY1JaOHFRei9Zd0t5WHhXa3RR
            aHhHOVNGVmlaamZKMkc0VlRUWkg5YjQKRmJMGaBf88qOfyp/JgE35WGdYRcOIrhz
            pPN7Xk6i6sthO3jslNreJbd0GRFlRJqLkY8SLXyoyp5h0Ds1LRCkwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:18:02Z"
    mac: ENC[AES256_GCM,data:uBZaHoZXJDSegz+NPay4+nklQphz8+fnWp9W22bRaAZ+mWaAZzOHWKGnbhMrMFi5N74o+XLcW/fDc3CtS3vJXYTI8X01Aner5HsqSjp2SvqzkLVrJQ/H9P0NpNt5GX04hnEhYhGCuvXLobDYrk3Z7nKwwEMJqL+Nxlnpibm/paA=,iv:RbkCrAMlTz68xr4utafNR6iJqueAwmNBGjJ/Lr1NTQI=,tag:WhbyJb39CBnGig6H083ygQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
