# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: valkey-secrets
    namespace: valkey-system
type: Opaque
stringData:
    default: ENC[AES256_GCM,data:Xhjs4wKt9CzxaIv5LYD7vDrVBp1n1uYq98A8Atlspew=,iv:IuBPyqMw729bl1qVKXMgdCi+GA5pOOdR/NKiKrLBONA=,tag:llIdLSG5jPgnrLTo33Wb6g==,type:str]
    n8n: ENC[AES256_GCM,data:7zoZ2c7QgQ9rUNrF4B1Dy6uCZXafYSM7ZWJGPq79ekY=,iv:Hab3IhhRCRfwphGc7GBlIx9HOcFa/FAzk9GBV5DF3dU=,tag:dFNTCuZxDfhqgnj65WG44g==,type:str]
    redisinsight: ENC[AES256_GCM,data:iZwVUOhf9MsgfnRiAAIWTE44QBpbQ0uYRKaZXX+wNuU=,iv:PmPKn7tyP9hqTaQg0mB4cGsn8Bd/NJV3UuJZbY5UzIs=,tag:OqnEs7stFdiimaBTife13g==,type:str]
    authentik: ENC[AES256_GCM,data:VWhguUJtlfGF67D2FpqOdynslisgxrrkaDoWcW3RrSW/KbJ1KtNY8M8023/Iw1SGoh+TbS2a05Ic/4qImY7yUQ==,iv:bLE6MRHLU8dTjj9mhC/8LrjB85tKJt6Lr5V75TQKjWc=,tag:nLnHxmm31uYSqQ1Kthvi6g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVTJYQzBsMTFxQ3FaeTN6
            STBRYW82STczRnpaQ1BEM2ErckZSZ1BxL1NjClZnaVRWZFJMeE9SUVlpTTAzNklU
            T3c1Wm5VZW50RWpPK3VaU2V6M2s3L1kKLS0tIGdGRUZ4ZVF5dUNpWFo5LytnZlMr
            R1IyYjVQWXJCZ3B3UHRtS0owNG9BNjgKf7pezBfQF6xdxbz5dTzpckZANn0lT0fa
            PCtFyVjNqbdU/VUjIe3zShx3Y6/aB5wzBi/LUJuXvz7o2+VKjq8sAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T13:21:04Z"
    mac: ENC[AES256_GCM,data:Dx08ikM/m+BpFppBA0T9a0w8sTYTUKr80zWhhBqUfXk7M1Wyy4R1X4b+LuGOqpgA8gclt15XGy9U2Ny9Du93QkS2zCPsYsdh8/v6nrdVsrheu++0fiablJPHEkcIZyksscm6EDHPJBlYBMonHz1zif2VdhI+wviHbcDdyMfc1UI=,iv:08//g+FAx35LOQZMCUQjrlp2XAiNf4N6SKnX9NJtwUk=,tag:9Vjn7c5mgS5XQHqodUTWxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
