{
 "title": "Ceph - Multi-cluster",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_health_status==0) or vector(0)",
     "legendFormat": "Healthy"
    },
    { "expr": "count(ceph_health_status==1)", "legendFormat": "Warning" },
    { "expr": "count(ceph_health_status==2)", "legendFormat": "Error" }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 2 },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" },
    { "expr": "ceph_mgr_metadata", "legendFormat": "__auto" },
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_cluster_by_class_total_used_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_health_status{cluster=~\"$cluster\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{cluster=~\"$cluster\"}) / sum(ceph_cluster_total_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata{cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster=~\"$cluster\"})",
     "legendFormat": "Apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=~\"$cluster\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "title": "Alert Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cluster=~\"$cluster\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Prediction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predict_linear(avg(increase(ceph_cluster_total_used_bytes{cluster=~\"$Cluster\"}[1d]))[7d:1h],120)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_recovery_ops{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\", cluster=~\"$cluster\"}) OR vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "count(ALERTS{alertstate=\"firing\",severity=\"warning\", cluster=~\"$cluster\"}) OR vector(0)",
       "legendFormat": "Warning"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 19 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\", cluster=~\"$cluster\", }",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Alerts(Grouped)", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 } }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 - Capacity Utilization(%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(5, ceph_cluster_total_used_bytes/ceph_cluster_total_bytes)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Top 5 - Cluster IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(10, sum by (cluster) (rate(ceph_osd_op_w[$__rate_interval]))  \n+ sum by (cluster) (rate(ceph_osd_op_r[$__rate_interval])) )",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Top 10 - Capacity Utilization(%) by Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, ceph_pool_bytes_used{cluster=~\"$cluster\", }/ceph_pool_max_avail{cluster=~\"$cluster\", } * on(pool_id, cluster) group_left(instance, name) ceph_pool_metadata{cluster=~\"$cluster\", })",
       "legendFormat": "{{cluster}} - {{name}}"
      }
     ]
    }
   ]
  }
 ]
}