# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
stringData:
    ZAI_API_KEY: ENC[AES256_GCM,data:bs1saS2PwEcnXYUqf0s4i/DLnA7QauQanfTiSgUjzIsN+sb7Pg/yA26n0TmCT+YRlw==,iv:u14TztaZpJhqZV6hja25qinAKrPtz2u6JWHMlx0JhWM=,tag:UlY8Uyf4p+oUpHyhFRaf2w==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:KroNBTSS6q6bumWxJP+cElV3AfE/E2G1XuJLFgPf0YD1TJQ=,iv:Pnmzi8FJnXta6ox7hOWhhatTtSLVF1k14p24giqg2h4=,tag:+qYM8yr3+54ZRULNzlJfpQ==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:FA32nVFfbFQIZCEG9YF+5A==,iv:ipMY6iD9+oxNQizQWeTeDVHMQVaYEpZeWAXiLav28dU=,tag:nHfS3dz2zzwVl8xWGfyg0g==,type:str]
    #ENC[AES256_GCM,data:hjact94TrdYVhAW5eW56K5DJHVc3R4oH0uw/MLRxNa8L2sle,iv:i3LooSSm8sktX9ft5sQCDscoCl3fCnrNOnK9s3XaXC4=,tag:FqfEeLYaPecXt4nlLlVTww==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XS8sdx0DJ1NR/LWXYaiR1rhyd0M=,iv:YfqVfn4PoqPANzgUudAtSsIk10cpGZXRsrhSccouRac=,tag:8RmgdU1FI+j+jS1bmwL7Bg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gKwYO4EGfMmHVKsnPFxrc53UxT5ZWp42oaU9Gr9ROQKfNJNMSAgktw==,iv:9vtrV11OblKocCrTwa4VaQ6jJ5cvcLLAYZIBnkfm2uY=,tag:b98/M5VsxTbMWEbs+X56lA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN3A0SjlWNWxLbXQ2QXcx
            bjZkckxYbGlOVHU0bDN1bEF2V1FIYWt0K1RrCjFEKzZFSXAxQS9oTDZadFNqOHdY
            Unczc3VVbm5QK09nR01VRlVYTHJmZ3cKLS0tIFpvQVhyUllhb1p2eVRkMnRlUEha
            RXNqQWxtWjUrNWVvaVZxRjFxYlR2YlUKqBDS9cZm17fiRIPqj7l1JrtwvU+K1cO+
            7aBDzM9pZIBXR17CEM5IbIZpk70TX2XCqO4eNCfQXRP8AJursw0rww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T03:57:19Z"
    mac: ENC[AES256_GCM,data:11L7aIk1c6JU38io2dgTad01EDA904lR3ZZN0F/6dnqgwrkbKcQHLuTFT56v5aIamwUKuM3rBGwGPOmLh7CepCJygXtXuRCalkId4eeqkjE+74ZrcK4HkJ2NHetYefHxbKJivC8rWERDqezlTh3Ri6NMSmjuVLnbZZxZzhktxEk=,iv:iPd48iYLLvhq9I9xe7IRS/IOPDCQsg/iY72Suk4dQeY=,tag:lKSJOsstyav6fIlUV1coKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
