# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:sRRrpEVd/4WQSZuXj7Lph4lbtUfai5B2sc2Hs4oEcwzQNlLW,iv:WhXvjpHVSoNn5hY9ByGDLLJbsZs56LQ0uJ4JYhkPPyE=,tag:h/nn1+G2tAab51yf5ZhQIg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YKN22wxPAvAeHseRAA1XzdMTKSc=,iv:OzOr5/vS2cx+v08Y0HEXZx/x/OHk9D4iiJ2xmY2NJq0=,tag:tUSiI5oQcJ/94k6oRJ938Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2QzLrtRuipYsr2piU5uK8Sbu1Diu994D9mt1XzVZZf9/WoYtgW30IA==,iv:l4xMmRAzfIBLjSRi64dGN86QcUPnqDpEn4Z1uuVdXcU=,tag:JKfbAv8pyiy/kX5GbrP+ng==,type:str]
    DASHSCOPE_API_KEY: ENC[AES256_GCM,data:7nSitbchEIuXO2pQGUe8ZuxNqnvo7Nps81m1xK+CeW0FpWwAvPDKgkZLG4Drg1orqUysfn39VQqev6s390/2uHHAZjy02uwIQ1j9tYQu1uIIjS0KqUfpy6VAKnVen5PC3Vlml6yoHwIybtaEQU0kFf9XyNmvVldLbYiXSWbmRgxD9lVfGSr9VIwoOsENeFPywQmftg78qpngtYhLHoP3ANn10I9M/u1USsS7LtoHm7sanrf229Cinm9+SaVaqH1WEldK3F2ag2FPY8iyKrmFltofPUS4vcBfbYEb23ISgM1XjIRNEf/LuMNYc8zcVdIrsFItOLlPTzIrCunjITTaE7sq5Vdkhti605giQZ+f51iJU78HNw==,iv:OnlbQDr/RKERkG35Bnkl+jIz/Iwc4RsmU/JZ+bsF4oc=,tag:3AdTqc53gFZHrne6n9N77Q==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:O0RXysVQWSKvM38TJChQO2t6H8A28bAghtE0RQRRXPBFe3w=,iv:1nVn7mGBZ3LF0uGuFZjST1eIbVLGOd3jluhz8o19YZA=,tag:0aNFVQOb3bTtij2HXzhVtw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:mmDmFgQoL2Sb7/eTf6jrrw==,iv:M2tCJo0LqTU3A1SZ2hg7uLdTL5ig9LvU6QhzXpLTynw=,tag:Aspcx8AKlpLPk3+pODht5g==,type:str]
    ZAI_API_KEY: ENC[AES256_GCM,data:Q/o1dDVLNGbsajEyfzAog2ga6Vn7rosiWe/IynnzLoZ5i8FEeL+2SQIhgVjvXttIrw==,iv:fIjkJ+C2oIP1jBzBo1zwjZUKj98rUzb+GPiBvo70uAc=,tag:kOGk8v+bhn+fABC5D4+Cyg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0ZCTEhjWXpYQllXWHNE
            MWNrR054Y3E1NDVvbDdxcEN3aWJOMnV3VUdRClRLSzE4Qk10by9rUmp0SDdhdk1T
            aXVuUi9WMndpT2F3aWxMVDh4RlpPVGsKLS0tIG1DYUt1Vm9RT09CODgzZ1A1amFr
            M09Icm5qV3N3N2w2Z2xSL2c2cFBMa28KKaxIyNY07OxeRyR8MEPVDi+jXhxsvSZ0
            Vb1uhvYkMdhiPU+bKLsu+Fz+MWU0uf/J1e0u+yPN6APYjS7BhVuFOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T07:42:49Z"
    mac: ENC[AES256_GCM,data:GondRfLcLUSKFL4YqCRRZt2x7QboK632uAQdF7iBh82165xt/OeRTIVZGZC8mYuODeJdTRB6sS8rhRscr27atOfZkni5yxvqz8Df9UsfwhtidzZEvZIH8uj3e/K+Hnofg6HpKlj+eD9O7HCIFQPsCKgPXTGtKSOHQwthu265gcM=,iv:pcA6lWphGA5XQT/SLbyKhY4PqDDUrMb3MEtqVeQJ+Vk=,tag:89UlT0/BvjGIBw1KXjv10Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
