# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:Va7Fr0zoEIU4ifcJPbSvKm86VKwNioA5KkTEkbg6+5XE7M0=,iv:4MLBTWO16FkpWVTZ2vhvfyEpm2fdoGIeGW/oudk++94=,tag:y2ZzlKsAKCVyA1aXuzCI5g==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:un0kAgDV+1qOwOygJAxQ1w==,iv:CaUTBLjgQMa7TJFuP93sYrdn3EfGCBba8UIzvnHDDcY=,tag:vP9r7faj4xLaweag5kGrGw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:AlB3HdhzMyxN6luWpH340054mqUwYIiLjWFsmZ/hJ0KAHqO34Q0T+nmzDKLX7M9eJoDqAi44aYPfUYyO1q3b8XjPiusJywxy96mCNK/hxo/pJriI6UioU33bqucTukA6PWdoXUiPlqmMgtaTfdKONbw/f+SOAN/CDNYgpbx6jRwVO2i0Q6MYOmtJQQWpVoroeWUgn14AkG6okjZR4t5MoA1iwtaux+4=,iv:dDBRUL0qnjnNscy4CD6M5V0i1Hv5po/jtQ7Otc7UqBQ=,tag:YJSPp2mlatN3TjuEUCcRDQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVnFvUFlqZEt5MWhXaTQ5
            STM3d3pCbXJXYUNMdjRsbG1vT25jVVlkc3k4Ci9xTTlsVnZFMk1PdFVvdDFKaXow
            REtZRUg1bzlhTG1rL0xHL1V0MGVkcUUKLS0tIHphSTlLOGhQU2lRZ1c2RStESW8w
            WWNvZzhBMzczZ2dSckpOUytOUGsxY0UK972ws2tosLsF2tHj4Xo4IOBh8uVPEBvl
            NFLA8CjqRkW8bR0AlUDz0qWlstto/SajcK3EpPyO4FY4LoVq4RrxOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T12:29:56Z"
    mac: ENC[AES256_GCM,data:QMptaSX5LqTXyOSdppLX5Fft4srbzBMjIJ5Rg6ZK/qI3blm5bRctxUzEThlRaps8KEXI9+m2xyCerMta7a9/oEM4P4Vl9mBiOFHoFlci2s5vViAb2QVc3Mu1SK4ygNNWJr7+e7HIqGoUo4wCp+9fGNdNDLMRlEm+i+pERoR8M0E=,iv:jQ1dZsebgYZXPVjOZ8utY+Y5yHy2hmbUBe4KRFca9ss=,tag:7mA9ze0y0MOETutj5zyayA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
