---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: nexus-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-fast-delete-ec
  resources:
    requests:
      storage: 100Gi
