# #yaml-language-server: $schema=TODO
# Reloader documentation: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/README.md
# Default values for reloader: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
nameOverride: reloader
fullnameOverride: reloader
reloader:
  deployment:
    # Bursty workload - needs higher limit for occasional spikes
    resources:
      limits:
        cpu: 200m
        memory: 192Mi
      requests:
        cpu: 10m
        memory: 128Mi
