# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-secrets
    namespace: technitium
stringData:
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:xc4t5DgQm+8vlem/FJXBK7vI9L7cnGMkhlKGHTrAkyanx/3ZKf24AVFsMOdLdN0wS2WFfm8Bff9eIomjSDyfJQ==,iv:LGZIKQjSf2gw+Pox3Oxkljto1eWg/EjPEmU+ipSCpF0=,tag:DShDIzko7lJdsIAX7Xt1vA==,type:str]
    TSIG_KEY: ENC[AES256_GCM,data:yW2CIiKhfwNvwBcS/Q==,iv:ADHCHThtiff5ZJP6iWh5GBs9EksSC8pM6a9sqI9tjzs=,tag:TGCJe79+lm6GhZ+SBP2m+g==,type:str]
    TSIG_SECRET: ENC[AES256_GCM,data:DoJzVQpogllAMUk/UGDUGCzuAyr2B12pi68mQAtsEWPS51xv4MfZ6I2M2jk=,iv:au/wIhNlrUh1bOe1nbUa7a8WQHuMiA4+YdcmEXbRFsU=,tag:mPI2boIbKVx9Usp8NeUuHw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYlFGWFVob2swY3lrMUgr
            cWd2eHpIY1U4eFBzL05YODVIUktvMjF3ZWdNClB1d2tMRnp4VzBWS3VkU1JlNTFG
            YUFsRitUUWtWUTF0L21vcmtVdzNFUUkKLS0tIHJCSTA1VnNnQ0xCOWNaQkp5RlVK
            MjVZaE8ydy8xNFl6N2FDajVtZkpVVHMKzRZ83oIHMi/D3CTmdkgH3zT9eGs9Zd0u
            HF9dEjhHkRXaXKY5ZIfiI8DYKSyQcI2K3gAQ5TpXd9xZC3AZdIwWXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:6g8i7mf74L0tbGs/9gzbMHzNVF+MVF2P4ElGt9L8BVNzZuZZqwXSkS7OudpWNhpDnA2XynPxSf+DuoeTyIX9OsN2IiseVI/ly8TKa+6SmmuE7f8XzktJA8v/nMgSW6sG+XyobBzd5XW9vfUYug/hIANumK5uGH3CNcRFWO+mbTg=,iv:ly19lNMmM/Vaa6+0UjFqqZP/+L4v7x9XpFedCp6LfZg=,tag:YOxcoBcr0IRh3G/1BxtiMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-cert-secrets
    namespace: technitium
stringData:
    PFX_PASSWORD: ENC[AES256_GCM,data:zW/muZdnEyioaQfy10qNsmwNyGuZJ1omgO2mNewzQjEzrKhvvaNBpf+RxFcd55224IpjdfN79qqQp/0vArpB+A==,iv:BVMfAMDlBSVtfWP9aIi1Zy6B5VJZ5tJzxaULvhtzkaE=,tag:lx/eBgShjEBLSiJIHZ4H/g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYlFGWFVob2swY3lrMUgr
            cWd2eHpIY1U4eFBzL05YODVIUktvMjF3ZWdNClB1d2tMRnp4VzBWS3VkU1JlNTFG
            YUFsRitUUWtWUTF0L21vcmtVdzNFUUkKLS0tIHJCSTA1VnNnQ0xCOWNaQkp5RlVK
            MjVZaE8ydy8xNFl6N2FDajVtZkpVVHMKzRZ83oIHMi/D3CTmdkgH3zT9eGs9Zd0u
            HF9dEjhHkRXaXKY5ZIfiI8DYKSyQcI2K3gAQ5TpXd9xZC3AZdIwWXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:6g8i7mf74L0tbGs/9gzbMHzNVF+MVF2P4ElGt9L8BVNzZuZZqwXSkS7OudpWNhpDnA2XynPxSf+DuoeTyIX9OsN2IiseVI/ly8TKa+6SmmuE7f8XzktJA8v/nMgSW6sG+XyobBzd5XW9vfUYug/hIANumK5uGH3CNcRFWO+mbTg=,iv:ly19lNMmM/Vaa6+0UjFqqZP/+L4v7x9XpFedCp6LfZg=,tag:YOxcoBcr0IRh3G/1BxtiMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
