# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-bot-credentials
    namespace: github-system
    annotations:
        kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:aftF8RJ8fNwt26qLwFcdhXc=,iv:0F75GB4F1PdBPwiWpgfmMscKGLN6j8WiU8rXQnghVPE=,tag:j2Lz69otcEsY0d+fejJLjA==,type:comment]
    write-access-token: ENC[AES256_GCM,data:Z1W/I90raEUYC3MAP5znAsVfDf3/ZGW/d9M+UQ7qBeRmv7UREkNIZA==,iv:YZ0CBq5FzsDUxZSiPzOAZu6woWNkcReRBiPiNbeXWEw=,tag:02HPeu/5lztO24u8eNUSDA==,type:str]
    write-refresh-token: ENC[AES256_GCM,data:EsMA7Hk442UJIaqO1uY3/VXTl1LJoZjERP/vDH6imuGiB1J1D47ICf/7SH9SQbvgXgxovn5FbcMg92NY2w2ejhFwPbuETaTU/ni3SxzaYog=,iv:MGef3a8nSlTzINZIZ0yWje8By5gkOtDvrjNyd+tnOOU=,tag:vLXhdoGJgu40Jr0ejWAMPQ==,type:str]
    write-hosts.yml: ENC[AES256_GCM,data:RMRRBpUspkDRT/aPqc+4clO7d5cXz3cj84Yi6Apj6ZTXaah4nwMi8q+LUJtcTQMtm5q8R6exPrzl9AIx7iXpyrCOv71j84QDeyUq5jVg/MYJG9zTC/LpGOItE8s=,iv:wiklT0zMVfdAFSa9RJp+oeYa8E0W4ze3FUkOBZHLbIs=,tag:OkyAEMNhQPNzDlt3Lpx6zw==,type:str]
    #ENC[AES256_GCM,data:cNClrOpyHP7Vax54V/Ltmw==,iv:3blZd5LgRyMGDadCr9GjCJztu6qAAuNBwoWBGYR7+sc=,tag:EwuxJrNmYJhrYYFJE0IRMQ==,type:comment]
    read-access-token: ENC[AES256_GCM,data:whpi7ILaDmMDkjDZ2Y7bluvScJ/4ukuj0VbPbXRkO2fBKIP3UEXKTA==,iv:/3oOpXf1YCmW0vOZ1YCbKjH0SoLFPgwJB0g3mjCI9lM=,tag:A4GU4VVSqsBKTquzPlGnPQ==,type:str]
    read-refresh-token: ENC[AES256_GCM,data:13BSb9PaPcd25SxRy/pJovEkXstG7jT+7C3N6Oj1StsOr9YMe2OqDlfZK6/UmUy14CAo1C1XDppGzw14UOttYlPGV1GVvN4zhei/8TFdww4=,iv:zKG33KwBDRcEr545ZewknrYZBIA1rWFipl9IjnJdUC0=,tag:zO3ziMuQzohp41BvBqdM/A==,type:str]
    read-hosts.yml: ENC[AES256_GCM,data:EZrXzGIUHIkUQbWZT0njaBHfWkonQe4AcXmAr0g/yuQw5BfsCMce09LvJklQHHd3riPQuIfHCPg4SvRap+C36Pu7ERFKi1B40Rm/XbscPnyPTv7bzeUY9irZMg==,iv:lnOJza7ZBu3ha5ZcQyl7u6fx5B86Dc+/F0zdpl1EJ00=,tag:7iOyySR2fYGEpXs979CsEA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZENxZTJzQVhSZVB6bkh1
            cGFaaGU5UENPalA3c3lZOTFWYVdVMXM5YUJRClpVVitIVjZ3amxwaHNGdHBJVnhj
            YnorQ29vYTBuUlB4VitURHd6cm5vQjAKLS0tIG4ySHM3aUxTQzQrT0VpbUVHYjBY
            UVdweGY5Q1Y2dVVscDkxbGh3d3lzVnMKSHP2O3uE8x6TGviy04s73sWexpVwrXgS
            sy7XoiCPNvWKJHKvpE3WAaKQjkPqb9QrtHEb3VcQzvp8KI5UMiG//Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T06:12:27Z"
    mac: ENC[AES256_GCM,data:lMKqZFcOGObM/tBqMD06XyFlSA9KttA8VCDcnwUqH7WTFLN0FYIzyLlgcJ+pz7GUTEiRkla1TgSjlQ5JDpHKIGIkBWREe9LVMsannvF3ICo/TkrZEJg4BcnJ5ML33sAdwvKYGxzeVaNHF71vQfrdQDP4Kf1tZAq+h3siX4h5TYM=,iv:f1YT8syMxP80XM6D6OvZyV5PUYQlbXKNmUWixAldO80=,tag:qg3jEDVQxrMSyG9xnyHDOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
