---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflared-secrets.sops.yaml
  - ./release.yaml
configMapGenerator:
  - name: cloudflared-values
    namespace: cloudflare-system
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
