---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/traefik.io/ingressroute_v1alpha1.json
# Documentation: https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/crd/http/ingressroute/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-routes-lan-grafana
  namespace: monitoring
  annotations:
    #kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
    external-dns.alpha.kubernetes.io/hostname: grafana.lan.${EXTERNAL_DOMAIN}
    #external-dns.alpha.kubernetes.io/target: ${LB_IP_TRAEFIK}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.lan.${EXTERNAL_DOMAIN}`) #&& PathPrefix(`/`)
      middlewares:
        - name: compress
      services:
        - name: kvictoria-metrics-k8s-stack-grafana
          namespace: monitoring
          passHostHeader: true
          port: 80
  tls:
    secretName: "wildcard-internal-${EXTERNAL_DOMAIN/./-}-tls"
#---
## yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/traefik.io/ingressroute_v1alpha1.json
## Documentation: https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/crd/http/ingressroute/
#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: ingress-routes-lan-victoria-metrics
#  namespace: monitoring
#  annotations:
#    #kubernetes.io/ingress.class: traefik
#    cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
#    external-dns.alpha.kubernetes.io/hostname: victoria-metrics.lan.${EXTERNAL_DOMAIN}
#    #external-dns.alpha.kubernetes.io/target: ${LB_IP_TRAEFIK}
#spec:
#  entryPoints:
#    - websecure
#  routes:
#    - kind: Rule
#      match: Host(`victoria-metrics.lan.${EXTERNAL_DOMAIN}`) #&& PathPrefix(`/`)
#      middlewares:
#        - name: compress
#      services:
#        - name: vmsingle-victoria-metrics-k8s-stack
#          namespace: monitoring
#          passHostHeader: true
#          port: 8428
#  tls:
#    secretName: "wildcard-internal-${EXTERNAL_DOMAIN/./-}-tls"
#
