---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/ceph.rook.io/cephfilesystem_v1.json
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  namespace: rook-ceph
  name: fs
spec:
  preserveFilesystemOnDelete: false
  metadataPool:
    failureDomain: host
    deviceClass: nvme
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPools:
    - name: fast
      failureDomain: host
      deviceClass: nvme
      replicated:
        size: 3
        requireSafeReplicaSize: true
    # - name: fast-ec
    #   failureDomain: host
    #   deviceClass: nvme
    #   erasureCoded:
    #     dataChunks: 2
    #     codingChunks: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
