# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:dhlSzcToKEs0BECIUpM5vfYbVG3GMb1BFOqHpblclApyU7INCCk19hvMxxtVmeXv/hInWiVCud2pP78U5ApIIEGtJ9WZKnFGq90M7Zx9UpwKIFEo2vkqQCyA+DcRCffENIbyxN1VaN9vOHbGdTKC,iv:RKPnJ+VdCdqwfbqjyN5utEp8OWWP0JZPdCKDT749zbY=,tag:FPp1ZdcjVLDtLpxJQsKmhw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVdVL0tkY0kvMjdSUTdm
            ZjRRL2s5K2hIUFZlTXVMZmJ2aEJEZ3NxZlJZCjdTeFBxKzc5MDRFUkZBWXRqR0U1
            UDdUMzBkK05mVC95VUEra0c4RVZ5ZTAKLS0tIFUrbjdyQWlJRVpEWTRTRjB4UnNq
            clNJTGxwVldUeU90Ym9scG82enk4MmsKIA8xfdoM5HH42xvhwvmjx7ctdo861D1C
            ezLouZEKCfb2eUt/sADF38hs3i9EtQpHfqKCCar0uKnUYIYL4coQng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T14:32:51Z"
    mac: ENC[AES256_GCM,data:drsbQ0tUSlkl0I4F5voC2Chr07xW+XE08aHcrm4nmRw+w7nXrBaC/3/u+Gtod75rxkMfw1taOrZOXuu6C9B49T5BXCKfKR98Fxq4P/W3nFD+BWo3QhKx4zoo10GojDXDXkHQ03yWoy951QovXBwxeE3UqJDN17h2/ahpN9iYJOU=,iv:WzGV2/W5Fj3C42OuCGdaQOzf2HeaaVC/kkrHhcWDT34=,tag:vlJbdl5mwlf7ug0aIHkMFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
