---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/autoscaling.k8s.io/verticalpodautoscaler_v1.json
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: velero
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velero
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: velero
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 512Mi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/autoscaling.k8s.io/verticalpodautoscaler_v1.json
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: node-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: node-agent
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: node-agent
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 256Mi
