---
# Default values: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.2.0/charts/library/common/values.schema.json
controllers:
  mosquitto:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      # annotations:
      #   backup.velero.io/backup-volumes: cache
      securityContext:
        runAsUser: 1883
        runAsGroup: 1883
        runAsNonRoot: true
        fsGroup: 1883
    containers:
      mosquitto:
        image:
          repository: public.ecr.aws/docker/library/eclipse-mosquitto
          tag: 2.0.22-openssl
          pullPolicy: IfNotPresent
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 10m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
service:
  mosquitto:
    controller: mosquitto
    type: LoadBalancer
    annotations:
      metallb.io/loadBalancerIPs: "${LB_IP4_MOSQUITTO}"
    ports:
      mqtt:
        port: 1883
        protocol: TCP
      mqtt-ssl:
        port: 8883
        protocol: TCP
configMaps:
  mosquitto-config:
    data:
      # https://mosquitto.org/man/mosquitto-conf-5.html
      mosquitto.conf: |
        # Configure persistence
        persistence true
        persistence_location /mosquitto/data/
        autosave_interval 60

        # Configure logging
        connection_messages false
        log_dest stdout
        log_dest stderr

        # Configure listeners
        per_listener_settings true

        # mqtt
        listener 1883
        allow_anonymous false
        password_file /mosquitto/config/credentials.txt

        # mqtt-ssl
        listener 8883
        allow_anonymous false
        password_file /mosquitto/config/credentials.txt
        require_certificate false
        certfile /mosquitto/certs/tls.crt
        keyfile /mosquitto/certs/tls.key
persistence:
  mosquitto-config:
    type: configMap
    identifier: mosquitto-config
    advancedMounts:
      mosquitto:
        mosquitto:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true
  mosquitto-data:
    existingClaim: "mosquitto-data"
    advancedMounts:
      mosquitto:
        mosquitto:
          - path: /mosquitto/data
  mosquitto-log:
    type: emptyDir
    advancedMounts:
      mosquitto:
        mosquitto:
          - path: /mosquitto/log
  mosquitto-certs:
    type: secret
    name: mosquitto-internal-spruyt-xyz-tls
    advancedMounts:
      mosquitto:
        mosquitto:
          - path: /mosquitto/certs
  mosquitto-credentials:
    type: secret
    name: mosquitto-secrets
    items:
      - key: credentials.txt
    advancedMounts:
      mosquitto:
        mosquitto:
          - path: /mosquitto/config/credentials.txt
            subPath: credentials.txt
            readOnly: true
