# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secrets
    namespace: mosquitto
type: Opaque
stringData:
    credentials.txt: ENC[AES256_GCM,data:mh/Vl6Ch5d7yPK2+nH6G0W7Vl04o2LRcelQp3z9wFJ/+UcuUXQXLo3OgN/fdPPXNXNe1qMCx2/5qdjrewkqYlKgkUcsFGe6fDJbfAfGY0iXuGTe2mQxwwhsG1SzRPxjL9b78MfWj6AYpFw8C4xRz7LojlzQQFA0Ds5C8kK3jSGGCEJWeb5SE6k76VqodPOzGJYqO6gQqYLvF3ntVaqVdHi9TL7cC7xaACQ7mTjRN4aGPAW24Ipe/Up+m83ykvmIjXiaUEZGeva9Qc7vPRtDIkk66LiR1HC2g3B7oTp8Wl8TeIpBuRUTcvoX8m37QlOSaarY/ivCeBFbqhUXh3DvzwbkHtsKFjbKDzHvKsPw52LQ5jJ0SX67tPjMUBhMT/xzng20BoFObk+Ci9x+4BlaHnr0Bg/Nge8ZM111DZKgQhvtnwjl33eGfCFBZJ6MfS33rKPxUmZVULGUGqCfzJugH3ujTUH21Aq6CcZYinEJLvB2PRoQGO6aLJyocwAMSeU45pFD4q9KAIosh1gXFxFXAiIIL43iwcupqeVyGAWE/TdkMuUQMRzeG6k2zZEauB0UyDJxBWs054A/fIyvwEsio5dsW3KoKWecqqxdsmThcZvXsrCkz5m1cl9+/Q7sek0AOGGywASVxHA==,iv:XJUDM0HFL6v30Q1WNDvL8nsBQvZL65jpg7vQocro08c=,tag:zBk75ylK3b5rmyi67smMlA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTWYrak42WWpuRHhMRXVC
            SGpkSzRScHNHTjlNZE5ENnlXOTM3aW40R1FnCkE4ejhYTHdzcUpGWlpNYk83dVox
            ZUJ3bHdLZ3lxeWZtb0d6Z1BNYTJOSVEKLS0tIGpIM3ZiZWVCL3ZjaEJzem1UeThv
            K09hSWNvSUo1c1BYMjdPRTFPNFJLcUEKxEzbpqxhk8f7fCXQwV/KBOfnMd6RopIM
            KlSd5QVRDSA6cAkHDXQ2G8ildxtNlorxOpcBwkL2E0nuVsdw9RTH5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T06:04:08Z"
    mac: ENC[AES256_GCM,data:YNmF2AbgiZ/l9PRMPhMYJOy+tfahWo3qhWqkMaVCFmfozbwkM/s7gGs2ilZD7QncsEZsHCNpK7OKoiDgBfNmZXPnfqiPaa+m8QCaPoAI+pTg1p+exMODBnQnkaVCTXZVTKyhNJo67qz9/Ook9YAq3IC8xqK1ALP1LQ42DKtk+ig=,iv:hP12q8APjtQfROBPFtn3xapw23T4Mc62BR48yRT6Psk=,tag:6h8uFsB25kLloPidWxOb9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
