# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secrets
    namespace: mosquitto
type: Opaque
stringData:
    credentials.txt: ENC[AES256_GCM,data:c9A9duMTVOQHPUsmh9WwNrVCtJSUQ1Ji9MFXESQwvBG84YA07mKljjzpUV0iol3bntc37by/NH/AmLjJZ8g7NCc0f3rIb1axxrsz4KM1wmsQtVLGXoRyoEaM/5j7WmG3KTz+P7PVCKqx/Ye3aVzjU+azeBOn2SbJYcmmvN+YV7cHefJ3UwcrrQ7tYqEVkKuxZfx1Cba3InFkKllO2BM93+0RnYxEpYe97glOB1rzuPYJFNsIgBVJplF+3RckEP15Rlod7TleGN0cW+eoyntUokBPv2xwY5GM7jKsxBu81784EqoRRkG2ADaQMcSoSqAn1dbPtCV+HtkGqmUb6xnnLBtDnmbkpgvqi2bUCpUQwlov4+c/kLBq87WqzC7etuwfdf3/rslF6YwRiZDpL4WHeEM9TcLgNt2SEnwZF58+c7TguCWUnKSb7k3knPpUjEsNoba/ApyETp5UzZTt1MMRMKTzCwGs8TZe2xDRq4P7iUkJgw3/lwIM59Otvg7D/+KfMa0z3Tv3EmWhV0yOxJa1Rz+TtAad4Ej57F7qIkJWCLEWtOrVgMDRLOZMplUYyu/jLTUxbIgOzhdX/4rxLf2a89s7m0/5q+CQJNU6JMYIjdUUb1ed6reGLNOdFt+IldRS7BQ4RRP7O/MQI5nFGt4qYKvS03l9,iv:/WCdk6PY4ZYVZ+ioXm2R6yEn3SAxds35QMVPUIAkvVM=,tag:V4XUNZPd2cr/QEwAs0+R6w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWm5TLzRVRllMRCtEVTVM
            UTlaYXB2b3Y4QzkrN1RVQTluYjJTS2FKUFdjCkVsQ3k2WmZZZU9Ga2ZaMVFYMzJB
            UmI5YURtV2lWS2s0eHlIL2FBZUNoK2cKLS0tIDBwdEhRSzNnODFQOGtiVWZ3MVox
            MGI0RTdyMHhOcUNrdVV1OStaYWt5YXMKQW5vLfH9+MnZALUsK403pZxc+QPFb+QM
            y6v16NvSy4/jCs4LvQg3peMur+2xe1vb5fLHWA4obMLreuFEoWtggA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T07:28:58Z"
    mac: ENC[AES256_GCM,data:Bj2+j/R3oGkf+2AUDsTJYYQpvkGS6g2DQgdNA3EbDoJg2g5dzrtK0BLXlbyUHRe3s8Q5LgrzAMcKx62viA6NPlzpdesSNOVtF08uYdBV+RXGGGHWFnnlmm1v3j01jHwLQ03Fo7c+xft3L4oHNEwYPL4bx7IiCEB0jQQ8UaYCm2U=,iv:gkIbKEkIWoKJ09rGuWj22l+WUG4Ltq9mgDQAfCyfWNA=,tag:btGOgLRXctfUFoD+sGXKsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
