# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secrets
    namespace: mosquitto
type: Opaque
stringData:
    credentials.txt: ENC[AES256_GCM,data:yQGRN41uxmGwlA79/+o4y50DOM+IOPiH05r6QRcDKoSjWJ83hEX8eMHaEeBu5NHEb6mUCYJimE28cK3JB2CakUq6W/NEmMSlcvjBeqqi2eoXYz8jpnmmKyruOr9RVcsunjmakXb25bbNV49r+vOY7HsFiNRLdF0leQwKtdqmVmIQxeyzLZ0YxJ+xrmlYCfcogFJ0Zo3SaE6HiE3KibjXVQ53fCST20IbW6IfCneGaxvYTMutszwdNju0l9IK9bhEDHH+klam3jKnF8WDSOuuvglkLxZMYP2B0RIAe+3BywklJ6NWiKFDa/fcU5kJqWTZkXNws5gOKyHrtItIQK3zTXr5Q4EW/EZ8wUf58FjrE8qTBz+iExk1SrSV1TY/i7rjctW1UnI/aeoLwI9WurNej85WFGa5kMPXV/TtnBwME5R00EQl3QcXEGstzY4AC4gQQUBoiqfCG7dkfZOqDttSQlnF/Z5GWEPVCJIvbrdLTJac7pvtnNOfOD8846u4vnLPkFXuIIJge3QDIMeJhxkKaq15Zv7bQQXCsXm3gltz26vt+xQrDmpIU6tVTOcuVGgbPHSqQgCDDPT0ZpQyiXPGByl0AhvrOcACWTV0sjMDyKo3D6FQypIeN7McNvC76HqxaigGuCfMAFmYaQLJAY4JVwxPYSHq,iv:zPosx1YXjr6+R0g0BXrQ/KD66+QUk6H1H1cYnoUgG5E=,tag:Lk5BNlDXRjWbh5RNWara+A==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcFQxcnE1SHBVQVM3eEI5
            VkRpVHUyNVMwS2hHMWljWllMNkNHR252Y1RVCjJsWlIrYlZrMFVoUzN6aEMvUW56
            NnpjMmlMMHc2RnZYZTM1QnFGM1FTMEEKLS0tIGRRQ081VW9aMU9MbVd6eTI4UldS
            UEh3MndDN3ZuOU11aDFnMHFiVWt2eUkK16l0LdZIdrnWOQDrM708CJJjOlRB2Y9b
            RHJcOLp/wAo1N4Wi9I+tlw/CVcQk5RzJwf5rpdUUgcyUWF6v9sJFDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T06:12:58Z"
    mac: ENC[AES256_GCM,data:KwsEl+IeF3Znu5rL87VUmRIqxkT7XrukUcqTKpdyE4ZGVIuS6wErNshx2x4oM13gK+WnH7B0sTWjCruQSliTHe8hYrRVSfVBR9FnDk/El3OXBQ4p9BhU6x2Jd4QPdVQYXVLFZ3IOi7PQ1o03IZPXZcuhp0ZTxEt4jw5a4WNcsUE=,iv:ZZZ8v0eOGjtdtL+HWKXilHDyzdQyM/j+GVCGiSYdUSg=,tag:8EP6bRkfFki/GsIDW1cDHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
