---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mosquitto
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast
  volumeName: pvc-2c3f6a6f-319f-497b-94db-8b6da82c283a
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
