---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: kube-system
  annotations:
    io.cilium/lb-ipam-ips: "${LB_IP_KUBEAPI}"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
