---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/traefik.io/ingressroute_v1alpha1.json
# Documentation: https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/crd/http/ingressroute/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-routes-lan
  namespace: rook-ceph
  annotations:
    #kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: ceph.lan.${EXTERNAL_DOMAIN}
    #external-dns.alpha.kubernetes.io/target: ${LB_IP_TRAEFIK}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ceph.lan.${EXTERNAL_DOMAIN}`)
      services:
        - name: rook-ceph-mgr-dashboard
          namespace: rook-ceph
          passHostHeader: true
          port: 8443
  tls:
    secretName: "wildcard-internal-${EXTERNAL_DOMAIN/./-}-tls"
