---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/compress.yaml
  - ./certificates.yaml
  - ./ingress-routes.yaml
patches:
  - target:
      kind: Middleware
      name: compress
    patch: |
      - op: replace
        path: /metadata/namespace
        value: rook-ceph
