---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
# Allow DNS egress to kube-dns for maintenance jobs
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-maintenance-kube-dns-egress
spec:
  endpointSelector:
    matchExpressions:
      - key: batch.kubernetes.io/job-name
        operator: Exists
  egress:
    - toServices:
        - k8sService:
            serviceName: kube-dns
            namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
# Allow kube-api egress for maintenance jobs (kubectl rollout restart)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-maintenance-kube-api-egress
spec:
  endpointSelector:
    matchExpressions:
      - key: batch.kubernetes.io/job-name
        operator: Exists
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
