---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bedrock-connect
  namespace: minecraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs-app-template
    namespace: flux-system
  # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
  # Default values: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    fullnameOverride: *app
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              #repository: nmbgeek/bedrockconnect
              #tag: 1.59
              repository: aspruyt/bedrockconnect
              tag: java17
              pullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            ports:
              - name: bedrock-udp
                containerPort: 19132
                protocol: UDP
            env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Djava.net.preferIPv4Stack=true"
    configMaps:
      config:
        enabled: true
        data:
          custom_servers.json: |-
            [
              {
                "name": "Spruyt fam survival",
                "address": "mc1.lan.spruyt.xyz",
                "port": 19132
              },
              {
                "name": "Spruyt fam creative",
                "address": "mc2.lan.spruyt.xyz",
                "port": 19132
              }
            ]
    service:
      bedrockconnect:
        controller: main
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: "${LB_IP4_BEDROCK_CONNECT}"
          metallb.io/loadBalancerIPsVersion: "3"
        ports:
          bedrock-udp:
            port: 19132
            enabled: true
            protocol: UDP
        externalTrafficPolicy: Cluster
    persistence:
      config:
        enabled: true
        type: configMap
        name: bedrock-connect
        advancedMounts:
          main:
            main:
              - path: /app/custom_servers.json
                readOnly: true
                subPath: custom_servers.json
