---
# yaml-language-server: $schema=https://raw.githubusercontent.com/controlplaneio-fluxcd/charts/main/charts/flux-instance/values.schema.json
# Default values for flux-instance: https://github.com/controlplaneio-fluxcd/charts/blob/main/charts/flux-instance/values.yaml
instance:
  # -- Distribution https://fluxcd.control-plane.io/operator/fluxinstance/#distribution-configuration
  distribution: # @schema required: true
    version: "2.7.2" # @schema required: true
    registry: "ghcr.io/fluxcd" # @schema required: true
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest"
    artifactPullSecret: ""
    imagePullSecret: ""
  # -- Cluster https://fluxcd.control-plane.io/operator/fluxinstance/#cluster-configuration
  cluster: # @schema required: true
    type: kubernetes # @schema enum:[kubernetes,openshift,aws,azure,gcp]
    size: "" # @schema enum:['',small,medium,large]
    domain: "cluster.local"
    networkPolicy: true
    multitenant: false
    tenantDefaultServiceAccount: "default"
  sync:
    interval: 1h
    kind: "GitRepository"
    url: "ssh://git@github.com/anthony-spruyt/spruyt-labs"
    ref: "refs/heads/main"
    path: "./cluster/flux/cluster"
    pullSecret: "flux-gitops-key"
  kustomize:
    patches:
      # SOPS decryption for flux system kustomization
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          kind: Kustomization
          name: flux-system
      # Controller-level SOPS decryption
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --sops-age-secret=sops-age
        target:
          kind: Deployment
          name: kustomize-controller
      # Increase the number of workers and limits
      # Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#increase-the-number-of-workers-and-limits
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|source-controller)
      # Enable in-memory kustomize builds
      # Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-in-memory-kustomize-builds
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=20
          - op: replace
            path: /spec/template/spec/volumes/0
            value:
              name: temp
              emptyDir:
                medium: Memory
        target:
          kind: Deployment
          name: kustomize-controller
      # Enable Helm repositories caching
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-max-size=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-ttl=60m
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-purge-interval=5m
        target:
          kind: Deployment
          name: source-controller
      # Flux near OOM detection for Helm
      # Ref: https://fluxcd.io/flux/installation/configuration/helm-oom-detection/
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=OOMWatch=true
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-memory-threshold=95
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-interval=500ms
        target:
          kind: Deployment
          name: helm-controller
      # Disable chart digest tracking
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=DisableChartDigestTracking=true
        target:
          kind: Deployment
          name: helm-controller
      # Adjust resources and limits
      - patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: 1000m
                      requests:
                        memory: 64Mi
                        cpu: 20m
        target:
          kind: Deployment
          name: helm-controller
      - patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: 1000m
                      requests:
                        memory: 192Mi
                        cpu: 20m
        target:
          kind: Deployment
          name: kustomize-controller
      - patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      limits:
                        memory: 512Mi
                        cpu: 100m
                      requests:
                        memory: 32Mi
                        cpu: 5m
        target:
          kind: Deployment
          name: notification-controller
      - patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: 1000m
                      requests:
                        memory: 40Mi
                        cpu: 5m
        target:
          kind: Deployment
          name: source-controller
