---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana-secrets.sops.yaml
  - ./grafana-oauth-credentials.sops.yaml
  - ./victoria-metrics-k8s-stack-secrets.sops.yaml
  - ./vm-service-scrapes.yaml
  - ./release.yaml
configMapGenerator:
  - name: victoria-metrics-k8s-stack-values
    namespace: observability
    files:
      - values.yaml
  - name: grafana-dashboard-ceph-cluster
    namespace: observability
    files:
      - dashboards/ceph-cluster.json
    options:
      labels:
        grafana_dashboard: "1"
configurations:
  - ./kustomizeconfig.yaml
