# #yaml-language-server: $schema=TODO
# Victoria Metrics k8s Stack Reference -> https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#parameters
# Default values for victoria-metrics-k8s-stack: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml

victoria-metrics-operator:
  enabled: false

vmsingle:
  enabled: true
  # -- Full spec for VMSingle CRD. Allowed values describe [here](https://docs.victoriametrics.com/operator/api#vmsinglespec)
  spec:
    resources:
      limits:
        cpu: 3000m
        memory: 2048Mi
      requests:
        cpu: 200m
        memory: 1664Mi
    # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h. See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
    retentionPeriod: 7d
    replicaCount: 1
    storage:
      storageClassName: "rbd-fast-delete"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi

alertmanager:
  enabled: true
  # -- (object) Full spec for VMAlertmanager CRD. Allowed values described [here](https://docs.victoriametrics.com/operator/api#vmalertmanagerspec)
  spec:
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 32Mi
    # -- (string) If this one defined, it will be used for alertmanager configuration and config parameter will be ignored
    configSecret: victoria-metrics-k8s-stack-secrets

vmalert:
  enabled: true
  # -- (object) Full spec for VMAlert CRD. Allowed values described [here](https://docs.victoriametrics.com/operator/api#vmalertspec)
  spec:
    resources:
      limits:
        cpu: 1000m
        memory: 128Mi
      requests:
        cpu: 30m
        memory: 80Mi

vmagent:
  # -- (object) Full spec for VMAgent CRD. Allowed values described [here](https://docs.victoriametrics.com/operator/api#vmagentspec)
  spec:
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 80m
        memory: 128Mi
    env:
      - name: GOGC
        value: 100
      - name: GOMAXPROCS
        value: 1
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "false"
      promscrape.disableCompression: "true"
      promscrape.maxScrapeSize: "256MB"
    # inlineScrapeConfig: |
    #   - job_name: 'kubernetes-pods'
    #     kubernetes_sd_configs:
    #       - role: pod
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #         action: keep
    #         regex: true
    #       - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    #         action: replace
    #         regex: '([^:]+)(?::\d+)?;(\d+)'
    #         replacement: '${1}:${2}'
    #         target_label: __address__
    #   - job_name: 'kubernetes-endpoints'
    #     scrape_interval: 30s
    #     kubernetes_sd_configs:
    #       - role: endpoints
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    #         action: keep
    #         regex: true
    #       - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    #         action: replace
    #         target_label: __address__
    #         regex: '(.+)(?::\d+);(\d+)'
    #         replacement: '$1:$2'
# -- Grafana dependency chart configuration. For possible values refer [here](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration)
grafana:
  enabled: true
  deploymentStrategy:
    type: Recreate
  podAnnotations:
    reloader.stakater.com/auto: "true"
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  sidecar:
    datasources:
      enabled: true
      initDatasources: true
      label: grafana_datasource
      resource: both
    dashboards:
      enabled: true
  persistence:
    enabled: false
  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource
  admin:
    existingSecret: grafana-secrets
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      root_url: https://grafana.lan.${EXTERNAL_DOMAIN}
    auth:
      signout_redirect_url: https://auth.${EXTERNAL_DOMAIN}/application/o/grafana/end-session/
      oauth_auto_login: false
    auth.generic_oauth:
      name: Authentik
      enabled: true
      client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      scopes: openid profile email groups
      auth_url: https://auth.${EXTERNAL_DOMAIN}/application/o/authorize/
      token_url: http://authentik-server.authentik-system/application/o/token/
      api_url: http://authentik-server.authentik-system/application/o/userinfo/
      role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
      allow_assign_grafana_admin: true
      email_attribute_path: email
      login_attribute_path: preferred_username
      name_attribute_path: name
  extraSecretMounts:
    - name: auth-generic-oauth-secret-mount
      secretName: grafana-oauth-credentials
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true

# -- prometheus-node-exporter dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml)
prometheus-node-exporter:
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi

# -- kube-state-metrics dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml)
kube-state-metrics:
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 96Mi

kubeEtcd:
  enabled: true
  service:
    enabled: true
    port: 2379
    targetPort: 2379
    selector:
      component: kube-controller-manager # instead of using hardcoded IP endpoints,
      # this is a trick borrowed from from https://github.com/siderolabs/talos/discussions/7214#discussioncomment-10255876
      # which only works if/because etcd is deployed on the same nodes where the rest
      # of the api server (notably kube-controller-manager) are deployed. Adjust if that's
      # not how your cluster is set up.
  # -- Spec for VMServiceScrape CRD is [here](https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec)
  vmScrape:
    spec:
      jobLabel: jobLabel
      namespaceSelector:
        matchNames: [kube-system]
      endpoints:
        - port: http-metrics
          scheme: https
          tlsConfig:
            ca:
              secret:
                name: etcd-secrets
                key: ca.crt
            cert:
              secret:
                name: etcd-secrets
                key: server.crt
            keySecret:
              name: etcd-secrets
              key: server.key

kubeScheduler:
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true

kubeControllerManager:
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true
