# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-k8s-stack-secrets
    namespace: observability
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:wwsQeOla+d7/0adp9WGzy6/R+CleDXHCE8KA8cb2fy92+gzZcKYuTFYWQQShM58CeW5+qTsVPS5pR2Ibj++yHdCwR/RnXiZFj+3iyH6X2RYv+nkZa54zpTkJPqPc5iUOMlL/UQot5UwDJee64yngrD5qut5pLzcE0wgcrNzqjOgRo9pXhWwnOVgogFXgSzguIU8IexfacEQ2GWNNxpYO8RYgBvFMOouf8T0ucAHXEtpRqhG/65UwIS1ICHT485fTpfD1Fj/5aazhFXghCzt034EQe09jY0FZpbRoSaGcfX7AgXRYEd9CZ1Y0Xe7f2pbb43ezV+1FzPCwuo1pu3TKhsi0L4tZQlHzvwFpAB9IXhxY2ymIySCvyXFmWZ06GNx8BvIo4Ja95xsvzy+hY6GTluE+CWeFjzVKpTp1HyUzuB9zolKlyeShkSS+GYWLvyL+pi7iZWXV7ou/+R8hDQIyu7SIR/NOog7P51WlvXZ7tXoL/u8pHINT/EhgByc1LwORd1d7TxTnf79H1Yy3oSVFfIuGOgeZxaFZvndtPeiCwFfFDMAcQ1a0ZP6AOqccD6IO6Nw0okZkDVTbI53yvRCyl0PdueBUo1q5/PaqoPXbar6DMWv+sNlWiW2LfMzukqx8K4rnafQoxYsmIaxWORAyQrocBepxX7t03YkxLP0Z/N8NxlWt1pgp7grEYgykPgWRKxJm5TODXeuyUwNMkAhzLNZ5E/hSDWNWW0jNlHjZmdcR05PioDMAfGXNEDY8HSmBBk34ajIMGEewaUggngJVHg9olOeH4Qy78WyYs7zKjFxOW7gFclXLEuCQ7/KPUJT5x/w3K06YOboxJ09Xf1w1Ze5YLMd/YuwfPrN7lvlxb4ccNvVox7novbF0YlXmN/Ch7zEL8IM0jOrs03Nj1NVC1UkSRlrL6GIRzXQMFYkezpLaf36LEKAYbwk8CFuGQZ2/Yba2yDGKXkJALd7fIcIOCgoM4yzEezJBlHOKU1KqMORz0mVI4FWzlgZSqBR1EbQ01hhY8Ehy8j9Flqz6P6t9xymch7ZM/BokFKLc5fbZMaQ86SuzA2pO9ME008SiBfaWkSI=,iv:Lb4MztYl2Tnb4GRVOAL2Db9c2DLUGYB12FXCQY2yLJU=,tag:NsebrvaagmwwlkyTJLXsmg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlpkVUNPMDRQRkFOOWxJ
            K2dsSVF6Z01YWWRneUZMeFNTSkJNaUJ2YkNFCk4yNy9pMm1QOUFWWmQwcjM1c2tQ
            OUZmWjVTSDdScHQ1UEtkbjBxdFMzR2MKLS0tIDRocURJRUNxdi9tbU13eFpnTi9I
            ZC9kdFF2MWExMnZZakdpTXRYcnl4VWMKeq0WwX2Z8MLDJf1qs5qP1Pq9bci/DPXi
            Chx77bdENfHn2Cew6mXGDDm+kQjvYqkxS159uyKyk2rgsCnns2UcPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T10:39:46Z"
    mac: ENC[AES256_GCM,data:wwmcywYDxagrMgzd2vZ5XuXuO+qKdMZLABHHRl2J8cKLwLefzi50WIh68gtfNutH93/BZjLWgY9oAF4H8wq6+NGUD78KQ/90BIBK+lKGlkeRxSJ42U93VzzfWwiULkmJOVcrM0WSKrPD8RII17zbKfuWDiHdp9G8NHH+SEKYk30=,iv:nRxhWLmuGUJByZ6VNMFLgkYsI4k5Ltl1uWZ57Clv36k=,tag:aH8LSiRY2g0viUr5nkdtDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
