---
# #yaml-language-server: $schema=TODO
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hubble-relay
  namespace: observability
  labels:
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      k8s-app: hubble-relay
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: 9966
