---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hubble-metrics
  labels:
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
spec:
  selector:
    matchLabels:
      k8s-app: hubble
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: hubble-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
