# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: storage-encryption-secret
    namespace: rook-ceph
stringData:
    encryptionPassphrase: ENC[AES256_GCM,data:PhfT3E2JiBR/26Evj3j+IrThWKo0K+YaVe/tJHCWKBQCWkTKrNkYUKRErmcqdFI2JeM0qYkZTp8ArXT0FGJ3mQ==,iv:sIvdJcU7ugur5wyUEauPDShsny/82mbYMtgDF3PoUBs=,tag:eV0Aq5jEZqE6ExOwSQnEpQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnFua2pYRlN3MXdtT2Rt
            RDhNNnJvVlpTb2xqQUNxZnRaOWV2R3NLa1ZBClBxWFRvL094NHVaYzFqamQ3aTZz
            SWJ1Mmxyak1DTTduV2hPajY1dDNJTnMKLS0tIHA3UkxLbWlqaXVpOUFhYnYvaDM3
            UHUwZGMrMXgrOStaQ2FEejY2OEgzTDAKAvC6ZjMDdQow2iPQMT/ZPOtqg8HCPDO2
            boMq8k7yH1kGL45MpnFrWce6IpbVh3+x8koiE0Vexx1e83rtSUC2Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:50:41Z"
    mac: ENC[AES256_GCM,data:UxQ9gP9shUaUd/eSPtnsmcARK8haERJyAXl0jeIjQIWXeJPx2uFANlVcfEDoMvDYxNPobcrERjZBNuqNywptV/ywFFbLIMZ9aevxP8B4ao3sLZXaqiQ3UEQwxhfhwemHAAEsWmfw3dPuKuWvHID/K8+WL8gcspcuu/iML2lB5Wo=,iv:zzCe48zzfbWFk/iyggWawmu8yL3odSkYKtOPGa8iPWw=,tag:pm4OwYesQcPrt1tSC4m72A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
