# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: agentmemory-secrets
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:BNFlANfb51dxOxhqlmvPDlvCPjI6BzyQryKcSKTgoT+/05qtWmq4ZHKWu3wxNZ9ctdIEDjY=,iv:DLxk0KRflyv7SJnpWE3FvdwtMbydRMy4Tua6AxjR8Uw=,tag:cmR6wFd6JEfr4Sog7mQUiA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:soenbw+32Ihed1kavlLX0/lreE25Z2Lf6i5/ooj82Z4Et8F7iDzI2fLmiLNJz0dE5ro4LiToK0njGuR7mHevK6jZgvqBGuCUEh1XDR45YWv74hBbEht/7JRekWX+aVquVOMCwc8tLu0YyyDiczXZ2Z8YJmhZT2iBj6rCeG6pMy0Jbn20jPTs3Ut9Ki3W/XOs88+/AG5M9DCzeMh0K2XS1Ah0OzFMzqM=,iv:w7ww7lEz+jnx2Z9dOX/udBQLRGxensNjqO6Fm0SGoxw=,tag:SV842j8Ww81CbOUnqApw2A==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQkN1T1RXSkJaNWxiN2pi
            TnN3MXBYeUNsaVNsNVlZR2wwRms1bkhaeXhVCmZnT00xWjM5YU9qL05yOXI3ZTlt
            NEtuUzV0NVYyOHpvUGVpYWtRV0RKem8KLS0tIHdSWTRwOGN5bDdJSEdmMnlpRWdF
            b1hpUUxISkMxY25Tb2h6Qk1qSjRhWWcKJiIHwigMAF4DU15LWJ3ZE4HqwxkB5MrJ
            YTpc6JMQ4uoVf3n8GojLHhpVS1KCviaEINbZJPwpKwYnW98Gqy6JHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:29:19Z"
    mac: ENC[AES256_GCM,data:+jXZic/TVz1oX6+Kh/n7Z71FV3xYVCTq7DLthAj450auy/eMyJpVu1wnVoQ0DFBanDb/0ePC/cbIyB1l6zWERkVqpcgYIzmCHp2woQRB+QKZAcxOp/c7FsrX9uSQP4CPUXrqDPIvmpmagedgtXpdwmPjmxdDPcHQ2cFsrmnMVxQ=,iv:+Xx/kaxpnOYSYbAX101QT+s702W1B6rQ/ZTRJcblbV8=,tag:Wmr+8uV0xDEn/UacIzorZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
