---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./agentmemory-secrets.sops.yaml
  - ./authentik-outpost-rbac.yaml
  - ./iii-config.yaml
  - ./release.yaml
  - ./network-policies.yaml
  - ./evict-cronjob.yaml
  - ./vpa.yaml
configMapGenerator:
  - name: agentmemory-values
    namespace: agentmemory
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
