---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
# Syncs AWS credentials from cnpg-system
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    name: firefly-iii-secrets
    creationPolicy: Merge
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-secrets
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-secrets
        property: AWS_SECRET_ACCESS_KEY
