# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secrets
    namespace: firefly-iii
stringData:
    #ENC[AES256_GCM,data:qsRh/SvPx3jHzdW9nJEaGj5JjB8+mboJmSEchPNw9EAH0/jmMFicb3bwVJ4JeylxS46fMevEWX+CzZyA,iv:IoU8T7AT1p+GMWOehUY1vawHR7p5KdXe3jaj1trmdOc=,tag:OyXV9eh0E32EY3xG0V6TRQ==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:aru8Hgzg60QoRRdionBQZ8AaBoqfAO5egjfkM0Kivvo=,iv:/u4SXMCjeYXEQua7UO7Pc0LnbLTt7HF0JSq8hJ6KzkQ=,tag:FWru1rtJR7/lvqCVwTDLWQ==,type:str]
    #ENC[AES256_GCM,data:1LWeKdRW1QO8IeMeg3GHA/INuqM9tfG0qXF3ZzmiG6xZO8mqz1CT1L9HtYyMY9M3KO6VIVVTuST5+YXO9Q==,iv:2To0P2XVdjVKw4Qm6CjpY0UVWh5zBJwBDdeaKUJlXgE=,tag:Nx4koOpVEBfLR/GCLDLrXw==,type:comment]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:Zew5JTRH3P4Moj8YAq/8e62VkkJwrSHb0qYQw0rpsTM=,iv:IE019RwKTs0ubdX0i9+pJnU8ykr37Q9shEKkJgPEqno=,tag:v7p2LvT7Y2kRq//9cbDUvw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGI2ZzczR2hYM2U3WHdh
            RXFCTDkweW1uZXF1THFKWm9IVkhaVC83Q0VnCnJXK3hwaXBXc0pyVjk4cWhoSG54
            RkEvUDl6QTdEYnZrenJQU0daZ3JJWHcKLS0tIGdRSFR6R3QxalN5Q1RaYWVlelR1
            VS9VdGZ6N1Y0WkhRUCsxZHVaS1Z2MjQKlReUoXfikNysbTNuRYQ44SM7QqTsb8CK
            r7VVL+Mflm/52OCbr0tgV6eSOnTgSHVbx/h/nV7STpD5OElecirl5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T11:47:23Z"
    mac: ENC[AES256_GCM,data:w3f/IlHPjLGxkIXHAW6YQJfZLlBUrtuvP7+2CcWTnDGZZYlcSlQRVnZ31ONZUJpntDr5ZRdaY48MFgZifduZN7JhM92C4qbpY9pZ+VoPKIJQIWQfUo7OAtoZuYmwXPPzRfQ8aUhbbJ5CWntPYW5dpAVjxU329XbdynuO0X41h6Y=,iv:wpbU0ls0m0ZA9l4O4ixC6nvd6pJKf3Y0YHx57+y8Q8o=,tag:5BwE+EiIB9TkJA6K6hcSWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
