# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secrets
    namespace: firefly-iii
stringData:
    #ENC[AES256_GCM,data:K2/ZBni6yT3eGzZUs7ob7WbYM8OxPTlUJnhsbyDwjTd+cVXi8gS/u+nn2dTQ66ebUHt5pD5T43mSR/rq,iv:DnNVFklBgoJHiVebaEJqpxGZvirkgAgyy7mZL47eRhY=,tag:NKa0a+3WDjp4u6riew8WfQ==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:itYRZv+vuSwBb/BSCB8hfFW3nnsilBtNO5g0g+qVoCg=,iv:ixgGvI17X9GU1ja8bb7ezR4nj7APHLVMcIjMF9jkAI0=,tag:0GjHATC7OHON/PzwDqI0mQ==,type:str]
    #ENC[AES256_GCM,data:ga+MS+B1aqhRiWruhyMmagBRSC2KgG1bh7xp1bejE49hmm9mrs7VC0SwsMaO6MAkVacW1Wyy70LREOlesw==,iv:aXqZknedR0tAfmqnx/mIrNOghYRDJfUt3eMBjzJLRBE=,tag:n+ztvHWCGMcbuLcQLPDIVw==,type:comment]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:4zU9ucyIhmB0DPpf47tc37ySDK4bFJ57oFF164gxDAg=,iv:aab1Lndug+kXyzXHsPLzDpEbIj4/m4AwvHJN+zhxEfQ=,tag:dDjidm85Fi3N18XWdYJ7WQ==,type:str]
    #ENC[AES256_GCM,data:aruMQabInVrWFCSjBa/p8kZ9A+Hxj8NXXTiWUx/cYffXma4fxbWEbg==,iv:3JYfE08ADND/KXzUXAt8hdNJzn5n7WQb5FdTwQE9qlU=,tag:Yi+JCdOzbj+JqHIgRFXlBQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dBcStra2fGn+2IhUzuTxgTHZMs0=,iv:rxFiKzrybO/mA0Ew0ePFjaycTXITcOZ7hLuZRfOq+v8=,tag:jE7Ct5f7ECaDszundhAGSw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O7Wy/e2hFA2lh7Io8RU1rx9nMsn0CdRVII5DeHj5wVzKn49Wo4FMvw==,iv:dt5acYSri48sNu6osUA/gfCIwG5gVH8plYJjysx1iNc=,tag:BFx3zH3rxB+bKQE/ct9EwA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbzJuZ0VuKzRtMk1ZWm9B
            ZzJUT3NvUGxwWGZtc1F3YkJlamVCdEdNa1VFCnRjRkpvcTU0UWc0K1ZDNkF4TG9o
            OVBmUmlSUEJ0QW93dTdOclFWQ3BzSEkKLS0tIEhzTWhlamFxVkJtSldUOXdqQkhC
            djcrZ2JrQ0VSbXRCQWN5RWgwSDBvZW8KNXIimBVtEOaowVFkfEsNRC9P88fCcMY6
            5OA+ASoG3abWD9DgAXmIinnE0Zn9wzdVRoOPD8eVDhdopcM7yNMSIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T02:35:08Z"
    mac: ENC[AES256_GCM,data:QQefPv9hMjyFG5TPUzP8VdpTjU51BcfjRDtODFiXO/F55FVe6wwUBaMCEQs2agSPNFk9h/Poy8BPVqwsuK3zm7Kun5vIlo3Ihe89mph/Ie/EhFF66o2milzN0X1W6mdQjIokS75fjs2FFQuxGRML5ocz2AA90WDmn3LYl+mXtEk=,iv:kgRWPobHMRg9CtNbL37B+TDUDAJnRvVwW1DkeNgAGXI=,tag:SfAMR/sUAFtc9sz8O5D4rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
