# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
type: Opaque
stringData:
    virtual-key: ENC[AES256_GCM,data:Ixt0p34CJbLTSmVnCZHsT/cKOOMTTHopAA==,iv:IRn3k2gWi/rbCHfb0I/zgNGFnJnbDQP+pbehwuDyWBs=,tag:voaHXQh5D10H7HFtHnviBQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUXE1U3BVTTlSR0ZhVGZR
            YVMvc1FQZ0F0ZzJxclM5QXV0aUsyZ2lGbEdRCk0reUs3aXR4RytwTDBzNGU2cWFz
            b3ViYmQ2eHJvWHhrVTYvMWt0YVBXYk0KLS0tIDNpSUhJSGFoSTVqSTQ4MHpPaTZR
            TWFOcHFNdys4enVUaUwyOVJKQWowUDQKtDorRRQ9Rd5dfiNcFJWprX1vgcLq/1JV
            1EYYN6co4LK87g/s2Vljtm2UWxTA7nnUMfTwpPiPFu2ODNnRRwyMUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:40:51Z"
    mac: ENC[AES256_GCM,data:E3iUxYUH9vwFzY5U0D1aIlRlY0NsJg/6uzKadDpN0CyAlUw8f7gfvgINZSCuugEBzb8fQMrHk5Ee5VvZcEOYlobb//ImiNxhHerLi8P6vlTQwafnVFGbWRSS8dY6XXXfgu0LAF7o73P2X3Dcg/mkBerBh4aq3uS/AY5N0D8WoiY=,iv:APSd+co51n+pThQ7sNaJ4uFmIqy+wwxK60wJS29rWmQ=,tag:NX72wpfNLj4kjQqI7ybvOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
