---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph-ocirepo
    namespace: flux-system
  interval: 4h
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-operator-values
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: rook-ceph-operator
            patch: |
              - op: add
                path: /spec/template/spec/automountServiceAccountToken
                value: true
          - target:
              kind: DaemonSet
              name: rook-discover
            patch: |
              - op: add
                path: /spec/template/spec/automountServiceAccountToken
                value: true
