# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord-mcp
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:7xmhR9CK6l2elJeVddF6JNzkrNyahuORTqkg1NQtnuWUyLWA7bFnWn4Rj6oe1PZjpqmvJYqFDcAfoD4q9Bv//pj9lh8v9RK4,iv:6cPPF/DwTGlpkUnXGroW265lWe8/DXLcvswNfaUIW3k=,tag:PPvUwIOTYbMV58kTgvusTg==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:W4qh+tjAWFuAVewhMVfUOgKF,iv:VyaorgrIROk0x6aAqYnP1LSbFFduVLUSWzMk9KLOl9o=,tag:zBcWnmTdlazrbI8Wdp1qmw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTzFBcVR5b2Zjbjk5eXl3
            bXBreFIvazF5aTd4ckNnSnNINnBiTWU3T25BCkFWSFAvTktpc0xHMENXU3FyaDdS
            bnpLcmY0T1JBczc5dmtiZllRdzdCUGMKLS0tIHlIL29weHRxMnd4T3ZTSVIrVUtW
            M0ZsSnFQTFYwTDFiMHZZYVVhcWRwOGsKcKbS/l4/Cn3pWe40UT6v8zN7//ZhfKhW
            rkQ2zeGSniSw8rmalCsbMp2o9aYxGefeg+1JLEYoCf08krDZXb8MDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T07:41:28Z"
    mac: ENC[AES256_GCM,data:G5VOqtS2vmpOYlBSiiFSlAHQAy5q9BZsGZ/MaWvtfAZtyL6f0VM1rT0guz7f8fa/umv4dUkeYFtKCpOxr4hRAjESQFDM82+lxKssqpXlHE01ZUL69AfBE1MBbqwUzGyk1Q8XikPCeaV2TifeQ6n4ggAqp/6S4qt6XN7+nDVGzBk=,iv:jgs4oIgBI24xHGwebgVZ+Jrf/m6krzk7LZ27N9Dz9F8=,tag:mz0eJbYnFipKsMb2W5GafQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
