# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord-mcp
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:M937drX1jysPo6lLFHHXBKAx5C+iUgR7TKVHdmJt5HrZEGbfhZSneAZYD0ki7AC1nJ7DgWGEFzuZUilp+d1YICWjFEfAjRYk,iv:Q+vGv/1SNea6fJCHqR2zCFsYMlANAqYn9/bL0Aubpuk=,tag:ETnPjy1TK2FOaAyYLe2tpg==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:NKKhU4Pm3ZwFfN73LcSiP2mz,iv:7ctnv0+4eCZ3CYXGt7AfVdaSgm+7y14phd+n7YOwybw=,tag:Qz9kOw6kuJODV4iPpfzzKg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ2FOaDNjbHljYzZHZUZC
            YWdwNXArRDU3NnVRQ0d6ZGZqOCtESFl0TGhJCnFNbGRxQ2xxNG1ENXI0dXhya01k
            RUM0NGxRdEJRWUlZUlNKeUlnUVhuNmcKLS0tIG9MblArZElMMzFEVEt4K21Femx3
            bUIvajBqQWYySkQ4SVQzcTRESGpjUUUKEVvLP/FRnX3DaNB2dEOjUaZ7UXqpZ316
            Y+Z4jreVh0W0v+kbh4R4dD1terkVff7QlsP6gcr4jB9ZRp+JRxo/mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T22:34:11Z"
    mac: ENC[AES256_GCM,data:pTATDrERoITaKdlj8ExoD65u1P5nXn212ZiB3tKbXpVB+GxC7jlgSEKlqQliifCG+RSZfjxYTHEzwth+E8/LQ45TbKVP8SP42CCa/IKU+9Ibi2e07O1uqBTRKsEr7B1DrAgDnfws9GHFojStXrL+6FFQg94doj/HW8imz/uRnWo=,iv:20todDGpoIjM73B5rwKmalxcrGhtHJ//KXQsWlOl0Rg=,tag:ngCvXAqG3YlA+m5EQbW6mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
