---
# Default values: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.2.0/charts/library/common/values.schema.json
controllers:
  unifi:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      unifi:
        image:
          repository: ghcr.io/lemker/uosserver
          tag: 0.0.47
          pullPolicy: IfNotPresent
        env:
          - name: UOS_UUID
            valueFrom:
              secretKeyRef:
                name: unifi-secrets
                key: UOS_UUID
        envFrom:
          - configMapRef:
              name: unifi-config
        securityContext:
          privileged: true
        probes:
          liveness:
            enabled: true
            spec:
              httpGet:
                port: 80
                path: /api/ping
              initialDelaySeconds: 10
              periodSeconds: 60
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 3
configMaps:
  unifi-config:
    data:
      UOS_SERVER_VERSION: "4.3.4"
      FIRMWARE_PLATFORM: "linux-x64"
persistence:
  unifi-persistent:
    existingClaim: unifi-persistent
    globalMounts:
      - path: /persistent
  unifi-var-log:
    existingClaim: unifi-var-log
    globalMounts:
      - path: /var/log
  unifi-data:
    existingClaim: unifi-data
    globalMounts:
      - path: /data
  unifi-srv:
    existingClaim: unifi-srv
    globalMounts:
      - path: /srv
  unifi-var-lib-unifi:
    existingClaim: unifi-var-lib-unifi
    globalMounts:
      - path: /var/lib/unifi
  unifi-var-lib-mongodb:
    existingClaim: unifi-var-lib-mongodb
    globalMounts:
      - path: /var/lib/mongodb
  unifi-etc-rabbitmq-ssl:
    existingClaim: unifi-etc-rabbitmq-ssl
    globalMounts:
      - path: /etc/rabbitmq/ssl
service:
  unifi:
    controller: unifi
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.io/loadBalancerIPs: "${LB_IP4_UNIFI}"
      metallb.io/loadBalancerIPsVersion: "3"
    ports:
      webui:
        port: 443
        protocol: TCP
        targetPort: 443
      rtp:
        port: 5005
        protocol: TCP
        targetPort: 5005
      id-hub:
        port: 9543
        protocol: TCP
        targetPort: 9543
      mobile-speedtest:
        port: 6789
        protocol: TCP
        targetPort: 6789
      communication:
        port: 8080
        protocol: TCP
        targetPort: 8080
      network-app:
        port: 8443
        protocol: TCP
        targetPort: 8443
      hotspot-secured:
        port: 8444
        protocol: TCP
        targetPort: 8444
      stun:
        port: 3478
        protocol: UDP
        targetPort: 3478
      syslog:
        port: 5514
        protocol: UDP
        targetPort: 5514
      discovery:
        port: 10003
        protocol: UDP
        targetPort: 10003
      aqmps:
        port: 5671
        protocol: TCP
        targetPort: 5671
      hotspot-redirect-0:
        port: 8880
        protocol: TCP
        targetPort: 8880
      hotspot-redirect-1:
        port: 8881
        protocol: TCP
        targetPort: 8881
      hotspot-redirect-2:
        port: 8882
        protocol: TCP
        targetPort: 8882
