---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-creative-v1
  namespace: minecraft
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast
  volumeName: pvc-63bdfbea-0076-4dcd-85ee-618b82b82d0d
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
