# #yaml-language-server: $schema=TODO
# Victoria Metrics Operator Helm Reference -> https://docs.victoriametrics.com/helm/victoria-metrics-operator/#parameters
# Default values for victoria-metrics-operator: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/values.yaml

crds:
  # -- manages CRD creation. Disables CRD creation only in combination with `crds.plain: false` due to helm dependency conditions limitation
  enabled: true
  # -- check if plain or templated CRDs should be created.
  # with this option set to `false`, all CRDs will be rendered from templates.
  # with this option set to `true`, all CRDs are immutable and require manual upgrade.
  plain: false
  # -- additional CRD annotations, when `.Values.crds.plain: false`
  #annotations: {}
  cleanup:
    # -- Tells helm to clean up all the vm resources under this release's namespace when uninstalling
    enabled: true
  upgrade:
    # -- Enables CRD upgrade job
    enabled: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# -- Configures resource validation
admissionWebhooks:
  # -- Enables custom ca bundle, if you are not using cert-manager. In case of custom ca, you have to create secret - {chart-name}-validation with keys: tls.key, tls.crt, ca.crt
  certManager:
    # -- Enables cert creation and injection by cert-manager.
    enabled: true
