---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: kube-system
  annotations:
    metallb.io/loadBalancerIPs: "${LB_IP4_KUBEAPI}"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - name: https-6443
      port: 6443
      protocol: TCP
      targetPort: 6443
    - name: https-443
      port: 443
      protocol: TCP
      targetPort: 6443
