# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nut-secrets
    namespace: nut-system
stringData:
    ups.conf: ENC[AES256_GCM,data:+9MC0dX/+mCm2AHejq5vPr/6xHAOz/MVxLHIyo0984Lqai9rbB6+W42Ryn026PpsnhB2YC+eZqgs9Qa+ueLXI/6KSJclOYzD9QSp+QrBwvCkDyUHX1SJ27oTALXG,iv:RGC8KYxwkPQVA8nLWDOwIzlGGTRFMqlfk6Bn9NNog24=,tag:FcVctmc+trgCE5WlPq6eEQ==,type:str]
    upsd.conf: ENC[AES256_GCM,data:VL0Q+KULeyHo8nqrjBagnsG3vQxltNNrcmFyQrJ2,iv:is+nG6SgWImxq25+fSUgfJ9Cr0rH6fb+D3oypfj4c8A=,tag:kfTJq8eHGK2/MG1PHIcYTg==,type:str]
    upsd.users: ENC[AES256_GCM,data:BF572c4/Dfq+UlyM5A70odP9fphTztpBRf0XWWIhhnc7WaRIrjam2VF3DRHO1rwB97QKYev2C647mHeVJ/n4rgegaths/LP2iT3BrhLPEXn5WusA+rRSuc9wRbIoua7qd8NOXjS9SsbMw7qWGlV2pB9I/Rz3oLmxYZRvPFNYr7Uwm/ouBi+TCU9mnSgJF3BlQh2hA6lK/JGZb2yjAhIaVAsBfjLBz7uGXmXSaYMXIwSWzLVzb+Bwsuxe4+EElydPyi/MOEOHUljUv9AyaCh+GP96n8DV2Oy7RHVfS80IbpfQp8veoiarTtvURbsD74IbxLgRTlpnkg==,iv:jWZZLKrL4ap9cnnpcwXJZPicRCScgiICEQsm+aj+5Wk=,tag:eLF7OoA8VWh2iQUs2oNUbg==,type:str]
    upsmon.conf: ENC[AES256_GCM,data:fMcsN85KVx8pEC0I6D0119w1k/ydVBSEF1o5+ZNb4uRG32wMNmHY7RXjs2xJXyqiEeKJsTqaEV5QnRv89CWvPWWs+epst63DAb3wlHHftEnEkOVtnx4nFQCRJVBQim/aEMpPqFD7BL+zwII/UCWQuNLfrE8aK1Vfm2PNTRmkpBdF9lfzbP14MwEYX1m1hQJq2f5vSMNP7AFr8LqiJv6Bm/Tek8mfNlXtQ3tOFD3/pqvaXUtTMQe3nE6zPfbTrFUg9hMDv5zuo04ajog=,iv:eJGfs0crQ2ZFz+Uz2DVyoj2VqPnegDzgx/O1vTZrTVE=,tag:XOCT+uGT7LTt69mRccTEDg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybC9VMzlZbXpSSW44YlVR
            aVFta1lBRVd3YnJHTGl0NlYydW9JQmdhWkZVClNGNmxUczRIaTd6SEZrVEFGeXdZ
            T3J5VUkxMUQ4MUQ3VWRTTW9SdUU2a0EKLS0tIDhKL3JYRGFsVmU1UjZidEgzblNn
            L1dxcFNVd3FOWjlTdXJIcXovUHZhR0kKvGLcS6qR0nZp7sfOIWfUKp82ZK0PQdDD
            xsI3/MMa1Iyz9+aDWWSmqzaEmWhfrkpjChExj0j0akaxUEhMaY+TFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:16:07Z"
    mac: ENC[AES256_GCM,data:kHUMbVPL1znAxlfF8YrLsp3gDJ6e6LpRS1FnMiwqGoMalfb1KJMc8sWcgFKzVoSl5MtH7tAITYvwlzS+aYNwUQj8XltJmJVNdPuUcqbmiJf+xz2uKyOaXhT0k8eH5KYYxNLW852/B5kJWXYpqvu1xo6zqEGJ+52RB/qAUVp/tcM=,iv:JayOrVCNYJKjIdkm2kTQ2Y7AMibsRyBj6pMUGrRfVYs=,tag:2NHZmzPxpLOsqVOvb7T4RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
