---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./technitium-secrets.sops.yaml
  - ./certificate.yaml
  - ./persistent-volume-claim.yaml
  - ./release.yaml
  - ./pod-disruption-budget.yaml
configMapGenerator:
  - name: technitium-values
    namespace: technitium
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
