# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-secrets
    namespace: technitium
stringData:
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:tAa5Hm80nXxZxOhVIB8rvFewC/aSZN1UD8g6N5r788aYUOKJ2hp3pcb/1WDpinHrxILZe87pTwGM8CNDkmBZBg==,iv:JfKcFOKVSwVJ7uSIuhE6C7HjFKmQ9qunKyZlC7iB0jE=,tag:yqyZRGEtzLcJUuKmiBLi8g==,type:str]
    TSIG_KEY: ENC[AES256_GCM,data:WLAsbYqAf2njuXkViQ==,iv:5xdRvNs5xnW2x+gb/utep6PP/2nA1K2vA2m3KFP+fkU=,tag:f+I6K//zC2KzMmi+zyWhdQ==,type:str]
    TSIG_SECRET: ENC[AES256_GCM,data:AjOY77cGWKtgls0w0Nxx5ii+DXH2hU0/8J5QAAYjkKrLlgYI9RZFoyk3fn4=,iv:htyHSezZ7Z7y/FT7tzFHJDgN7VwCpBjgMf/CrT/uWAQ=,tag:Ra5Bo5UQo8OWZGcAsC8+mg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aStpWU9rRFdnRkpUMWV2
            WDVLazVSNmhJZ3cxR1VTMFFQVU40STJySTF3Cm9KcW5INms0VFJwMm5TR2trcGR5
            WHVHVDVkYjM3Q3ZUcTc5STF5aDkvTU0KLS0tIGo0eDM5czVxT1ZDbG41blloUStt
            SDFNbVZ4WHV2T2syTms1Vk0xc3dZQncKzmEYO9R2+DM6jPqdh1E3vYaLLs5gP+LF
            XvcjxMqIHEnAtNYR9UuSWQRxb1kmZvyjypGoqrHIDLq6oxgbrmfvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T07:52:54Z"
    mac: ENC[AES256_GCM,data:ZyAc3IC7OfXE0/067m0Wlb2pIvpL+uxxDyWVDgNt38shgqSlwhHsankFGf8uA8cecBbUIaHCZ0+kW9eeDFmjf7RBzvnhXPDVY6ZyB7BOJyW9c59p177yPT+5B8WYxBFwrUE4IcfkaUblsJ67aHQn3CbNrThLKHvqc2ohL4fqYD0=,iv:TvpaJNhPwnkuhMuUgZi8xDBo1hsXnX8UM/65vmonrko=,tag:+uzZk9n/PSzWjfN43ACzIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-cert-secrets
    namespace: technitium
stringData:
    PFX_PASSWORD: ENC[AES256_GCM,data:3RJVGG6SgNxP+r1k5Hz6UBhKGQnv7mbbE9loN21vy/tzYbih84WyfsZtssCegrbw+UqF20fKKBS1BlSUzYmgwA==,iv:WfuBipEvJ1ftYnU1Kvsz6aGKXQDDdNR0MRf46KqgZi4=,tag:IH2V7VCUFPj9msSeHNHxrw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aStpWU9rRFdnRkpUMWV2
            WDVLazVSNmhJZ3cxR1VTMFFQVU40STJySTF3Cm9KcW5INms0VFJwMm5TR2trcGR5
            WHVHVDVkYjM3Q3ZUcTc5STF5aDkvTU0KLS0tIGo0eDM5czVxT1ZDbG41blloUStt
            SDFNbVZ4WHV2T2syTms1Vk0xc3dZQncKzmEYO9R2+DM6jPqdh1E3vYaLLs5gP+LF
            XvcjxMqIHEnAtNYR9UuSWQRxb1kmZvyjypGoqrHIDLq6oxgbrmfvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T07:52:54Z"
    mac: ENC[AES256_GCM,data:ZyAc3IC7OfXE0/067m0Wlb2pIvpL+uxxDyWVDgNt38shgqSlwhHsankFGf8uA8cecBbUIaHCZ0+kW9eeDFmjf7RBzvnhXPDVY6ZyB7BOJyW9c59p177yPT+5B8WYxBFwrUE4IcfkaUblsJ67aHQn3CbNrThLKHvqc2ohL4fqYD0=,iv:TvpaJNhPwnkuhMuUgZi8xDBo1hsXnX8UM/65vmonrko=,tag:+uzZk9n/PSzWjfN43ACzIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
