# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-secrets
    namespace: technitium
stringData:
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:7HEWh8kfDc8MeWYlNtuxNHovMs7mlCbJb0V1K2RcQTWVLb2bsKLqt33uI+x3SbBvSrdw7eNj2W7GHFIHPcIYoA==,iv:e0hmzyOEQMMYpI/Kno5nvHETC76aVjxS/fPi7hu19B0=,tag:nhYUU9F/4fMxGI52bFJzJw==,type:str]
    TSIG_KEY: ENC[AES256_GCM,data:/ICmJTIkul9UIPCmbw==,iv:jaMBwfS9WOM2AyBhTO8n6eRYukD0boOzkYb3JuZiaeo=,tag:i1gOMRK8DjPg/TflrXeIsQ==,type:str]
    TSIG_SECRET: ENC[AES256_GCM,data:Ezu1fStZXUo/A/5onde0/OG5kC4vUJ6Cc4XIU88aXkwUKrVoNL0PQZtT66c=,iv:XoV/U5d7jj4LVFJcLbay5dCf1O9iBpg2YGZU8aNJBIk=,tag:GxRbipIOXwp1HONC4KRzuQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY2lQeGtad3BRM3JtZE1w
            ckRZWm0rbnh3RzlRcWdiNWkrS2swck5qcEh3ClVRc1VZeS9KL08xZUdReEtWeVV0
            UFlwbUEwemFSSWQzK1diL05Gd0FPaFUKLS0tIHNkNG5PNGRXZ1dhSVVwdVdYYWZt
            QkRkSVRsZUlUZkxGd1B2ZDZhNU1OWmMK/9lgjnorVn8E2gY6eddxfSUXOiqaGtvY
            P6VDXvGOkgFXldTYiKGpZdHKAxksR/6f6uZ1eLQvdGp8lcr2cafF3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T05:55:23Z"
    mac: ENC[AES256_GCM,data:XvTiZmT5M/NOXS4YII0CUHhm0/WQKvePzOpCUsOmq+M9ywLbuCLoT0KiyhD59pHLAaQIN26BGMhMvxNk5DuuMFBFvxwpwjYtz7UH/GCszxCWfkH7Udn+PEH5MhSUUsS/8ZruELnPOcQ6dHV0OJV3AfK7vaf0u4/I/LSqCf1GeGQ=,iv:/inJvZJZfrdKF3K9MNl7cOvKMghXvBJoesLVp7UeH+I=,tag:rp0bMAljN576hx2QB6dp/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: technitium-cert-secrets
    namespace: technitium
stringData:
    PFX_PASSWORD: ENC[AES256_GCM,data:A2hS5uMr7OmKGAPYuCpV2sEG7Ke0lkAz1K+cCtaKZZ7GtBkvKKx+o9vzUMkmxmgwEFpe7DvNKOYAkVS9fP0i0w==,iv:wc+K01ljXPyzrEjBScxfExtNNZRap5hRsd7WAWqYy+s=,tag:sDYatZXnyN9jB5tEZUgGaQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY2lQeGtad3BRM3JtZE1w
            ckRZWm0rbnh3RzlRcWdiNWkrS2swck5qcEh3ClVRc1VZeS9KL08xZUdReEtWeVV0
            UFlwbUEwemFSSWQzK1diL05Gd0FPaFUKLS0tIHNkNG5PNGRXZ1dhSVVwdVdYYWZt
            QkRkSVRsZUlUZkxGd1B2ZDZhNU1OWmMK/9lgjnorVn8E2gY6eddxfSUXOiqaGtvY
            P6VDXvGOkgFXldTYiKGpZdHKAxksR/6f6uZ1eLQvdGp8lcr2cafF3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T05:55:23Z"
    mac: ENC[AES256_GCM,data:XvTiZmT5M/NOXS4YII0CUHhm0/WQKvePzOpCUsOmq+M9ywLbuCLoT0KiyhD59pHLAaQIN26BGMhMvxNk5DuuMFBFvxwpwjYtz7UH/GCszxCWfkH7Udn+PEH5MhSUUsS/8ZruELnPOcQ6dHV0OJV3AfK7vaf0u4/I/LSqCf1GeGQ=,iv:/inJvZJZfrdKF3K9MNl7cOvKMghXvBJoesLVp7UeH+I=,tag:rp0bMAljN576hx2QB6dp/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
