# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-credentials
type: Opaque
stringData:
    virtual-key: ENC[AES256_GCM,data:zOTwt+RGj0XMrTGQdVTHoZ9JvuOwpOGKgA==,iv:nrRGMfGHl0QtdudAF/N/ZpGlxXSXvHo57lByXmZ9t4s=,tag:W/WRLmHMMMpSvdu89daVaQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM2VzUUp0bi90QllyM3g4
            d3MzK1hNRVp6VXhOYm0wMnpJc0lHRDFza1dFCkNYOEJkRWl3VmQ4YkRWNkxhUE1u
            NHMwczZDMEZUZC8rTFk3N1hLcmdqYk0KLS0tIGFGWDJybFcrckJVdjV6OGQzd0dD
            dWxCcjlDYlFUbkFSRlJaVjZTaXlxRWcKQBpepeetWZPMRt/LCuHmLmAYfOfBgZ+8
            3DZsNUSqVftAhzuU5/4+43iIHO2PeKPtPzeGD6ozTkyVMvEdRdIf7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T11:40:53Z"
    mac: ENC[AES256_GCM,data:KoODDdP8d8B1UIxiFNYy8e+WedNRwvWWb2T3RjxwCvuozhvxOs2ZITirmD4pJ2nYhEZrJcWfqlc63ByxqX7ugHUoN6LQnZngLVYj038OLIhv5h00U/Jkizavt/6f1ofxIh8FMtfTR+JobnkpXxL/Bc6BgCBpMeknKZBWQqwhdjY=,iv:gZW67pDZXFJVL0ZN7u1eF5Uxb0nGIlmLAqjRQ49CpuE=,tag:QcNtxUY6JMX00g7T5mPqOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
