---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/traefik.io/middleware_v1alpha1.json
# Documentation: https://doc.traefik.io/traefik/middlewares/overview/
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: lan-ip-whitelist
  namespace: placeholder
spec:
  ipAllowList:
    sourceRange:
      - ${LAN_CIDR_IP4}
      - ${LAN_CIDR_IP6}
