---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.48.0"
    digest: sha256:f1df4a9cd26ce506d0b899625104fb488ff4935b1420b5db80de7fbf1c748a54
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
  verify:
    provider: cosign
  secretRef:
    name: ghcr-docker-config
