---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s-labs-app-template.yaml
  - ./rook-ceph-cluster-ocirepo.yaml
  - ./rook-ceph-ocirepo.yaml
  - ./victoria-logs-single-ocirepo.yaml
  - ./victoria-metrics-k8s-stack-ocirepo.yaml
  - ./victoria-metrics-operator-ocirepo.yaml
