---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyverno-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "3.8.0"
    digest: sha256:ae87475ab2efedc133426c77228362e3d47234e76a3f7cfeced552666e6b3292
  url: oci://ghcr.io/kyverno/charts/kyverno
  secretRef:
    name: ghcr-docker-config
