---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyverno-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "3.8.2"
    digest: sha256:2d267f9a36a0cf42efb735f5e984acac8a9f5eabe501f48138825f1cf07efafe
  url: oci://ghcr.io/kyverno/charts/kyverno
  secretRef:
    name: image-pull-secrets
