---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "2.1.0"
    digest: sha256:49b7b6e126afb792683d3fb2e99c92a0c70fdaf9e359cddf5b8db6a54c81119c
  url: oci://8gears.container-registry.com/library/n8n
