---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "2.1.1"
    digest: sha256:ac5e38f96b91bb39539a0e1647d5f390b8aadf6c03f706e61acfd783b03a6217
  url: oci://8gears.container-registry.com/library/n8n
