---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster-ocirepo
  namespace: flux-system
spec:
  ref:
    # https://rook.github.io/docs/rook/v1.18/Upgrade/rook-upgrade/#supported-versions
    tag: v1.20.0
    digest: sha256:9fd9cca67d27d9c17d3ef56e2b8c5d2d2810bcd7d874ec1440eada03382d5ddc
  url: oci://ghcr.io/rook/rook-ceph-cluster
  secretRef:
    name: image-pull-secrets
