---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster-ocirepo
  namespace: flux-system
spec:
  ref:
    # https://rook.github.io/docs/rook/v1.18/Upgrade/rook-upgrade/#supported-versions
    tag: v1.20.1
    digest: sha256:13804d5126727b70f1be40512dbd9b31253569195721a46207f655a5b2917502
  url: oci://ghcr.io/rook/rook-ceph-cluster
  secretRef:
    name: image-pull-secrets
