---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster-ocirepo
  namespace: flux-system
spec:
  ref:
    # https://rook.github.io/docs/rook/v1.18/Upgrade/rook-upgrade/#supported-versions
    tag: v1.18.9
  url: oci://ghcr.io/rook/rook-ceph-cluster
