---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.7.2"
    digest: sha256:24605308daa03e1920b4c1db044f2de6ad241dd6a9ec886d8d643a2682f2ae98
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  secretRef:
    name: image-pull-secrets
