---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vectorize-hindsight-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.7.2"
    digest: sha256:ba87de9ac8b70e1315ad6bcf46496f93d40fc5dbf228b31d89e4b5fec09da46d
  url: oci://ghcr.io/vectorize-io/charts/hindsight
  secretRef:
    name: ghcr-docker-config
