---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vectorize-hindsight-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.8.3"
    digest: sha256:5445452aa193b68c4b94b816cf19a9a0b7357f938a7f100c0b8f8e8f16433fd4
  url: oci://ghcr.io/vectorize-io/charts/hindsight
  secretRef:
    name: image-pull-secrets
