---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.67.2"
    digest: sha256:454e94bbc58a44edf760c69d69d3e2cbc4a355b90b5adda2dcc28069213fb442
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
  secretRef:
    name: image-pull-secrets
