---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-traces-single-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.0.9"
    digest: sha256:78f90a84e64b09cdfbf4f92c0271e2333ae423789348fbe2bc47819fe0c364a1
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-traces-single
  secretRef:
    name: image-pull-secrets
