---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.81.0"
    digest: sha256:b8f7f31f3ee1ce7cb70fa6713c8f58519afe68d15a2cd0b9ed5a4b80c4c1de22
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  secretRef:
    name: image-pull-secrets
