---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-single-ocirepo
  namespace: flux-system
spec:
  ref:
    tag: "0.13.8"
    digest: sha256:d3fecd1a6b536470fe603546599af2827c7b0549b83a9300fab146a229ad985f
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  secretRef:
    name: image-pull-secrets
