# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:eyudxWNOpKXBGqUD/HxcDnXQCnZk2Ebhn4SVXAo87oOyX/2ETVz7qYpVRbI=,iv:M4iPOxEMSZiHdtOPjXzNlNReAxIgyQqf1/cjylyWbOA=,tag:cceF711/uNWEw3SaWuqh8w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYlV1T1lQQmVsTEV2V0Ju
            and0eTduZnZJUjJVODZPWGtLRkpxK09xVVhrCmVFWlJWSFprNW9uOFJEM1JtRjZm
            R09EQ0thZ1VpSk5SYlNoY3VaR25uckEKLS0tIGZhOVc4cXVNaVV5N0NPNTNsUEhh
            S2RjWnNIUlV4ak1pWWZPK2g0RVZVV00KOg7N+0JxIBZSf+p8IysnOaaJKfK1TLON
            F4Kf9Iarkd9c/K/6wcmX06tuwfg3j5b46KxPnm2/N9hhqS/I5WAPHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T10:56:29Z"
    mac: ENC[AES256_GCM,data:G0BB4yfgRhwz0GkjpgW32WSvqLh8T/5CW5QN/2Pwq1T3F63GJi1L2TLjtTv+4R1LVhsDw2Wwgm059JsooAMjOU/ht/B4Di7Kr9gALfQ0j04QwvVvg9xA5fKiiWgaR2PNMHMFjM0s/xWwU1F0tX9CFbWdNOGDvCZyqIWQ7bJHnok=,iv:Mo8SovvULKYN8ahL0koxCGd0Zye/sWdL882Up4VAbaQ=,tag:k3Kw8d37brEqsOUXwrwnLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
