---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-secret-writer
spec:
  template:
    spec:
      automountServiceAccountToken: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - image: bitnami/kubectl:latest@sha256:8affbdae5326dc4d3dab460a0ae70ee6ee47110d8294c5c0d9cdabcf43ca4a8c
          command: ["/bin/sh"]
          args:
            - "-c"
            - >-
              kubectl create secret generic etcd-secrets --save-config
              --dry-run=client --from-file=/system/secrets/etcd/ca.crt
              --from-file=/system/secrets/etcd/server.crt
              --from-file=/system/secrets/etcd/server.key -o yaml | kubectl apply -f
              -
          imagePullPolicy: IfNotPresent
          name: kubectl
          volumeMounts:
            - mountPath: /system/secrets/etcd
              name: etcd-secret
            - mountPath: /tmp
              name: tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 60 # this matches the etcd user in the cluster
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 1Gi
      volumes:
        - name: tmp
          emptyDir: {}
        - hostPath:
            path: /system/secrets/etcd
          name: etcd-secret
      restartPolicy: Never
      serviceAccount: secrets-writer
      serviceAccountName: secrets-writer
  backoffLimit: 3
