---
# #yaml-language-server: $schema=TODO
# https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumLoadBalancerIPPool/v2alpha1@1.17.5
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cillium-ip-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: "${NETWORK_LB_CIDR_IP4_CILIUM}"
