---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      server:
        url: kubernetes.default
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
      auth:
        serviceAccount:
          name: eso-k8s-provider
          namespace: external-secrets
  conditions:
    - namespaces:
        - n8n-system
