# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.3-standalone-strict/secret-v1.json
# Dummy secret for ClusterSecretStore validation.
# ESO requires the ServiceAccount to have read access to at least one secret.
apiVersion: v1
kind: Secret
metadata:
    name: store-validation
    namespace: external-secrets
type: Opaque
stringData:
    dummy: ENC[AES256_GCM,data:VFqIfp2mU35eDQ==,iv:xZ3rkKhR7NeqS68jNYVkVsPVPIrHaKKTorJ7M7j8nu4=,tag:3MTvLu0Tm6uIy+pnEQOJKQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRi9VanVhd3Q3cUxOQnFD
            elhlZFJzOWdLbFpGZ09oZll2M2Jzak5jU0RvCnVvVkdxSVZuNlpVLzUzbldLT01o
            R29lQlJJWldnb3crcmpWem9MNmlYUk0KLS0tIHlZdDdBRmZBYzJvOS9sY3ZjSXlM
            cFdlZzdpd3RLQkFxRWV5ZHFXTEM3encKJldMnu3+M4uYcQyUVj1uKBQI3IgD6/I3
            2iXMsd/o/rdKvNomgdB/d2AItU9+T4xoleN+dzlJJ1YBUO7f0fOdvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T06:47:02Z"
    mac: ENC[AES256_GCM,data:Y/um2CdhXg1LeTBSuJ7AsqdJZe1awCRMIdG4vlYb60hgTIp1+CSrsxdVmMEgIFvEMEfrCt26k/duCy65iJB3SYySvHqFG6y8IuDOI1PTnq2/LKXeMFNpWLLkd1U+eVG3/2sk6YROISSJWudUp1vcGuzP2v5kV7zC0ZQJNwcPphc=,iv:n7bsSmKOBCbPX08KZCbURG3HdmE/NdNgpsntVXPDJl8=,tag:ZwPpjAZXkbhnFomVUYCAtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
