# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: litellm-valkey-secrets
    namespace: litellm
type: Opaque
stringData:
    default: ENC[AES256_GCM,data:0VlOS/5uHQvwNtxQ/3gskS8la5hThKqlymF+0imbjoFMaK8xT2ZVta0So28P6vjA/DLpDja+c0je4NJsW5hv3raKCVg7Aau8va2pbfxVRnFqXet5vxOtu1ZGOjDNKQu1ngsOCnFdMkxZsG048BoQzZ3MM3JfvX+LfJaeIRBEAvE=,iv:3ZxQLUMpOgOA2KkfSm0Zftzj1xjgji280Wxol9lcWGQ=,tag:fjPkNXRQFO0CsHmWDG3n0g==,type:str]
    litellm: ENC[AES256_GCM,data:a0Tj99UiJtuP3H11AGTR7xB0ToHUZfXDDiqKqYxF1RLtdCyuITyKmN2PvFjIA+bkbmzYMILYpSvR6xt4iVG3BXBpntpYxfZSsdKfkcyyBHaDVoumPfO28JYsX0tWtMY+NLdG87BQQFbG2IonL00iLJtrQX6E7yTn6B1SK4giXEc=,iv:g13XECwztiYvdJEo7gu3s30D1BA6+qy7UweGM+iEFEs=,tag:D0l6VGc4DqK9ZM0+TXPOxQ==,type:str]
    redisinsight: ENC[AES256_GCM,data:amDPYu+wWkI8AphPnZ7CAvu/402mgSv344sLQToVD1r8TmTCWy7ffvczF4WFvrYHP9IxglHFl4IwrhUX+DNhApWnHDVSyIcCAdpweobwJrqiuwDyzqQ4k/YY29LWNyaQ59n+LewLYDJJXGYUySf0jsm1Sw2+3hggKiLqFny6mGY=,iv:NUqk5lHJJXly21Zdg6wBQbIvR1nhbavukcorhrkHlSQ=,tag:JXFsaqADCfh6O5maBgiHUw==,type:str]
    metrics: ENC[AES256_GCM,data:P4LPxp0if8BngwSWE3VsF9a658DI8vjGn0MNKIXuqB7/PNy7+5Ux5nE9PxeFwikPzOmB2kh1/FhquuH9KBY3wolqhQuj8oaA0klRXG4Ib8asuUKSJlDqbU6kXXnTjEtOkDe7big6eUHdmvr4fTxL9imPjGFzinejGNaeblrk2z0=,iv:aY++1i+/za+t/XfOm6CF5d2/o6FJStMOJN7V1gAyb3s=,tag:lGbOh4NzQDBLC8LDV+L81w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bUZrQzVlNXQ0cEU1YjRS
            SUNEUXNQQ00rTGRVR0hlNXBZZDhZekxERXlzCk54aFRjQ2U3ZkVaMnJoRHRnQ29u
            YldZSys2ZTFKQzlEdEhaU3YxWW02cVEKLS0tIEdFS2YxUmVlS3NrM3dlb0JucHRs
            QXltengyNG5sYjVWTkJyUEIwZDJTN2cKqC4EFVVZeezdwlMd2gbfJW6cbpD5pmNS
            wZmtKj0BsdIMpLVQWZf50et6qwXg9lHIjx8BaAFGMEUUqgj6slgydw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T12:42:19Z"
    mac: ENC[AES256_GCM,data:WiCIoSH764zRXmhYpKiAlZG9+DDzno8h10IjDeDjw4Q2qEKCiziIYCNBqtksNBf535hzopo2eeB+8Fe/yolu4tmUhlkPDjIJmjrngwQJ8ztBM8gJWV1bcfyPlQdeCjkQV+dqIFbVSAB+F0cQLCEHEiYZL9CIXATanrO+spehJXs=,iv:LB55EgMw8bVRIoJOsQftEzSoJLZFs5sBBH+jkfuJPXU=,tag:sfjignIpKDOzC0Z7nkPc+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
