---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./openclaw-secrets.sops.yaml
  - ./persistent-volume-claim.yaml
  - ./release.yaml
  - ./authentik-outpost-rbac.yaml
  - ./network-policies.yaml
configMapGenerator:
  - name: openclaw-values
    namespace: openclaw
    files:
      - values.yaml
  - name: openclaw-config
    namespace: openclaw
    options:
      disableNameSuffixHash: true
    files:
      - openclaw.json
  - name: openclaw-scripts
    namespace: openclaw
    options:
      disableNameSuffixHash: true
    files:
      - entrypoint.sh
      - init-config.sh
      - init-skills.sh
  - name: openclaw-workspace
    namespace: openclaw
    options:
      disableNameSuffixHash: true
    files:
      - workspace/AGENTS.md
      # - workspace/BOOTSTRAP.md
      - workspace/HEARTBEAT.md
      - workspace/IDENTITY.md
      - workspace/SOUL.md
      - workspace/TOOLS.md
      - workspace/USER.md
configurations:
  - ./kustomizeconfig.yaml
