---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./openclaw-secrets.sops.yaml
  - ./openclaw-workspace-config.sops.yaml
  - ./persistent-volume-claim.yaml
  - ./release.yaml
  - ./authentik-outpost-rbac.yaml
  - ./network-policies.yaml
  - ./vpa.yaml
configMapGenerator:
  - name: openclaw-values
    namespace: openclaw
    files:
      - values.yaml
  - name: openclaw-config
    namespace: openclaw
    options:
      disableNameSuffixHash: true
    files:
      - openclaw.json
  - name: openclaw-scripts
    namespace: openclaw
    options:
      disableNameSuffixHash: true
    files:
      - entrypoint.sh
      - init-config.sh
      - init-skills.sh
      - init-workspace.sh
configurations:
  - ./kustomizeconfig.yaml
