# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:TTqMT85pwcWL2FUHx78aw/+1pLwZj/QTt6zpWwJHtXu1aUfT+RP8RiWazYEkroKD65DgbHdDWefawtrqkXekbg==,iv:moLvq+AiXTfRGzclDL+GGYv+bqGlsRyUmGKjdTnk6nw=,tag:FMErPrr5EV8XWHW0znZs2A==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:XPi+W+p9F3rEU/nbWbgBCA0yiYZsFC3xD7RcPdDxLrZVHc2drg2d6iYQ22TPavHAhZKvDh2NVoefMYO5CMxEWHXCI5VsCbMQxscN77atLDAW90MjEE6OycxYLvqle1Fo+kEx2xKqA+PpDiKYD0AlQF0H8nAL0ICmBN7KvnIaNIyl6A/7wYfd6eSg0yxwzMCykWmLzMhRJdT+MzxYrAwo/mu6ep8=,iv:FnbV3xqUCOdMRGKmCGNi2HFr/rfzut26lrcr5F9dyig=,tag:A+FGkPmmICiemOba/ZhT2Q==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:92YHofZfy0y/unPVH+t1owA4k38pTG59Ya8oct17CNR/nDKJHRgmT7qJWKn01qk7KOChiTcnexPjt2uKJCnpxmdVxKlX119Y,iv:tXoNxtrYLv9qUp11UfPfCpcIc2fTWy+ihZnYTsiybP4=,tag:us3439CJ5j80XCgP0eXkcg==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:TeFr70zCz73vjWEVMuz9T577mCjdEp2/LfrfZmT0fQ==,iv:dEA9khES0RDUqdI02hYazD6OT4ezJ6vRPk86bxVRw+I=,tag:S63AnB40LK/kG4d85xSPAA==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:L1IQ8CmzKQZr92mH3ahXzb47ezOHvBOlPPMGOM/mLdvqSaxR3ZACf/aHGhTMLlb8l9WBK2Vz31y+pc3gnwWHlavvDrAGm2UKRAXM8z7y6Jq+ps3jRbt9K4XBe0H5,iv:gl91KANYpbwbe8xnctIhJOiO+7RAvCTE/aMM++mmRlk=,tag:6qvJ6A4JVskNtw1K4uSvxA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSlZLclFBaldON25sNzFy
            bmNmbnN5bWMvTDNleGVVeStGbHlZZSt1Z1djCnh6YllzRDZrSHdrelRTUm1TaGVP
            NGxGTkRwMU1rdklXWVZDaXNTMUFZbk0KLS0tIEV6VzhBRS9BWUF0NU9OcDNQcG5P
            T2Q5N3BGNkFrcEk4dHdJODNIemJ5bXMKx9eVD8MfRJPaWE3e919Sd6zvLu2LQ/KT
            uQHpdgys/ebZavzmV8Z5zgvrEre1q29Obmtkow38yz+Pd5wvysUFRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T11:52:02Z"
    mac: ENC[AES256_GCM,data:7odqG8Ja9j7u8gmy97ii6b52JV/W10DjLKtBMlpEhonxhAGy/oHV0OR1s1dsXx+DDNWyR1gax20zVw9ZRk3M/BqqiQhG7ZXToajp6nPSnW0mC3Sc5Z81LfFsjmDQsF+Vk3IpJ+HR1F0kaJecmT+jkXcbmsZrhJ3qv2qvKBBjbS4=,iv:69uMm6uG0lBIEvrwp9t+dgRmAr+7nV9I2MasO8hsrG8=,tag:Z2ba3KaD7CicYOe2gnl/Ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
