# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:e9GZGb0fhq8nY31Gj7sLVkv0Xj3gGGNpXpoU8CJEXtKTb7bGvcoSSroL+MpAMdSsG/t2nhr5Qe8Qy//5Eco0yA==,iv:0YY3MRxleg7SOhTkm6w9mj2Z+Tf68bO9uIlc0OCK9tw=,tag:pYziufz35EpkbvWm6U3fhQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:uVtSM1aIjzraucjyOnTKAvh9lJo3S7cssIUOvCFVsRoRnPhJBImUUXx6C36ZUQKmFlWZGhxN5WSIjK3McxJV/Uye5kZhPOtuFHSMN/4eLrmuSpsb4cVKGx+DiM5HEE6/oN26Y1jvaEQxhehOZk7QioZH/iessPUIBeEFiNCeIh0Tw1Idm2rw9lLVHLHqoqs8suuKlXylJUOV338pOG+yHs+4G78=,iv:sPv56un/dsnXG17dwaFD9sTIIleizddprGJv1CJLToc=,tag:XLWrYrigAKsYREv9V0G5+w==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:LEpDuU+yoQtNQwAmRSBDOYOk213Tbx7w89qbScivIBWRjkmzyRokppFyyuuMM98BxYZCX8fIKpuNxQXyYY8GgO2k/YDrBGsc,iv:sEykdxBoE8/hvE1Wk4SKxeufT+r/jhG4RxUk51xah0g=,tag:kXPaKtpD5D18QF21Z9IkPw==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:CVq36I8hO7BLhEzyFifpVQlnWcb9ckJ+782BuceWUQ==,iv:x8SeI1wLhU4CBjZIDByxCfSD7unEWMon06Z/hjj18NU=,tag:6TzL3mQgkt0t53L0fdUZIg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT0NySkNQcTNtZ2dON3Nv
            Z2Vzd05YWklIQkxUbVhQdCtPRzVKUGsvR3dBCkdUbDl1SWYyN3ZXRkxvZzhoeEkv
            L3E2RmdJSkxFaEdrc0VOVkVjSkc5cncKLS0tIDErS2NOL1k2U2FKUE5SYWlZa0o5
            dVN6ejY0N2J2ZGtBWFhZYUtUakJVaTQKkpJArc0o0QhAkMseeFzMjaoR8IPboNRP
            MdA/wT4l5mNvpBvRfnFIHvLvHqoOOXOF00ivOVtGPSfKELpDI56Hyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T10:07:08Z"
    mac: ENC[AES256_GCM,data:hKGKHVOXZnlZmmLLO3Yy7ujdeEGC9hXq/egNeeSiX1xZEyTshU1UQYH6Z1mRb49Ld0xbei6HLks40ziu6N+Z8m6qF1ekVyGIiGBsvDqz6+Ef7TLk5NmOmzXwYt5W4OEITUsjDSqkz7SgET3rshxcJg3wwDWL5Io52B8fasbV9GU=,iv:wURo7HBdP27wIFR/8N4r5JUXuXoshkFvaOwJLDj7nHw=,tag:Ph84JanBNnDVWBnoZ1FCBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
