# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:O9WC+W65114ZRtvu3MpmzToEw3FxbOwno7Ro4CV0IrEok0mjn2CvTFxtiUKrbuERs3Nyw+ZAqbsCsNmf6dbSIw==,iv:BL2UZpU0ZZ1pfnc1QEDdohHXdxrktx81ROXyMQotOwo=,tag:sUR0heIsqX7H1/wn9mB91g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:BLD/ksH086m6bUrhBwfdQcDSZ/AWssNq9BKY+tNs8yh3+EGLUJ1Jquk5g67zCdY1M4V3LZBIq2g5MRhKerCbyHpJFYqU0NmZTHtXmow0iaq2agL7eSz6YDBmXxhDItluQ4nPczPH2z27dP34cVpcjbo/zwAni/D10RpwPz7J2rD2BZMrq1TDbmUPrRRkfLow8T+fp0rfyjAlZzRS565Z81VJCV0=,iv:9BJ9Ne/aeS57pqbhlEUZu6SVH1XAXa1ObCLLlDGhMro=,tag:7eCtIAcx9xkfpFmXc3dn9g==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:mTBRY4NMINAvfvAsrJ55UpYpefa18J0BODBrhMm3jgizrdP6W8y8mYNR9EBkFXrpBl88vq1QWEE18CC5caU3xDB9JqwFN7OT,iv:SUH5+vaIQ7zMVOaw8Kcu6wgQQgYhh3d47goWZdQzQJQ=,tag:ruNyMUa0RaNF03gctV+bzg==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:JRrqK2PMZnnOicwWNsfG+LHcaZWhvjVB+xI7dZaoLg==,iv:77xfkCL/rlJHeRn82LPvtcEAqFq7QQqsCLlTEJQc8IY=,tag:1dGxEXu4DzKV1/TQqPL76Q==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:KrlFLhXPVhxYksb2/ABw9nVAhMJayoqK0vTwAAK80gVlxU9tuyo1KTl6f8jbOxCuddu3vZxXHn5ak0OxtTdP8bpWZCVW1APTLNtnBocCae7kkIFJE70CJ0+pUMpV,iv:0M6vxBth7egVsWAz23SbE6F+po9Hjank6WTcrjZuULQ=,tag:yQ3Zhn83FR6vUK9RfZPtYQ==,type:str]
    HASS_ACCESS_TOKEN: ENC[AES256_GCM,data:MWeLFEuAcHMkm2zjRpnMnXollzT8PgZrF+UceLffWDq5ZipRLrsl9PQKkFBYreqYdxCB6vPTSaSAJtC2KW7eR2eAtE4DOt4EqEFwczf9ExTqXXSSY/Sxtr3fSbjMxeduPZgG1SeRwv3FxrjXI4yKJUm0Ru1BB75yPi53fekCmZV3yxWgJgIUuFnA7jE8qpL08GmmpLsDRGNIZLf0Y54ukQD+4CE820+Fd8IH3Vm6GfP2Xkg3P9p0,iv:VOAUpbK3PtXLuOO8JWDzdivWgLys8g9sRbnbyjDRzFE=,tag:/zU0aQALPxIMowlPrcEBnw==,type:str]
    HASS_BASE_URL: ENC[AES256_GCM,data:z54EbxyCrYCVVPnCxTEGh9ENl2bXMZLz,iv:VUq1QQcSEaybDB0ncg269S9UuUTOXSQhYw2NqavHPpM=,tag:k44EP5R3E74zpeXHvoJ9uQ==,type:str]
    N8N_URL: ENC[AES256_GCM,data:92SH7Crq/1X7HGSbXWgZj2cnpDbTEwZbCHaBVy0aonlh02A13pBdlLy6AYizvSziE719A32G4t3CylyPuCbt,iv:Ka7aRvy/X/PsKXtsmiY0d1dXbT/84fu2fVYW/qMYHCw=,tag:KUnJvMA6XjuXj0Mx245ljw==,type:str]
    N8N_TOKEN: ENC[AES256_GCM,data:e5lyb1P8peOQV6fpNr3sQI2PQ9LAWExQipN7G+f8rQFG5WRrlAdqieO5H1TZUNmt50kNX2Qs6TBaHP+dbrCbbw==,iv:dV8gVcMumdSnpd0vfLl6AabbW/UYnoukzuS/qW3TbwQ=,tag:5ZCQQIgbsRsdIOONRHFSFA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcmxDYWpuWnZsWG1aODBD
            NjNBNzAwOGpGQnU3dVdMOWZMQkh6VS9PblZzCnlCSGErYXNLcDRMTzhlc2dhZGQw
            RHVlMzlxaklLNG4zQUVEdDZSK0t2M3cKLS0tIGpVUTVyRmxzUy9iWGQ3Sk9lZFQ3
            L290MmhGVFNSc1JKTlcyV3ExQ0VRcXMK+ab6ZxSfJR51VZ85Piua896zob4UOgHW
            NSF3H32zInZDAFxyzl0HB0FIDIxUff/qL2qa+VhD/OOt5/UtLHmRPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T10:03:18Z"
    mac: ENC[AES256_GCM,data:mLvHVxFvPKAxh7zK5pjgQ5lgWC86XLPHu1bfuIfH4y2OiqR6LGg8qp9+1yS3R7jUxoKdnxNkoX5mUD+qQ065ViF0b8O+AEIS0Op9vVFzLg0ZYBu1a7owWm3pWpVFd+Wg48W6q2hmglAvaLHgQdBAFstGhErs3qvS/EDA9PfgKzY=,iv:lVp7llGtfKtmEOI8+/9sJYhO70AeX48Iq4LtdxQplZY=,tag:npMsy9RYccB/Cezmg+nRuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
