---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/autoscaling.k8s.io/verticalpodautoscaler_v1.json
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: openclaw
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openclaw
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: main
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          cpu: 2000m
          memory: 4Gi
      - containerName: chromium
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          cpu: 1000m
          memory: 1Gi
