---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: technitium-secondary
  namespace: technitium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs-app-template
    namespace: flux-system
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      strategy: rollback
      retries: 10
  valuesFrom:
    - kind: ConfigMap
      name: technitium-secondary-values
