---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-secondary
  namespace: technitium
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast
  volumeName: pvc-0f7df522-b93a-4ff7-aab5-6afb33932e09
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
