---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-system
  - ./firefly-iii
  - ./flux-system
  - ./foundryvtt
  - ./headlamp-system
  - ./kube-system
  - ./minecraft
  - ./n8n-system
  - ./observability
  - ./openclaw
  - ./qdrant-system
  - ./redisinsight
  - ./rook-ceph
  - ./vaultwarden
  - ./kubectl-mcp
  - ./whoami
