---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./zerossl-eab-secret.sops.yaml
  - ./solver-secrets.sops.yaml
  - ./release.yaml
  - ./cluster-issuers.yaml
configMapGenerator:
  - name: cert-manager-values
    namespace: cert-manager
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
