# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: solver-secrets
    namespace: cert-manager
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:0CCRSoYZ8wU57/mBErKkt0DAPJBuqMeJWbTNSDFEas+8CuOeH5EtOQ==,iv:Btm9wy9PsY0s4v4eCCYR81J6EpzthfdLlwXUasxLYbE=,tag:XdqopEh5Sclejqboy9Ij4w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eUhYTWErdnVtVWpRcWJi
            V3pJVlVBSXV2WGVBSFNmcnhtQUhXbGtoK1VjCjlxVkNWTmxvVll4SW40NHZiRUx1
            OUtONGtxYjhMWEY2eWVQNHRGSlp4MEEKLS0tIGh5ZmMwTjdRQTR1WGVaQmVvd2M1
            RG01QkRjU3dFWU1zbGJUSFRSMDlBeUUK5PkqKba4A06P7DufcaYH30NP7Cmt/sRo
            G25Zv3GRrjQo8MUAy6uKnCkOefWJlSZgNX3CCTEpcCogC2kVOdFEOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T12:10:44Z"
    mac: ENC[AES256_GCM,data:n+WUQv4FzwNFI5XvWL8lDLncEbVKT/38mYtaUvC30hIyuzJaycjEUdQZo+ukYBxAU6k/ECCErLtkHQGhbuy4HPavIcdtv4yyPHzMJ/8yNnGKb4WPBg2hsWCiUH5T6o2CDy5HNVtqxVILdC0n9q0rkJ+6AaXpgwuUDckTLGTW3KI=,iv:6193HaMqf0ZLay6z/SGh0+Vv+8GBz9CdgkXCefc2QDQ=,tag:nwozxs31Yh7VrvejqHbNSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
