---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/deploy/charts/cert-manager/values.schema.json
# Default values: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
crds:
  enabled: true
enableCertificateOwnerRef: true # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted.
# A comma-separated string with the host and port of the recursive nameservers cert-manager should query.
dns01RecursiveNameservers: 1.1.1.1:53,1.0.0.1:53
# Forces cert-manager to use only the recursive nameservers for verification.
# Enabling this option could cause the DNS01 self check to take longer owing to caching performed by the recursive nameservers.
dns01RecursiveNameserversOnly: true
# For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
resources:
  limits:
    cpu: 20m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

replicaCount: 2
webhook:
  # For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
  resources:
    limits:
      cpu: 20m
      memory: 192Mi
    requests:
      cpu: 10m
      memory: 96Mi

  replicaCount: 2
  podDisruptionBudget:
    enabled: true
cainjector:
  # For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
  resources:
    limits:
      cpu: 50m
      memory: 192Mi
    requests:
      cpu: 10m
      memory: 64Mi

  replicaCount: 2
  podDisruptionBudget:
    enabled: true
