# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zerossl-eab-secret
    namespace: cert-manager
data:
    EAB_HMAC_Key: ENC[AES256_GCM,data:fxST09C9SZ3KbhttcG074mntXg3BIQI3KVYbYfIguNpS7Oba2/rGWunlJlmGfEw6stOOeOKd59A85EzJdqdR+LXWdEjdXooo/9013jx3VsbmGXdRPUhYMaqMfTT1tLIp1CNvjHTNaD1VMctnZZlznVGuBtg=,iv:f52LdCB/GbKknHcmLlp0xbRqdmFyZrirGig4wEHVGvE=,tag:UBI0C+HfMVpWAEd09lcnbg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjU5dE1tbHlWNllxMS80
            MlB2aGxRb0VUL29MY1hBMzJrbkdweE5uREFZCmRiSkFXK24yNVJGMStpRmxsK01a
            d1orTU5xbTE3UHlKeGN4Y2YxQlN4RjAKLS0tIEhIOE4zRjl3SUtiRU5tbW05RnNn
            MFl0YWRnNHJiNkZubTdTcnpDeWx6dlEKJSScYQNlPU85uhgQClV3VKflUfDAm70B
            9rx4wQgNQ/09+U+A8uCeeKEaUI9usnvp3IZHMLaVgH3TQJkq4/R8xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:50:40Z"
    mac: ENC[AES256_GCM,data:sVnoZIZABxY4HzvHXoXqDgfPJqwU1rmB+qsjL1e10FT8UK6cx44IqqodATDR8Etv+/DClYiSgG/2yguV9mx9j4DKL56mudPAmnw/2TNUyh97e2fMmCOKD+UfuiH27KLuG4ygBsGz5x2t0fxXomOoiAulzPHYRA1VsZ5rrg71JSM=,iv:SV6JJopp9JLxJQxbtBTedMZN7szsCAoGx92a5B+eji4=,tag:v9Kov/D/rpHu8UhZCix53g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
