---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app coder
  namespace: flux-system
spec:
  targetNamespace: coder-system
  path: ./cluster/apps/coder-system/coder/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cnpg-operator
    - name: plugin-barman-cloud
    - name: external-secrets
    - name: authentik
  prune: true
  timeout: 5m
  wait: true
