---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./victoria-metrics-secret-writer/ks.yaml
  - ./victoria-metrics-operator/ks.yaml
  - ./victoria-metrics-k8s-stack/ks.yaml
  - ./victoria-logs-single/ks.yaml
