---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast
  volumeName: pvc-63c9a9a0-fe7d-43a0-9da5-fd6114163c8b
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-backups
  namespace: vaultwarden
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast
  volumeName: pvc-4444b3d9-2bfe-4dc1-a010-e614601d9332
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
