---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
  # finalizers:
  #   - kubernetes.io/pvc-protection
  annotations:
    reclaimspace.csiaddons.openshift.io/schedule: "0 19 * * *" # At 05:00 daily Melbourne (UTC+10)
spec:
  storageClassName: rbd-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.3/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-v2
  namespace: vaultwarden
  # finalizers:
  #   - kubernetes.io/pvc-protection
  annotations:
    reclaimspace.csiaddons.openshift.io/schedule: "0 19 * * *" # At 05:00 daily Melbourne (UTC+10)
spec:
  storageClassName: rbd-fast-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
