---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/persistentvolumeclaim.json
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-v2
  labels:
    velero.io/backup-volumes: "true"
  # finalizers:
  #   - kubernetes.io/pvc-protection
spec:
  storageClassName: rbd-fast-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
