---
# Default values: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
defaultPodOptions:
  priorityClassName: high-priority
controllers:
  main:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
    containers:
      main:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        image:
          repository: vaultwarden/server
          tag: 1.37.4-alpine@sha256:19ea2b669945d842dadc3d500f2d6a795866a003330f59a47b9634658bae98bb
        env:
          TZ: ${TIMEZONE}
          DOMAIN: https://vaultwarden.${EXTERNAL_DOMAIN}
          PUSH_ENABLED: "true"
          SIGNUPS_ALLOWED: "false"
          SIGNUPS_VERIFY: "true"
          EMAIL_CHANGE_ALLOWED: "false"
          ORG_EVENTS_ENABLED: "true"
          EVENTS_DAYS_RETAIN: "365"
          TRASH_AUTO_DELETE_DAYS: "30"
          SSO_ENABLED: "true"
          SSO_ONLY: "true"
          SSO_SIGNUPS_MATCH_EMAIL: "true"
          SSO_SCOPES: openid email profile offline_access
          SSO_AUTHORITY: https://auth.${EXTERNAL_DOMAIN}/application/o/vaultwarden/
          IP_HEADER: X-Forwarded-For
          IP_HEADER_TRUSTED_PROXIES: ${CLUSTER_POD_CIDR_IP4}
        envFrom:
          - secretRef:
              name: vaultwarden-secrets
          - secretRef:
              name: vaultwarden-oauth-credentials
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /alive
                port: &port 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 2Gi
service:
  vaultwarden:
    controller: main
    ports:
      http:
        port: *port
persistence:
  data:
    existingClaim: vaultwarden-data-v2
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
