# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
stringData:
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:+FjBXdeLaePNzaBiHTChommlSU/b6V7FsdwHOUen6T6fixqe,iv:ARv+WFB6sWQePtYyEMecgfB1jUsr5RgFl9YI0BAuyy8=,tag:J6QLzIumdgLZaMZ2j1AjHA==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:2rUJRGFlLOYDSVFTc7Y0dqDkxNk=,iv:8cEqGwF3yyZT9uQdhMbGY1W3/KTfl43656Pu0AKuEJg=,tag:nfjKNS6mVyeck+g20K8M7w==,type:str]
    ORG_CREATION_USERS: ENC[AES256_GCM,data:2g1K8fLlSV1u4dI5Myw0iMkdgaMW,iv:osbo1ruxtFs49Lu1H4R564z2ag9vCcM72PF6lBSib9k=,tag:pFV6pDmv1jYHXv6MThvuHA==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:tNL6Pw+ZPG45hzApJuAvHfoJwQA1sSsIqpg8Cjj/vQzFbYbdiPKY3VTHr+WZZC/MdpP9C+b59HTnwo5Iptkf096yvwfqfcPoyWAadOSyuTj2xSMPXSMELd2sHyuuzff8aHCrJ5F8NSIOrJ1LNjYBRlkZIaninA==,iv:eNTccIXML44LDwB3oJx0R5tLQmE7dmf85qZxWFwFcw0=,tag:1nkz+opVMwtfMGO7XcB6pA==,type:str]
    DUO_IKEY: ENC[AES256_GCM,data:OrmwSjBKOgogL5CTIaYXL9ZTC2g=,iv:PDVI1JT4uhaUOHkmh4ZnM20ZAz8aHdVh+Zy/CfQkk6o=,tag:DQHth1Ql0jtBuTZjees4CQ==,type:str]
    DUO_SKEY: ENC[AES256_GCM,data:NMGXhmMQ515BXQ/BrdVDANfGFfVY8MeG8qp1tk2nmow83aSh+FN9Ig==,iv:zc8X1OuxecOhACMhV6E0bRlBC8ulYaEbLNBj8kIer9s=,tag:1FF1TTGBHDLAQpwNQYp/4A==,type:str]
    DUO_HOST: ENC[AES256_GCM,data:AnutaCoHZohkz/u7murmIDA7jL6DwvRKdL6Gyg==,iv:mDjRKRzGL9BmTRWz/gJWGyyQysSe5W0ZHHyNFhqSvdY=,tag:UUSA9Ks+s/m6sFFlDp7UeQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:Oll4GgBPMzE+AougWdsGVIyHvc8=,iv:2EbM2ak2UMD0T2/iFHGM8ih42Zkm4oOAVD7W5x8fNeQ=,tag:XSV0d7R3pQ7PPvIckkqhLw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:pv33tvbXjIsJqAdcRVb8s4houWra/BYihndn7Cym,iv:4g+IpK89wLl7E636Gfb11zsWoomsbnrOztyXJDy4udQ=,tag:BOwZCZzhf1Iu62cl1Rd5IQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:Mga3hysf6YEzmWmQ/VBLs1EqCRhGtB2Q,iv:5oc7sBJp8aSUhIummsK2cKnNX3c6FQsviGRJXncNUpI=,tag:A5FqdbeDyJlEUhZq8YBhLg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:+Rx6xsCVFOaZmzdNYOmAXA==,iv:U7baQE+MFcoel7pYJnrSqr2H4z4goDIXvZHxZRaal90=,tag:wE9/vWycm39rYuBXNvufjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVVpDcStzZVM4dHZIZkRp
            ZEk2VUlnZ3ZIOGlVM0w4cTNiWFI4L1llK2c0CnNtOGYzNFNNdmRHMTJEYkJncGkz
            MWxOdmpjaEhCSkVJNThuT0FtRC9ubGcKLS0tIGU2VDE0VjRSem9xZTVSeTVucXM5
            R2RGY24zU3NQTmM1a0psN3pmeGZQRjgKggHBgGGc0BFawaDDH3xYcC+BcL4ObSna
            qjjA8CrFle4DX6uR5khfEanlE5mYHiZ3LTlXQgGQOrzoDHPzR5Qjyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T08:50:24Z"
    mac: ENC[AES256_GCM,data:MnyW7cRfI8ojKZmwP9qqLMcXn84Webeq1fmZS8wRbHVoMGCM2JF4i0WxpXW/SOyNl6+UUpWed6fVRBNoc3T7P0AGuCAdZNpz5FNZA6X/oYBz/jHNsL7gsNDbxDTsaJI1q9xx6AAbWF+aBuGs9ZP5xpOHQcU7wlaGyokv6h0tm0Y=,iv:UMgffLydSWREhqZ4u7LTCBq1ZyzZPgKuR7p4Wu1Es+M=,tag:B1YTfcLHHEnMQkF9fYEF5g==,type:str]
    version: 3.13.3
