# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-backup-secrets
    namespace: vaultwarden
stringData:
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:86rAKSf59xBQBjHUXf8TdvawJLOBYl48qeEc7yya3zqJ1FWDw6BX4tJO7w7TOSvn8zfKieeYQKFtgpK5cBdRTw==,iv:7jcDovDi1/pOcwA+g+hf7HobCXZG72n1UWq55piguP4=,tag:/yahcEARww1fvLCwzCrSJg==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:bc/8Qw==,iv:tQvweQuM0/tzJwNeDzpFxf2z6ewBnGKLaT/PJYvUDaw=,tag:rInnB5u2XsnFje3YtEVOkw==,type:str]
    DELETE_AFTER: ENC[AES256_GCM,data:U4A=,iv:uQIRb/eVStnZzVS4mct4N4FRaP7EeA6ezcqVNPIjTHQ=,tag:RXDkVrCWSYrZYcvLFxZxPA==,type:str]
    CRON_TIME: ENC[AES256_GCM,data:u2jcuuJ8bxVr,iv:oiqgtQMo86til1iUqZkCVgAzB5d+Pc6dJ48WVu5SzDI=,tag:ZyjPNjFo5Cluc1Ci0c3Xfg==,type:str]
    BACKUP_DIR: ENC[AES256_GCM,data:AEZnnlxa+ec=,iv:ijDHw4h+dK2X/GC5Ck+0XmNjBFsKZWO/UOgvaJm/zNU=,tag:t/yc+sVoIxX76j0I0w5LHA==,type:str]
    BACKUP_ON_STARTUP: ENC[AES256_GCM,data:of+kLw==,iv:PCYhLLHOJOm5wzl+YaHJujYYw2IFV+SlrsJ3RxJWTho=,tag:Ld3x8DY2QS3HXXK6alEOAA==,type:str]
    GID: ENC[AES256_GCM,data:wg==,iv:l2Bi6M/I2MuQAa/zblCFmFoL8orYasQaBKltV0BcWdE=,tag:HhDKIXrr7hk8ImZlqM+7pA==,type:str]
    UID: ENC[AES256_GCM,data:7A==,iv:YiGH1PFD1E9oLl10olF9acipZcSlj7iNfTCIoHtAi3I=,tag:2A3iHQ0nMk+hNhoVVtaMYw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMTlYL3BNTmxZWk1BUGgv
            OFpNS2k3TGQzY0dicHY3SjZhdW9NTStzV200CnRnVjFKdlRMc2tZMXZCbDBFNEZm
            MWZJZWFqdm16YzYvYVFQdy9ibXdKbjgKLS0tIGxkTmttQUwzQjRKRWNyMjhqQ1dT
            TW1nTHBhY2ZCeVl6SmRmSzVMY2xETFUKGjSKpYb49BVRq+CFrAfkgP+8DTcFsk/1
            lwRnqzKv1wTBZOIxeZG7fAeaKucxmxtJ3lEdwkE3D9aQZ3sU0SiM5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T12:41:04Z"
    mac: ENC[AES256_GCM,data:UZIiwR2/URa4iz/iQmwhU3DMkRMl2PT+8SEWRumbCYGN8ysXibN6c3/t3qy87ViNzJhYSOI1nrZEubOoGfLfe83y1ZzW24aKzz92R95A1Ro24ZFWcha6/GnB5fG2pPTg0RYaShYYliubleRUJw1XANztcyUNIJzCTMHDMJ9fZew=,iv:ywnmCqGejKjDdvxRvKHQiaRReDVDhyiT5gozh20ou1o=,tag:IervWj+hbW/MS12nB3HQyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
