# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-backup-secrets
    namespace: vaultwarden
data:
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:6NIsPwXWLiUtJLox7OwkQhIj2dN/7W2VnmqxMuk81/MuahyFyR+QhFirDSh/HqcmE/DnUMHaaajzx/DBzLvInA==,iv:BAtjuZq5vugwFVh/1vxKrh728DD3rQHpIMgDpfssMa8=,tag:hHf6hV9Z+88FCwmMd1+3/Q==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:XpNnSw==,iv:hYH/BcU93aryh/yuVNoyQUft80b67L432lD/ITnB00Y=,tag:imWnO737FIQKNpP9GfV7bA==,type:str]
    DELETE_AFTER: ENC[AES256_GCM,data:2ZQ=,iv:Cgd4ZokmjiEjr9BwRj0+WoZpMBqtVrRpQyazdFR6e0M=,tag:GZDPrFKWWA7hR5fIn9X7Jg==,type:str]
    CRON_TIME: ENC[AES256_GCM,data:HugfU1YIiDN5,iv:XJwlH4a6tTnIIgl+5gWCK9z29mU3oIPNgtwac9RPAAE=,tag:PutNlLa39FNTDTlgmfdadA==,type:str]
    BACKUP_DIR: ENC[AES256_GCM,data:6H/kKuM/c5I=,iv:3Bte7bLXxn/tzeybricrG4ey2PQXBneICiNsE4DP6Vw=,tag:QG2CDTnhn6qxt3sgZSPuSA==,type:str]
    BACKUP_ON_STARTUP: ENC[AES256_GCM,data:n9jWmw==,iv:QUL7N/klwiUdW693wOdil1y5piHIcLrUHMumqoxwp44=,tag:ww2BGxUlJKloUg8sJgmsgw==,type:str]
    GID: ENC[AES256_GCM,data:+Q==,iv:Rd0xQgdtKYDXKYAk0NRBAdUAhWsFx378oR5pr470t3o=,tag:LRkzm+X3DoU3EDCsts5ttQ==,type:str]
    UID: ENC[AES256_GCM,data:aQ==,iv:EFugmRqsjY8VYeCQ+FH1eTnBwV2KYfg580q8p0DEAwE=,tag:Y+7kb/lvpnD8Ai+wUHWhMg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQmI5WWRvTWtmZ3ZRcXkw
            aUw4L2NLQ3cxVy9naFNnK2NYcmZ6dENyVjBZCm8zVjBpQkJsNFkxaHFWSmFHMDlX
            VGFEYjR0dEhLcGx3b3doY3hPUWdKaVEKLS0tIHVDb2Z4Qkh6SmdaaFp1R1p3akNR
            OFArR2dlZ0lSUml3SjE1eGUwMmhZQVkK58Tm9F5Po8tFYsnkouc+uaJjN503rHOF
            zBM5AxPFOW79pdIMHJqft7n9GJ6AO0KmzrkWYo+C5Ou7B9aKk4/CvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T12:37:46Z"
    mac: ENC[AES256_GCM,data:Rp8AEXKwcAHeoeupSfHkUB0BnqwSAenGKFYxUuYnwbfalkN/yL6Ps9aWsnAZilsrTuz1civU6gfMgnhrs8Rrvt5Kuh9xVdslobLYvw4XEvk5fLGcnfhxUMFhp7qnsx5RrGf7SCDYA0GKDkaIljrkdifVrycPDHY19L7/Cu/qJCg=,iv:Idfr9aH1J8cnruteIOIYK2j1d3Or5taGgYgE1zSJ5zg=,tag:ZQrwSB7f9RT1cIwvwTYoIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
