# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-backup-secrets
    namespace: vaultwarden
data:
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:vHDeAs8xKvb8KkhG7CKfc3xXENxGA6OK+9ZRsT247oxBP6ErCS+ARR78nUuGn0hGFvBh+yG1VfLBbQKQeWFXnA==,iv:wX3JZk9QvucimLkRvjD5DGiHuTTcFUCzMZgNQj+0IfE=,tag:6QN8vT/YoGXoSREJY7ctjw==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:N55MhA==,iv:NODXmWZBpZrJf8kb9HpYzX4mH+Jn2qFT64xrn1vqtyE=,tag:79mip8+J4RsoWVcrl3LyHg==,type:bool]
    DELETE_AFTER: ENC[AES256_GCM,data:Bgk=,iv:KhIsZ5y42AmoVn7BzD6LHIWnIF2vH9pkrQH4BP1fnqs=,tag:BuJPJlqZFlD8XCcCnyzKFg==,type:int]
    CRON_TIME: ENC[AES256_GCM,data:BwUyn/JsvQFl,iv:hjB+sSr3JtsEc0cSWMB2IbOXhLtOr3Ire8Xwe+lYMIY=,tag:HzIbx/GBgoJd1B77AuMUyw==,type:str]
    BACKUP_DIR: ENC[AES256_GCM,data:BelGzT2PC30=,iv:7kU3GIwasiLTIsUmz+LCJuTFNtsj1pOGa9aE1C6HrBA=,tag:itvWTzAAtpCnm2zMSe9e7g==,type:str]
    BACKUP_ON_STARTUP: ENC[AES256_GCM,data:RXkaFQ==,iv:BMufkYotT6E+J0WJbcMcladbjNzqJpadC2lgpEv1lYc=,tag:GN0lRO9OfrcN/vLwVvaRIg==,type:bool]
    GID: ENC[AES256_GCM,data:og==,iv:nL8T1IqPxNx1K8m9LZpq4YPzssCCA7xgSPow6W63D4M=,tag:7t5+w2fh5GgtBjsySNTnRg==,type:int]
    UID: ENC[AES256_GCM,data:Fw==,iv:z8YNq0T0G1JV5Ek/QfZBWaoF4ycnHPPZEMSdgQH4kEg=,tag:neYR8W2szF5VnOaUCNclvg==,type:int]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bzlleWgySThtdlhTWlBK
            UVIrTDljU1o4WVlDZzk2TVNFa1l3VTcwam44CklGcUxrc1ZTR283RGFMQUlFMHdo
            b2FJKytJeEZDQlBvYnhTejlTeThjUG8KLS0tIGUzcG4yYU0vUW1rK0lDeEo2WlZI
            VlZlUmhMT1ZNVk5Tb01Sb011eVRrL2MKMbEC1wSBhC5leu3sFQXKO+92TKlyqFCR
            HwCw62oXO3ltsVJnCXbsiLCjSkEZ/hh/MGnok3VCSUs/W9nFlFtV8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T12:35:11Z"
    mac: ENC[AES256_GCM,data:HI97zDlfpNXsMBJ+euTNglVelgMvLYfhqzgEBYhSgEGUAUybIrvJ5dXlWcOQGuOOZ9MTyvxwUDIwGU8H8ya2Dt5l9lkq7605PZtlg0VK3ucS6i4y0MmufqkXl4oEETm/DZg5sMZK+Thn/yVkxhHw3R/5Ym2xFmk3e90DJYHL+Cc=,iv:gOjjTNNiheyDu+gk8JLXqvLQs2UjbjatlqEoaXIHxYg=,tag:9Zf5elk2kAFGOfd7iNMEsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
