# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n-system
type: Opaque
stringData:
    N8N_LICENSE_ACTIVATION_KEY: ENC[AES256_GCM,data:kR1FoaEgoxwBBQPwjuLoLxbCZscA/DBCOUgKLYbn+N8hpIJY,iv:NDg5OJI9KJXQdkanCW1UL4jgTdq9ng5T7tWKj3S92fo=,tag:/3iVJsjz1PzvPbX3Lyj1ew==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:YYoa9curigtBj9JiogYzXC+ei+lKbPGgfqaKRB/n7fo=,iv:ai7LFdYmcYSsoUKR5e2La1AhsYXspCFUC4Q4bhkXJ3U=,tag:SVdukMS2XkdGVNB27v9eIg==,type:str]
    #ENC[AES256_GCM,data:+epZPp7BvhySLOINv3NxSsGhQUIpgg22oAJilGE/lImXLFMPTQ==,iv:WcWoSi0QBPBVczhW0hUpFp+gcf1ZwelyTb3Lbtme1LA=,tag:dLccM5Fjf7q+9GknlEP3fg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WttpbUuLKjSFJASuzy2EGMaPjNY=,iv:Ti/nidqto9oYhF+1BcDybA+8/L9sZp6J3AQ9V8F1+BY=,tag:31Wk1eMU4nSZ1VfPp4vo1w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Y+hspuVVSig4lzOYtkT/Pq2tU1h60wIxtcLkimfGZEL1IIKcT/eikQ==,iv:1I2VSwp3q2yZ0rseIcD6cxKAShTBVB9VcgG/GK638B4=,tag:FYXdHQRJEkaYBkUrmPszjg==,type:str]
    #ENC[AES256_GCM,data:Zn+nVveyQpHIQdUQ+X0Ov20Yrav0E/yAWynxkjzN,iv:xtj35jSLecPHOkUc4iV4dW4gWErHzjfBYOT9UakMFmM=,tag:AN3+FxGyDxk7nE7CSS4w0Q==,type:comment]
    #ENC[AES256_GCM,data:pe1lQdzLW2o2tAun4lcGZ1L/Hlb6viEGNxOnEg==,iv:ggS47H4toU+fsOR3WlMnwWTBNJOS6hWNPObzw/pCgdk=,tag:xFtYJl0VrOafGE5fb2iyew==,type:comment]
    #ENC[AES256_GCM,data:3jYEK5krihq9CERg19ub/MaqlmA0G35O,iv:pEwpNvpsgvXjVlTvOPTn52V9BRq8BIv0piRjOEzo9fs=,tag:gXVUfQEtBSwNmuyV52cf/g==,type:comment]
    #ENC[AES256_GCM,data:OvInsT+nZlaU7t0z5ycJByMm46PwxlniNJpXJ99r,iv:3BALXE0LHb1HxfjXy/C0K/i5nealYRM45ZzYWtPjOW4=,tag:U2kWvn3ggZOpcMCqJj24YQ==,type:comment]
    QUEUE_BULL_REDIS_USERNAME: ENC[AES256_GCM,data:wU2F,iv:qudXcKnkHld/jELuLWQFoWNuLgwWgVDufcV3XgI35og=,tag:Qmtrjbka9j9gD10uM0HgvQ==,type:str]
    QUEUE_BULL_REDIS_PASSWORD: ENC[AES256_GCM,data:KC4G0QoXuANMjbp8NgHewxmb9+MtTeHvcGm49wgEnXc=,iv:EmNdL68GXhLg1+0Mzmty5dcQWtrkNUhf1q18ZAS48PM=,tag:E80//RqJbkZf9phQK9G6yA==,type:str]
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:bePw6ZO2jwIKlML4143+SGDsA9wkR810CqPrzaBFUdcF3NU9lg/+0GMC7GTsq0gujvUze9z6klJUczxaP9TgfbapCnQ4RZrvLjZsHtO+IS/L+YeTxxACXzdWRjAsmnRGYQhDthf5jQSTZUYbGGeO1th26rZdXIx1h/4cTPE8cNo=,iv:op1bVIE125vTGJ/7zqtE2Dax+foEbTiYBl6U5qmUTU4=,tag:v2erSEEKF5y6CkmBHC8u0A==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSlpKRjN2Ukh4ays3elZE
            L3ByejVWMjlJZjJrOWlBcGJMVVVCbkpQaHd3CmplTFVidzlvL1NUSGRsVXUzOThK
            L3BRbGx0V0djWGxVeW5qSFhKNFpMS1UKLS0tIDh4YVozak5Ldkh6T3hxbklnZmJZ
            cUNpSUplZFlrM25VRXFMY2ZGZFhGS28KGPP0VOavmMs6e2dibHuQwBZ9F/icLmUI
            UvYY5WV7NuTWmVp9EujqVOomHnRGBjO+Uv/xp+w3Y29wn0AIZcfYzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T23:16:16Z"
    mac: ENC[AES256_GCM,data:PFKMKaEjTe8kxpPq2XN5xikJ5t9XXw0bB+de07ZuWAZuYr7+oExKHAn/Y83XQPAgfPBHS0faFQfvtBBymkOXW08cAZxIoQh3N1A1a1v6lK3mZeDhmRYpnM6V4DajH51DZMq5GoWFxYjAijkh//kNqOS+7/oJ+YS/VNAAqJhcGbA=,iv:rrcvCdMC4sPKRiXw/DW2F/S/K/K6Do8uhgQ9swsK/io=,tag:vpJ6gFcqDBIxfYvPN1Lrlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
