# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n-system
type: Opaque
stringData:
    N8N_LICENSE_ACTIVATION_KEY: ENC[AES256_GCM,data:A4pecwCyDxdZDWJpFme7IXqb+IIekqAJlqodxNBebif/XSGd,iv:Z+AR/jrosC/b8rgGAWFklCEqMsTFHf3XffkDia6uPNE=,tag:wOJKjo9xGXdieleik2pJuw==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:kdFNiGZQk0uZdVW/QW6QyGCNMCQF8ump5hrXgyyKteo=,iv:6iCc5sZFGaVCsqPRhWN9Gcwxr5IEmZF0nTnmLKEwWcg=,tag:AWmqjd9Z80IQNNev4XApJw==,type:str]
    #ENC[AES256_GCM,data:ALygn/m91zTnPejyU2sr0izm4Io03lcPoBuUHNl5U/KudHUpKw==,iv:77H+/y/yZuVF0TYEHYsocWVFUNeLZsnZ/lLjc0+vE8w=,tag:G6/OeLhPdwodW10WENcCUg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mR5QoH4yRVA/QklflfywoaJq9iM=,iv:vaiUCnalT5zNEDhTiS3TZRYZ9r5C4X+FqLGKqxG9Veo=,tag:BemyHidZLTcrCp5QLJ+uYQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+DIzD2mVaphLYIDe3Jp4KxF9HvcPxf5DwcqeCcsqChJk2+58dlu71Q==,iv:zsFQBZO0wbq4d2Mv1m6bsCaMCWEUwI/2u/G2Fc/gk5c=,tag:9G7Fbfn8O06pIxwJbR69Qw==,type:str]
    #ENC[AES256_GCM,data:ISXLEQFp30w+XFzuGQ1chIEawqQ14aqEK53kC1NM,iv:QwzJb2Awc7tH6Sgcgt8CtYMKgerJa0L6zy5v8OtehdY=,tag:kU7aUnT2HS6Gocf8pvScYw==,type:comment]
    #ENC[AES256_GCM,data:J9ZxlcV3vTwdQplAiLF8lHo6wmWNHPrqpERLQQ==,iv:GnyswuNMM4+Xp9/gg3nTNZNtxnF5iNTY/v9xbmGvmSw=,tag:R6hVnZPG3S4kndtGSHtykQ==,type:comment]
    #ENC[AES256_GCM,data:TpnTUOmETHQEwH4LoCAjq/ydbfnDL+Nc,iv:IqBgL5qHSG1B6jZ2oIdDtdCxVtNIZeEI00xB5gf0SJs=,tag:vwO8iWJ9TL/L8LaKIO0POQ==,type:comment]
    #ENC[AES256_GCM,data:LrEORfurHaQdOye1jqrmPmr9j7hKi0+SqVYdUcKq,iv:rmKsCd8qYonfdvxnKoOspJpoEkJ9PqhGc/xE0HA7RIM=,tag:tcYdMvIWQqGjHj1ax79q7w==,type:comment]
    QUEUE_BULL_REDIS_USERNAME: ENC[AES256_GCM,data:43am,iv:CIXOk7N9cE158DGyuSnLQv8cdJaOwGY+91yOArDzv2c=,tag:/ZFuOpspxpqBQJC+R5qWgw==,type:str]
    QUEUE_BULL_REDIS_PASSWORD: ENC[AES256_GCM,data:eJDsfppURsStOubRsbRomvAKP4UJRkfTiUQS4kRC1aU=,iv:AyTC6Q15f6DXIlxsS+zOJOChSRxMP2tDsRNnBm9ZytU=,tag:TLyZzrWqK6egRqCp0wl1JA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU1pBRXJUVFk1VVljVlJR
            bnNiTEczSFJMT2VMTGJZUFFRMitQVEU5cVFFCldYUjd3VnpEdnZHakRXdDc3RVdR
            WUx4SFE5SUdUVkFDWkFmdUdxQitCTVkKLS0tIFlPN2lXQnNrM3FXUW5lWUJTVEpO
            SVV3V3k0Q0NTRi8wMnpDVTlSOE0yLzQKhNsmH6C49X8el6WNG6dzOa5/fHfhtMLP
            KUuF5kllyXdPPX8QrXgJBPpzwvIVpsmDSjIahV1wuVGB7Cjcyj4f8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T11:25:38Z"
    mac: ENC[AES256_GCM,data:PpZysclGLzgnq+3uwnDkuD/3F66/HA3/M12uq/GA/Cx5MwwmNN9oU2YQnR04J86Lc9SZ84p8e+rin81bWVms7OzxPMultxC8hYAMPdIevSzTasWu8O5dWu2bDkGT4gN2nq9S43TKVJSCwSR/nL8Z7SkeCO8UEWmmFvhV045QPlQ=,iv:JdJyP6PeyNkRJNt1CTscmSEKVu7/hBHNcMmbfY+SAqI=,tag:Iyb9NGwkiH3BysMrbVJlHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
