# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-runner-secrets
    namespace: n8n-system
stringData:
    N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:H8y86hbxjxp5HYGr0tWSgtbGg0o+rCLi3rIFe9Q1uMy6kvFVH0tEvQjAeiNZXLu6VqrDhHyV7esrb0kyyrE9s2rDJRnUo/7AuX33Temmc1UMdl4um8LCguwNylZjqdlNEhHWmMzKCt465LeRqdEvhjfCWan6s1ypb734jwtro/8=,iv:ck068BshfdnA9FsWFm77zFJxkYEKqZ4pRetXvtvOrl8=,tag:Mr2BZnFBEC+sxm4E/KSEOA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVFErM2E4M0daQ2RsYXA4
            bWNNY1lDbHc5T0ZTL3VKMzg1UjZpOUZvM1NRCjg5cDFpSFNseVREYUJVVXBYdnZT
            VDRQWlZaRHZlSmpMMm1UeFRoblM3bFkKLS0tIHpNS2Q3VlNaOWRPR3BiSEU2T2tu
            MktsVGFGVnZPV0Z3S0o1S0FQL0ZYTDAKdFkvkjCzXv+ioKpI8mJvPV7s9b7CGeA5
            BuIrHomSwHI+DIRzto2ejJ1f8YUHhZm1JhznHhFbB2/+E7QDTMFD/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T04:29:11Z"
    mac: ENC[AES256_GCM,data:3Y9kVbh3/BvSZlEgs99nE3mb0k7V0MqwVjBeCQygbIrfE3MfPFQ1897LKrbXkrfrcjzl/AIXWXLVX6F6/uCN0Qwvlc/Vyi4BNx5m3M+0VLFYwR31/BIAlB4d+rrqEG5PX58dJybB2fW1lVbQEbBUYdMeIbKXdsrvuLPmeZ2Zs4M=,iv:qSgVxkRIqNNI4aZzNYpbttdEiLXyU23uWgPpePzycAE=,tag:oJYCNCGHUi67SjqVh8JUcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
