# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n-system
type: Opaque
stringData:
    N8N_LICENSE_ACTIVATION_KEY: ENC[AES256_GCM,data:TPwcbhKw7G8aN1KoHwpc74la++ccDaC9s4YnydnlpecwEpDD,iv:cf3swmJmlmTRzaevEjDqJA7Lhmgpd0LiTBwMyq2/y3A=,tag:KNM68xHONMtEd66fuVxO4w==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:nSnFcmSqCiPPxZPRI3CpsMj1/pRPqfI1gLkmGm/t1Go=,iv:nosV6j0TRKMbYeQeF/C7G9K2g9OGU2Pw3cAeolJ2s7Q=,tag:IXVWqSwOG/Gy76X2AP9umg==,type:str]
    #ENC[AES256_GCM,data:fJCnq82xsVhr4ye4328MD8EL130uRAlbFvCLSmjx,iv:KiFYoAfgrjB9w/pW7GA1bVFVzHOw52rPdQXaCzPr9OA=,tag:4McKbBACP7Jv9L7TY2/BoQ==,type:comment]
    #ENC[AES256_GCM,data:VuT2VCRUmHg7lBUWaiKcyrKmWmI2jZ0ZFZ+qeA==,iv:e3ImfidE6+TagEtX7uj6h56E3x4UkJNp0/qDhX3prDY=,tag:fY4M1oMLNyXiVf51wU+thQ==,type:comment]
    #ENC[AES256_GCM,data:7Omoc1ZC12J4vj+GCCS9p0YE/WyArj3M,iv:/L5BkyDrvyLZGdqu+NgopNDlhlvh4iIrODSsLjuied4=,tag:Gn0GwEsbG9ORsU++sTrwOQ==,type:comment]
    #ENC[AES256_GCM,data:uHIXijx6KA4GqQwyj+CUBvM7CA8+bLH0V8G3dsS1,iv:vrAoB23Nnj3nVQfb4T+a0R5vEnypsjqBythHpVSRB70=,tag:BxrI3eZ6W769zZ8IjTsfuQ==,type:comment]
    QUEUE_BULL_REDIS_USERNAME: ENC[AES256_GCM,data:fOG+,iv:ygAR2UccY8PElxqg+2zulqkRQsRPAgMspphUdUkTqRo=,tag:8m6B8sKwSq8oS5WYKuI8Gw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdjhFRDR2bEczc1kxbUpt
            STBnZ0I2azNucnNqUG1HMFNJWGVGbTl0QWhRCnN2QmdITGl2TDNvV3h2aHVKM2Fa
            YWhWV0d3US81WG9CR3hLcWw1UVVvd00KLS0tIE9NT2VTdExoK2Z2b28ybkZoUVBO
            ckM5UzkwZlFObDgyQnAwRm1MblZOUzAKLEFMaLmTB+nYxOJaN7cpYsEcgcKfKed5
            /bRxFAgXNNG2XiTcxV8PfyQ4QeZ460mzZl/D0EUotsQ33ag44u9nDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T11:47:23Z"
    mac: ENC[AES256_GCM,data:CBOjjy4OGoEDdhjQD7iZfgA1R4pNoFmWmeqHo8bjFv1Sg4wM4O0wGzSho1/8MagL3jsGGza59mem4bl9jFvhzF4wcebBZ2BZln1elTabASa9cygawl9HZ2IHlsjrShlh0kc6UjZ2g9nr00h/OCST31PEgFi1TLA0jf4lmA1a7sI=,iv:Znyz0jIjZ1dCnbG3ZtwybVH4bKTKA2wiYBZ9Qt9g27E=,tag:R116FmMKmdYfmN8iAP7c4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
