---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-cnpg-cluster
  namespace: n8n-system
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
  #   recovery:
  #     source: origin
  #     recoveryTarget:
  #       # Time base target for the recovery
  #       targetTime: "2025-12-14 06:00:00.00000+11"
  # externalClusters:
  #   - name: origin
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: n8n-cnpg-aws-object-store
  #         serverName: n8n-cnpg-cluster
  enableSuperuserAccess: true
  imageName: "ghcr.io/cloudnative-pg/postgresql:18"
  instances: 1
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: n8n-cnpg-aws-object-store
  postgresql:
    parameters:
      shared_buffers: 256MB # 25% of the memory defined under requests memory
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 1Gi # shared_buffers under parameters should be 25% of the memory defined here
  storage:
    pvcTemplate:
      dataSource:
        kind: PersistentVolumeClaim
        name: n8n-cnpg-cluster
