---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# Apparently can also do this as a CRD -> https://github.com/timtorChen/homelab/blob/02178963e88dd102f1fe89ebb965bf2e6b4e36a9/kubernetes/rook-ceph/cluster/cephcluster.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: n8n-ocirepo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
