---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 4h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: n8n-ocirepo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
  postRenderers:
    - kustomize:
        images:
          - name: n8nio/runners
            newTag: "2.16.2"
        patches:
          - target:
              kind: Deployment
              name: n8n-worker
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: _
              spec:
                template:
                  spec:
                    volumes:
                      - name: runner-tmp
                        emptyDir: {}
                    containers:
                      - name: task-runner
                        image: n8nio/runners:2.16.2@sha256:d9e65e68c0352c490dc52d8ca2d5849904907308e55d76741c50ae2b5789d101
                        env:
                          - name: N8N_RUNNERS_TASK_BROKER_URI
                            value: http://localhost:5679
                          - name: N8N_RUNNERS_AUTH_TOKEN
                            valueFrom:
                              secretKeyRef:
                                name: n8n-runner-secrets
                                key: N8N_RUNNERS_AUTH_TOKEN
                        volumeMounts:
                          - name: runner-tmp
                            mountPath: /tmp
                        securityContext:
                          capabilities:
                            drop:
                              - ALL
                          readOnlyRootFilesystem: true
                          runAsNonRoot: true
                          runAsUser: 1000
                        resources:
                          requests:
                            cpu: 10m
                            memory: 128Mi
                          limits:
                            cpu: 500m
                            memory: 512Mi
