---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
# Syncs valkey n8n user password from valkey-system
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: valkey-secret-store
  target:
    name: n8n-secrets
    creationPolicy: Merge
  data:
    - secretKey: QUEUE_BULL_REDIS_PASSWORD
      remoteRef:
        key: valkey-secrets
        property: n8n
