---
# #yaml-language-server: $schema=TODO
# Documentation: https://github.com/8gears/n8n-helm-chart/blob/main/README.md
# Default values: https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/values.yaml
# Configure n8n via env vars -> https://docs.n8n.io/hosting/configuration/environment-variables
main:
  extraVolumeMounts:
    - name: db-ca-cert
      mountPath: "/home/ssl/certs/postgresql"
      readOnly: true
  extraVolumes:
    - name: db-ca-cert
      secret:
        secretName: n8n-cnpg-cluster-ca
        items:
          - key: ca.crt
            path: ca.crt
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
