---
# #yaml-language-server: $schema=TODO
# Documentation: https://github.com/8gears/n8n-helm-chart/blob/main/README.md
# Default values: https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/values.yaml
# Configure n8n via env vars -> https://docs.n8n.io/hosting/configuration/environment-variables
main:
  extraEnv:
    DB_TYPE:
      value: postgresdb
    DB_POSTGRESDB_DATABASE:
      valueFrom:
        secretKeyRef:
          name: n8n-cnpg-cluster-app
          key: dbname
    DB_POSTGRESDB_HOST:
      valueFrom:
        secretKeyRef:
          name: n8n-cnpg-cluster-app
          key: host
    DB_POSTGRESDB_PORT:
      valueFrom:
        secretKeyRef:
          name: n8n-cnpg-cluster-app
          key: port
    DB_POSTGRESDB_USER:
      valueFrom:
        secretKeyRef:
          name: n8n-cnpg-cluster-app
          key: user
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-cnpg-cluster-app
          key: password
    DB_POSTGRESDB_POOL_SIZE:
      value: "10"
    DB_POSTGRESDB_SSL_ENABLED:
      value: "true"
    DB_POSTGRESDB_SSL_CA_FILE:
      value: /home/ssl/certs/postgresql/ca.crt
    GENERIC_TIMEZONE:
      value: ${TIMEZONE}
    N8N_BLOCK_ENV_ACCESS_IN_NODE:
      value: "true"
    N8N_EDITOR_BASE_URL:
      value: https://n8n.${EXTERNAL_DOMAIN}
    N8N_ENCRYPTION_KEY:
      valueFrom:
        secretKeyRef:
          name: n8n-secrets
          key: N8N_ENCRYPTION_KEY
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
      value: "true"
    N8N_PROXY_HOPS:
      value: "1"
    # Running n8n without task runners is deprecated.
    # Task runners will be turned on by default in a future version.
    # Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future.
    # Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
    N8N_RUNNERS_ENABLED:
      value: "false"
    WEBHOOK_URL:
      value: https://n8n.${EXTERNAL_DOMAIN}
  extraVolumeMounts:
    - name: db-ca-cert
      mountPath: /home/ssl/certs/postgresql
      readOnly: true
  extraVolumes:
    - name: db-ca-cert
      secret:
        secretName: n8n-cnpg-cluster-ca
        items:
          - key: ca.crt
            path: ca.crt
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 256Mi
