# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-logs-single-secrets
    namespace: observability
    labels:
        grafana_datasource: "true"
stringData:
    victoria-logs-single-datasource.yaml: ENC[AES256_GCM,data:aBfHPFJK9qkdF/FklUTqnGCvBuCtud/qn9L8mRgoe2wql4e52ROVS/2m5UC1lDc8lxtVF8RoVuyNbCfva2k/ZsTJx4iYnvqikNua+0oq9Q8cJ9mYI0ehbQLLBaMTRV3m2p10oJrEN/mwfJJ+1WHN5SKzJfSkL5pqzKuJdCyj1cQ/UtOJDgRkjO4MbKbw3scY2ivJUESZkwSK7Qs4Bl7864WMcjq8+z3hk//V4d90EhtXECSkToMR+R98wWXXmSmPnVxdheQctUtFFpYVq85H5Pp70R4YWQ/bLw==,iv:DAadk9XxBhIihspB4rLeuEYFd9RHb1rP//pV2jRWEjU=,tag:EUhu4syMQC0kErT0NHpFLA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaCtDK1FyUVcwZ0haZXNy
            VDU5U1lFN1oxZzVvVnVoZk82anpVM2R0T3pvClN4ZUtmM0lxOG5jcEUzRHJ4YWZ2
            QmcwV0VGdDZOU1RhTW1ab0xXUVlHb1UKLS0tIExCWmZJVzdMMmwrMTM4aGpadFlX
            N3h4WmNDa1lvYjhDUzNUUVk1TzlLWncKTxFW6eKnbcuwcsvAZEBGjiUJjyBuH87E
            ZSBO2sO3nQRLTMTgWCOx7kOWGlpi5ETcWxM4pzzZsKdbY8HEIDiZZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T10:39:46Z"
    mac: ENC[AES256_GCM,data:GgDrl+4xyFLw9GrPtF4pvwyXLvOUUA6WtRTwyCcT+EF/LpHMJ/bZRMGOGOHZLL+OvQ5D4uvhiwm2HdKyU/dfpqHGr3hEriWegOZohqpehEgzIyNsYLdnSJTj/pQVY0l/sndIle/bYqkDWYcujCSDg0SKIW1izhkM24C9vPBkgIM=,iv:SOkN3XpEQ2apOzkGPamTN0J+D/lijDFTeTXNn1rLdsg=,tag:ElUrPlbZHIglyivGpF8FUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
