# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: victoria-logs-single-secrets
    namespace: observability
    labels:
        grafana_datasource: "true"
stringData:
    victoria-logs-single-datasource.yaml: ENC[AES256_GCM,data:inShO2KAtWr/XW2qejBP9X9lnyxIXceuuVkbA5yJEqCrhbu1TxcAEjUovCXaQtMkczXDEctbFJ0TW2KKNGW/cFunYDTOYBuSRQgE8w3TL5fWKz1ZHfChoqXhLSQ66c9Ne4LdoQXrKV9WMLiaDdCuY57dANTeg4TivmKZ+H86+LFZViJbgOINSfbpefisnLgcfoZ2hojoFTIARuYWSn/XckDXStW9S8+6J2UIiwHwJ3wwUQkiataVJWAY83cv7rKiuMzO1TtwOPVCCUgQZKxsVmhjo34kmA==,iv:NP1v2+dVSl01Bnyso78out5aXulOUo60fhzEzCTayQs=,tag:erw44ZrjO6lycSj84gjs8w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOWt0clZSUC82V0JzRjBF
            NER2VGJ1bS8vWXdLdWJxTWQvOEwvSTVLOVRvCk5EbFFwTFVQaE5HM1lWNkU3Y3Mw
            bnZkVnlBc2hCYXRQOWFBVklYdGZNdEkKLS0tIHZNNlVIYTUyOURqM2hJblQ2cVkz
            RHM4Q2kvSWxJZVQ2dnR4VEdFVjJnR28Kl7+S91zXp3F6yR4axr355f3cej9xc6al
            dme8GfGQwHvTFiVExyhYctqoTGDZJ3CjfpB+xTfLwLp4YyiEOxjIaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T10:25:29Z"
    mac: ENC[AES256_GCM,data:ffJN1llPqFcFQrOoyDiHs6U3+NHoBpepti8HAz+s0pmz99VkkACoz7qY281ABXM/N2ZLXMCp6hd9npXc+JB/UyiPTh+zyvL3D7U0ZF/vZHIL8Z310mhVwuMbRkFoqBUCXpNugP4qiP1qPBpDw5F3FOVUtxZ/gqgWAoZ3ge22go0=,iv:a3crQDFuoENhLD5Ns3MbqVpD6fbN6LatGX6d/YPEQQg=,tag:SsqeO1WcDqw6UWikuc93Dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
