# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-workspace-env
    namespace: coder-workspaces
stringData:
    AZURE_DEVOPS_EXT_PAT: ENC[AES256_GCM,data:4X/s4PUsCdnfI2/f8bmbUt3tU0Itwge+HHDZ7ADQLmxTZDn185wNfOwTHmP/7KMU3BbxGBk03KT+IXRftSQf8kmZpIlj5XZbfVIuD3ne5EclSLxh,iv:SIJg9QXEHmeqw7ZuMA8tBh2PJCmLkS6CJTQ4jzEQAWw=,tag:FnIt3eR7K6uM+tKJPFtT0Q==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:E0Xelev10tzOlQ==,iv:Pd6J4BYr08bV4/WpJgfXbYAjG9Dg6QKLMBEzd1DKkEQ=,tag:htVmrxTOy/VZvdKh8uBV3Q==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:X/89AACrhpoDTD7zqZJrhcwkjLvKSXgvQsxaTKSbkGgEhgogIkm0cnsBtiln58hZ9O009RACeYUJ,iv:2bL/c72ABPoGn3iSO31UDiRQGakVtbrVB2n9/O6l+ZU=,tag:lE9IWabu1MRXMDaGeccK2g==,type:str]
    SOPS_AGE_KEY_FILE: ENC[AES256_GCM,data:6sMLR67DUvwmWkjhKrX2MbvTWbO+GwTxQpkjmO4=,iv:OmIImVNQieNOoXF+pFyzHw+rzX8Wz/dTBXL8N9SnI50=,tag:joBh5c1Vagqs69BgzEGvmg==,type:str]
    KANIKO_REGISTRY_MIRROR: ENC[AES256_GCM,data:JTvx8m3ylRKuuirwBTcQSg4lBrsMxouKb7fJ7NXSmNjPT5jUELengTE=,iv:YwyFGR3klOT7beo6x/ZfGSMZNK6WkLAzZevW0M5IDLQ=,tag:idTVlIN7fvFRx9zrAKP78g==,type:str]
    ENVBUILDER_INSECURE: ENC[AES256_GCM,data:+tNXfQ==,iv:BhixU8Q3uQhhapesn7pasQFLxJY1+rhnBi/YMkeT20A=,tag:H06XRMUg2bQARAFclrxqtA==,type:str]
    ENVBUILDER_DOCKER_CONFIG_BASE64: ENC[AES256_GCM,data:1melE5kCnRIqqQZgxGq3CXfsxE6n3u9EwedPsSRsHyT/c8IaX6dZM/jVrm1N+mwdswltPuOIujvWo+1DEgvczqs0QMxn1aq+jGv54k1R0eNZ5RGWvS+kqLdhi4l2ItPNYmE57/Cr+CTJBqgECeSwbGrYVv4LfXkmQUijb4Ok9z7gUCAQ+GqEDiLYYPVfMUeieMnUe1rnPiyCoqYXhcBcMkQQfVvbzDw0H7NrgT0i4EWbZdbSOnxiww3z3ycvZULFyBycOG9+6Cqz0q53OD7fBuzN4OeUBssCz1fSwWcdinTbpZroEXJfxV2INIc3UB0NgmljfugY5G9PloJrQA3Txuf5h0i3OGwoHGpWSlt1jtR9jGb24+P5q4PBgrw9lxlxh494bqcddUT9qQmYWnLBs1al61dpXUMc6xiBAlG2DR0bpqTAYXyvbCXQ9/UTdE62yWao30BZkx17xebB9sQkVD5mRnqs99vyb9OB0U22Dh7j8sJwmce28i5/MhQ+RFmu1MnaDj1EgHf0EebgAnT+KKfs9CAl8BGBZ/W1KZI6U52/hBzr,iv:o/eTXRlTGCF3GW5YLuq1Q0ggCOPa8/AL0vXZt5FEk/I=,tag:QlBU46t5sFkOBc0sQuPBBw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bngzdFg3YWZQSk1JWm5P
            aUxmbi8zblZINXlyL2xNZmk2dlFuYjRRY0NBClROYjA4dVlmbjd1YnQrdlZyRFFp
            SDBIaitONEJSNFJ5QmdOUnZMbnpaMWsKLS0tIEczdlNLUTRQbDJWcTJQR3Rub205
            aStWUWw4Sy9kZjBYVHN3OEliVmFSTGcKPD3csoLWogZaIM9BeCUocT1s3c22YFwO
            dmscwpOvj/rwNcNYr7VB1/C2qJ0NhYOSR0OA55zR4nwx8ocnCP/BDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T23:12:13Z"
    mac: ENC[AES256_GCM,data:3c/bfIigozgql7woOewkN/W/Hp1ohzK8KXn8D4WusvnU8rx0d50snCP8xBTxMdXEiycXx7KBtEjAoz/awoca5gkukVEhaMj4xo//xesAYW8ZWiGSGIBSwQforxuMqShRlMyGRhY5k6l9XnOfwwOTytbXRO3bUA+jGbz3RhhHXi0=,iv:tsiY0Lzh0IaRKl5KS4F6cLVeUK365eOb+xdaTDyGZSU=,tag:LSCA4iy+Ha6iCYsY6Cx5iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
