---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coder-workspace-env.sops.yaml
  - ./coder-talosconfig.sops.yaml
  - ./coder-ssh-signing-key.sops.yaml
  - ./coder-terraform-credentials.sops.yaml
