# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: aws-secrets
    namespace: cnpg-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/Pva3kW5/8xx0VoqyHEhXTNsZ7s=,iv:Mm5sDqcwv+pkgLt2dvBOyockUE+gVE9+NJPNZnshwJw=,tag:KKA+PGSn2uFeAbyA0cRzXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y5lLyStNeb3k+hsksnlq9xkqSmYv4nwGcB/hagM5L46nsFE3hxyphw==,iv:H9gPtl0CrcdNZ9cZmE+qjw1g7WqCOxiCvOqVOwz6ZsI=,tag:glD6BsA6ClAZ8fJJMPBvRw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3RjK01VNGdXNGZwbE5j
            TEREd2JWdTJQYmtOSlVLYlMwTG9nOFZUUHprCjRrTjZTcWxaR3k5VWlUZWlRcDU3
            dWVBRUdBOHpheVQ5UnNBQXpqNkJxRmsKLS0tIFFzQ0d5L0JhZFB4VVozQjI3d1o0
            UXF6dm1zSXpHSmdtMENGbzhrYk5QUjgKF7t1W441wQP292md2HjP/rEGM7YEGGGD
            MhICs35D1+xKTVWiwf5aggJ1q7PYu6i5uksDuo9qd5v1LnRsIJQhBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T11:20:45Z"
    mac: ENC[AES256_GCM,data:1Zgpmquq0JXsQLE3Qm+v+fBfDaMdAhsEPjdaNq1/pXz1xpl8BULzug4hq2R8QHYCMlVrDOnkmMGgXkMdpp5MZT8Cy2TXuL2rPQ6RjYMkHAUSJ1eA1L0BSWol8h5M/cqXrxd2SmHIAk7I+pr/U/vSMNd9gpNy9vV/InG8roHfkI0=,iv:o8bXMWBmeYEn5mk8wTLahFqCzaLfAZm/YSp2z08bZ0M=,tag:xtT0YKlp087RJda9uWn2Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
