---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bedrock-connect
  namespace: &fluxnamespace flux-system
spec:
  targetNamespace: &namespace minecraft
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./cluster/apps/minecraft/bedrock-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: *fluxnamespace
  interval: 1h
  retryInterval: 1m
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
