# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-cnpg-credentials
    namespace: coder-system
stringData:
    #ENC[AES256_GCM,data:hzfqzw6fbYh6IRfRIGmzP6Dn08qCpYZHQHxM/Vz769auNL68l27LHQ==,iv:ifQjUjabLOSdxU5K53z50+dc59t+oNC82y1qmOiJqQY=,tag:ODuRYjAHNCOpr1QRz0N0kg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jX844ugK33p48wWBMcjvZGRJF08=,iv:0S/WxBMAYOFXuUHfqUlM3hxLRm+pDUNzU5XiHpR9aek=,tag:m91chN5GLsGFrckxpQyj3g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:t6TCqExb/71FvwNMxiVkP/aBRDmjpCoZQrTF2zrXytAiF1mPhHWj0g==,iv:AKvX7+D4NkHdCy+r9XZhvOq6byJbkEaQ7DNyHp8m3GY=,tag:t4qDM7XsP97A02wR5s+gAA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdjhBOElmWXkzOHh6Mktv
            QktITTIrV1BGZHBYVXh2SGNHSExuTVBuQXg0ClU3WnRtNmloaFRKNkRUYnlJWVlL
            dGtEY2xEeE5KRlRjSjRrN1U4WFIvZDAKLS0tIHZ4UE03THdHNldLaUp3UGFtWHBC
            QnJ0TFFQbjBsZEJmUU5raE95cGJUMUkKvDlncH7JHOTp9GsSwmwhVzKMh0GEAOtM
            ouyKpdizDAKDUVs83LNY1UsGCtV7+YvXZN9A6A0A2ngsoN9GxP+T/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T06:55:50Z"
    mac: ENC[AES256_GCM,data:POuJSHMdmtqvyVbL5fD8P7M2I024ycBZ7ns6KPax+gYh6+lFBsOIiNYP+4YgQXw1GyjBGotxoCzPsEPGVQlAwcZHMK8RIT1NQZAOjHmMdgAd34h71sX0bIeoiVR3gtPz9GYKd3HEguJHLaGJ7ObYgF8LbsxEwFnmkxSO8uO1vhI=,iv:GXmP7NzFHVOhJa+Ml5xl27IhEOFHo8hNgE/lhbGca1U=,tag:eK1OkCgUZEUFM54FJSss/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
