---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-oauth-credentials
  namespace: coder-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: coder-oauth-store
  target:
    name: coder-oauth-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CODER_OIDC_CLIENT_ID: "{{ .clientID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .clientSecret }}"
  data:
    - secretKey: clientID
      remoteRef:
        key: authentik-coder-oauth
        property: CODER_OIDC_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: authentik-coder-oauth
        property: CODER_OIDC_CLIENT_SECRET
