---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-cnpg-cluster
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: coder
      owner: coder
  enableSuperuserAccess: true
  imageName: "ghcr.io/cloudnative-pg/postgresql:18@sha256:36f19b80864f5ae23bb6ce87166e413154bf8c1b705e893ec8360ebb4791e63e"
  instances: 2
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: coder-cnpg-aws-object-store
  postgresql:
    parameters:
      shared_buffers: 128MB
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  storage:
    pvcTemplate:
      storageClassName: rbd-fast-delete
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
