# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-workspace-env
    namespace: coder-system
stringData:
    AZURE_DEVOPS_EXT_PAT: ENC[AES256_GCM,data:EynSp/iQIGCkiOVdhphg3bJFJN4X6Ji+XJIO6PIPl/Yp5HH0e9qiwXSa+l95ybMDvN1jPuuDmLjkFqs0dfp4EGaxL/iUauXcGyTlHPfKiZ/9eWTU,iv:GVhpk5aVd1/nc3THYBfbptFTYOaneiA8Hc8Kjmj+KhU=,tag:aiNA1nAnBh1fAnNMi0w6GA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:C1cR2WaIPJfg5w==,iv:ysGXZjBAj44CR3+tmeMPBw3oXqlDCXo+YcTh3WQyro4=,tag:Hy5PF5mxtz/WOzLi3FfkwA==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:dHkue8LoDh1+lsrjx3trmPkfkXKE6/o1VDj7fep70xmcM13jkO/uQfwLVmYamcCbvSAd6ORzKn+w,iv:Z2jSj9QdjNiXHT79GvTMmRXZb7D1IhELHbeHf57W1VU=,tag:dICrHeu/q0WCEiurqohAeQ==,type:str]
    SOPS_AGE_KEY_FILE: ENC[AES256_GCM,data:+esvslMOabG2bqRF5i5sYbk1mj3wfAP8w2EjG1g=,iv:5g8nMBcniR7O2MjmLlfpL5+g62zTs3+3qAtPiy+Li3I=,tag:pELKEb1oViTJ9IG7KqNQPw==,type:str]
    ENVBUILDER_DOCKER_CONFIG_BASE64: ENC[AES256_GCM,data:0MC4IDIBa8Yrol/h6zwno3gdXxq0f/xXTW5Ef+I431QdhR+7yoI5Lc9DNUM8x9WpHNJ4V1RBQFVJlw0+ceNl2fWa77mFi25U/pgitQ7C5w6hTxTX/PwITwvfl6+oY+9T0chAeBwo7RpL8PTo6juaxKJxREfbCEcrG+NWahDMwMxoJTU5Lmjd0VgqbX1f6P2mfVRwNg==,iv:22Cq6vv3+UvVZc0GTgwxEXxlMbV2MuDbnPFFvtHRq7E=,tag:sAnstPVv9nrLJth6Gzv3hg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMFhVbmplMjB0ZUlqaC90
            bUI2YytQYkZEa3N5dmZZaHE0VnlpUUpxa2s0CnlyNHdnMWZaTFBadFkrak5SeHBE
            ZEFyZnU4UUpua3ozVGVkUHBLZUs4OWsKLS0tIE1wSjJnckM1ZFlmTXE5TzNmVzhP
            VWlSblB4WmZteUNVYmVPODZmWUNEV3MKsABBle9ZvRiS6OVKoWhkDJtYLYk7CExG
            9JOjTdE2jr4ftCzhb8dv6sjPLWak18nk6SWmy0psnp2YnVAyr2sKHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T02:24:59Z"
    mac: ENC[AES256_GCM,data:1hq8bv/ScetqASthl90PGjSnx8L8mY5JqxHRZVPzu/XVvq0lvCZqf7wXvLX37exR2A3eKEWYp7wfzLw9G6MnEXzsvavMZaqEDSk1HnfE0srJT4oaS21BpLzCIr2NkjCLiwBIFs8kgd/KLGFyJIhxNmuwWJu7TDUJ0wWApjQzldo=,iv:qz2D1KuKNwWiJ+bQZqYgKY3I9TfCvLqU2DjOsKa/qwo=,tag:1/17Mm4gc9XrzyJBhX9G7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
