---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespaces
  - ./namespaces.yaml
  # Fluxcd
  - ./flux-system
  # Kube System
  # - ./kube-system
  # System
  # - ./irq-balance
  # - ./spegel
  # - ./kubelet-csr-approver
  # - ./reloader
  # - ./chrony
  # Storage
  # - ./rook-ceph
  # Networking
  # - ./cert-manager
  # - ./metallb-system
  # - ./traefik
  # - ./technitium
  # - ./external-dns
  # - ./cloudflare-system
  # - ./unifi
  # - ./whoami
  # Observability
  # - ./monitoring
  # Databases
  # - ./postgress
  # - ./mysql
  # - ./mariadb
  # - ./mssql
  # Message Brokers
  # - ./mosquitto
  # - ./rabbitmq
  # Games
  # - ./minecraft
  # Security & Identity
  # - ./vaultwarden
  # - ./authentik
  # Automation
  # - ./n8n
  # - ./node-red
  # Disaster Recovery
  # - ./velero
