---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./kube-system
  - ./kube-public
  - ./kube-node-lease
  - ./kubelet-csr-approver
  - ./external-secrets
  - ./reloader
  - ./observability
  - ./whoami
  - ./cert-manager
  - ./traefik
  - ./spegel
  - ./csi-addons-system
  - ./rook-ceph
  - ./technitium
  - ./external-dns
  - ./cloudflare-system
  - ./coder-system
  - ./coder-workspaces
  - ./vaultwarden
  - ./irq-balance
  - ./chrony
  - ./minecraft
  - ./mosquitto
  - ./velero
  - ./cnpg-system
  - ./valkey-system
  - ./qdrant-system
  - ./n8n-system
  - ./nexus-system
  - ./redisinsight
  - ./foundryvtt
  - ./sungather
  - ./dev-debug
  - ./authentik-system
  - ./headlamp-system
  - ./kyverno
  - ./falco-system
  - ./firefly-iii
  - ./nut-system
  - ./kubectl-mcp
  - ./github-system
  - ./claude-agents-write
  - ./claude-agents-read
  - ./github-mcp
  - ./discord-mcp
  - ./brave-search-mcp
  - ./n8n-mcp
  - ./vpa-system
  # - ./snmp
  # - ./smtp
  # - ./mysql
  # - ./mariadb
  # - ./mssql
  # - ./rabbitmq
  # - ./node-red
