# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unifi-network-mcp-secrets
    namespace: unifi-mcp
type: Opaque
stringData:
    UNIFI_NETWORK_USERNAME: ENC[AES256_GCM,data:Ia5m64GsYA15Kvm4kg==,iv:DD8ohjMQk7hiOyv8s0Rl37UmTjU03atLcREh+Ena3/o=,tag:PIlZRfIgFsb7cU3TxhQYhQ==,type:str]
    UNIFI_NETWORK_PASSWORD: ENC[AES256_GCM,data:HJriTnZmqQr+T6jTLKLRepK1PY3m4nsK8yUDYkSPG0zr4zCsVyDptKNuzie3aEizVJ36exDsbtiPYyysFOMJwQ==,iv:B/rpYXrYUnTS+R/snMk5QDtGxPfRsVQAR72uUho7ZBc=,tag:+q3E5f+Xd6JZ42hE3cdEoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUFh3SGpiVVNZQlFaVndS
            RGQ2RHArUWE3UmJEM2ZVaG9Ga3B4SkxwU0NZCnhpNkhseW11dlhmUkhnZVNZTWJV
            YUh3L2V6cDhwSmlndkJGdTh2d3RSMGsKLS0tIDdnZWpOTjdmYmYzUVdURXVmZlMx
            OWhETmRFOWl6cFV1M3NLV3RYS3R2N2sKU3eZnEV4sZgAjZPEJpnLPHREt3HjfZxZ
            kHjvN2fOX1Vzr2v4LJLg+lSimr+I+xxWE+Ik0ojH6Ihli9hrJS4QhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T03:10:55Z"
    mac: ENC[AES256_GCM,data:Im5/Mzh29xsdBap/NNtIPbfSBsgMInEWYlI5ZgEI0Sl2G/YuVKYJSZn4vInn31yucqlEgdME2nV/BWYc0iow7lHdHLOF75q5t/YJrm3ThsBLJDi0bz4hX1Vl8ZBBzk6m4QQI5g+VEhvwk4b9Uk7YVZ03g2O7ZDQfVcYusNsjetQ=,iv:Owh4VrLjsGm3APuawMFPH44CzjJ6p4W8RsWWJB6egOI=,tag:ZMBv/g12W+iH0tkOeEp8yg==,type:str]
    version: 3.13.3
