apiVersion: v1
data:
    TFE_TOKEN: ENC[AES256_GCM,data:kHLbLnPbLTl2YBouhpliqng0Td/CfU8QOq/QrMMKPRlbY3I1CxavRw0U/nINvJ3SBKxWSLCzq2rY4Ih1v2n8QHiwXNilK/GntkxFLg1RAY7o38/P1m2mKzEAGXGoeWfrT2UWkUo9803AcGK9Ko4k7LBrqujkFELj,iv:I+9TDDHCZuscXck98Mk4HgFxyQWl8yrzNjvlqVWWitQ=,tag:uz5qqvfBDQ/MyNWAUwLWQg==,type:str]
kind: Secret
metadata:
    name: terraform-mcp-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NUhWaGZkdWtJK1kyTXYx
            b3ZZYWszSCtlbGtMUzcvWnE1TUtieHVLVFMwCkdpenoyeE5LNUFWMUYyT25xdWtH
            eHJBVmdJUGxwU1VqUUJnTkgyZmtyRDQKLS0tIDVJQ0ZWTE5XUXR2N3dtRjAweVFr
            WFpYQ2NkWkp1MEZlVVZFYXExTkM4V1kKv5wrUkum0QEW3H1AJOg2Hsb2E3wOZBc6
            2EoiNYFyXv7NRRLV2RKZISqFrqokuAQ7t/l1bcE6dSpC2hgKTpuLaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T04:09:22Z"
    mac: ENC[AES256_GCM,data:16YJ9sLhG7/rr361WiSWcth7QVJZczOSkjHL3KCit+mzmFBmAwjO2JTcFf4+Qqo9UcFqgPLpICVxCfDGCcrNa8HN4tYtd5zr3/0oCWx9n2GjOJsza9WePkKuATt3ZqjmDbZMx6L4RSeoKM9rW33f+jiCnvuUMhCdP4aDtATJ6u0=,iv:RHVT6dUOlhzy0Dauc+deIEmQl9VIvQ/0jgwUYoxph7I=,tag:fz5aFYhSUbuTt0hFVf+L5g==,type:str]
    version: 3.13.3
