---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubectl-mcp-server
  namespace: flux-system
spec:
  targetNamespace: kubectl-mcp
  path: ./cluster/apps/kubectl-mcp/kubectl-mcp-server/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  timeout: 5m
