---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - ./persistent-volume-claim.yaml
  - ../../base
configMapGenerator:
  - name: minecraft-bedrock-creative-values
    files:
      - values.yaml=./helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: HelmRelease
      name: minecraft-bedrock
    path: ./helm-release-patch.yaml
