# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-technitium-secrets
    namespace: external-dns
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:4iokmhlP5FyjWMTmMHhv7Mw0S/SVX6jyN0W7/vMGajZJDYr8aTQdhn5KKl4=,iv:VAkcueYpI4TpwQ13FIcnK/Hju8jdmlDQoGBnlWx1i3U=,tag:rlfHuZAF/2KvtgXDsi+QHg==,type:str]
    EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: ENC[AES256_GCM,data:D07hWh5hG1hDwpU3,iv:SSRy4iE0EdxV8UluWJV/T5bp0Ohsvl8wg7q7B1T7/Cg=,tag:p085pDMrTxoBbT442WfhNA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2l1Qm1MdkVqalljWW96
            ZW9GTWsxVWVVdHkzOFozN285WHMrWW5FK2dBCkV0VVAzbFZmZG5zWndLdnZkckVV
            R3VBYi84ZlZyOUNnbXVnWStTMlJDazAKLS0tIDNjQ0F1MmRwQlRldWk2YmEvK3R1
            WHB5MUNNZGtPTTVkVXlSQ1JVSGZvVUEK7pWswooRVsDZ7xns7hVEd09DkahNZZzM
            I22OMjGRFAkjWdxXf3PR2aPsIVqYUM31WczIr+1ksp0MaycZHREQaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T06:32:25Z"
    mac: ENC[AES256_GCM,data:UPn+6v0QC6IBB85Sgcfuv+ikYKrQhcQafpZi72FnW5WVNpBTaj2ge+clbYm/XGwrngpBP6pU+uao7SGlzzFVSUJ20xvC8hNJFWssVvPsJlljIIzejf55uH7UdhY06vOevVGiv81G7yfxIBwG22vPAOWuJlp+hz2phA27LYb0tK8=,iv:X/I5KIFGppZq/LacC2/AAFzqehEOklFAlKIQfMfZxQ8=,tag:Cb3mhdNkwAc1RRDxY5gmmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
