#!/bin/bash
PROJECT_ROOT_ABS="$HOME/home-labs"

CLUSTER_NAME="home-labs"

CONTROL_PLANE_1_NODE_IP="10.0.0.11"
CONTROL_PLANE_1_HOSTNAME="c1"
CONTROL_PLANE_1_DISK="/dev/sda"

CONTROL_PLANE_2_NODE_IP="10.0.0.12"
CONTROL_PLANE_2_HOSTNAME="c2"
CONTROL_PLANE_2_DISK="/dev/sda"

WORKER_1_NODE_IP="10.0.0.21"
WORKER_1_HOSTNAME="w1"
WORKER_1_DISK="/dev/sda"

GIT_OWNER="johndoe"
GIT_REPO="homelabs"
GIT_BRANCH="main"
GIT_PATH="cluster"

CILIUM_VERSION="1.17.5"

source "$(dirname "${BASH_SOURCE[0]}")/paths.sh"