---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chart:
    spec:
      # renovate: datasource=github-releases depName=traefik/traefik-helm-chart
      chart: traefik
      version: 36.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  # yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
  # Default values for traefik: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for `traefik` container.
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 8m
        memory: 300Mi
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: false
    service:
      annotations:
        io.cilium/lb-ipam-ips: "${LB_IP_TRAEFIK}"
