---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./fallback-certificate.yaml
  - ./otel-api-key-eso.yaml
  - ./release.yaml
  - ./vpa.yaml
  - ./coder-service-reader-rbac.yaml
configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
