# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-mcp-api-keys
    namespace: traefik
type: Opaque
stringData:
    AGENTMEMORY_API_KEY: ENC[AES256_GCM,data:JLNea+ELdBbRsS0Ia5I3Who//cs2nrWQIMEO7UcBYBVFvNhmj8VRv5pqLbPQEKSdXM8goA9YEDjO4x4XAydYn4Xg0wYMM1/jv1W0NhFQhnugYutkrKpaNvXJCATW/yk22lBCQwU5iIivG6oVOAkD7/gXyIr9R7xLsWEabRnPSi8=,iv:0zcGfQ2zlUo5QYsUp00csnHbGLK3tF84j0DePWWL/b8=,tag:U1V6fFizopGjCBWv0BbkcA==,type:str]
    BRAVE_SEARCH_MCP_API_KEY: ENC[AES256_GCM,data:XHCPSuPTssDc7e3P+gyGT7KD3A+R0e5C7tHKwbAeaBbLLKGq36pduemL7e8xRC+y653jF18pXftb3a3FWsx43g==,iv:vdUFBljZ7DcG551WuKRpkWhtzitek9huQQfqjKTfXjM=,tag:V7FVSmRTqlDIk/l8e7Qpzg==,type:str]
    VM_MCP_API_KEY: ENC[AES256_GCM,data:KvJavojKqruNBKQTiBkZQyWefwMzxd4A2ZA7rpSGj9duuUXAsKhmf9JIGsxUP2lhX4bZeRtbSAQaGm0NmnVy+hm/hYioxmqLeb9Ef7SCEVW1oA6LK7Eaa29TJ8ZnwnDl2gEeEzWSxthFRjKGNAoxZQiYluVDsklYsysSkD7QzsA=,iv:ItROCXx6NEzc5A5i/Zt2X4dafwaOFHWwnvWsiCuJtBU=,tag:EkZIN7u141vo952Bxi9dTg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ3U1c3d6VGVFQjVTY2Y5
            SzExUE9ka0cra1JBSWJJWXliZFlWamJEc0JBCjZ1R0IwNm1HUko0TnRvS2c3b2l3
            aWhCV09LeVZmZlJHMXhyRkJPK1lCcXcKLS0tIE1FR1ZaaEdvSVVnZzFMS1RSaHdz
            eEg4dUsvZEtTWVJBLzZIVUk4L3VUdFUKqndGGFgRLlau9uM+iGJ5v57mHMmo8QKN
            JcA1aCqZcQ/pqELoxPHGs8G4OMNnvo5olmxRx8061RwYICe/5n5SWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T07:29:14Z"
    mac: ENC[AES256_GCM,data:ZvuDrJnY4SKaqEdYYOKVFkqKXam6uUP3YaS3HgaVKEt+Rtodgrvg/+d5qMMiLMwj+RqztadPcFqvErBdjLcChrDH801G1BftDt1TaOFtF/+usQxFRef1G6h5YLBJ2SEYSUB0M1K0i0ZcCmvwYkgUfJRxeNlPkCHD+J+oV9wtsD0=,iv:fZlaL4tiP4gEW9gC18V71yez3/X3KHfyHAZ4H+IUz5g=,tag:65oltaPd4kYZH2bnwLsZeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
