# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-mcp-api-keys
    namespace: traefik
type: Opaque
stringData:
    BRAVE_SEARCH_MCP_API_KEY: ENC[AES256_GCM,data:iVyambFKjN2R/dCRYSKfTDjfpP8SWJbUpSIOPjYKeezXD0TW1wUaz8QaG0Gf2BJbjxIEAEXd3o/dt2zFMdKMTg==,iv:gmtvos7OL0Tiajt+5HJ5s+5D9txignmty7mb9eRpfk0=,tag:WXsXvlcJNpDvkhbANc4Fxw==,type:str]
    GITHUB_MCP_API_KEY: ENC[AES256_GCM,data:egQa7qNl72wOsEarmebX4o8kgw/IbxeHmHMcbEjBxID1XT4u6iE+qO9I4LkTKkaiRRvfDBlwVW+w5Fnd8pwX+g==,iv:tloSU7MjyEYVzW3AivTGJjHJCb2ZmzxSWbaJlFWoRnk=,tag:PeTP9LLisb9kmYSpwwioaA==,type:str]
    KUBECTL_MCP_API_KEY: ENC[AES256_GCM,data:vDWliQc6A9O21nJaZ+mk4yNUQVRHdU16Aecxfd/YhRY0QU0l3vzFZ7+PUrs6DBJG4aPO1RKJCKXYdoFhxpm6+A==,iv:rxqGd9Zf+vV5yONO9QTZ7jh4B99NPVUpYespcr1oVQY=,tag:20YCEVVfIlTvvUEIH+8X7w==,type:str]
    N8N_MCP_API_KEY: ENC[AES256_GCM,data:SNSmr5/7jt7WuQE9KnyBWk3TQ4K/a74K5xIVihnzIChoaO98gIYIxKU9mNDZ4mEqhuBT8QFAvH6UptF8Bv+jAg==,iv:i+/7tPpM9bTdXEn9IST1ZjQQ8elrM8wTf0j2GmA45pA=,tag:UuSLZ92iUhkGJfHDaa8Suw==,type:str]
    VM_MCP_API_KEY: ENC[AES256_GCM,data:5tGy4Ht2i44sNkMmTcKEmAhHn/GD9VtJjRG/IeFD20UeS8jBWzplN3Ev+JRIxAR19fssu6h8WEVVTcYIquXgcA==,iv:Wi2fFkoo0s6hxqXId/LTn49wLNL0y6J4MJC41T1lDOA=,tag:bPn85Y5q8QoP5QGs58apqw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WXl5eEdCUGc2aDY4SEdL
            RHRUNWpxZVB4dW1nd2M5K0xURzZzNXpuU2hRCmxwYjUvSnVqdkFDUXc0anprdURO
            UDVMQlNFYWZXVlc3VGwxZDJVeWo3OGcKLS0tIDFPem9heDZodmEzdXFxek1ZYjY1
            M2FpUkNCcDVPVHFJVjJuakpXSnpGNHcKi4XPtDG/SBBeKc6EXKKX08AMgwoDSkqX
            Wz6UPJ8c/tL8nNx6CIwlC3c1yzfJoRSIKjyhnLCwd8GL4gzTOZNSuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T12:02:01Z"
    mac: ENC[AES256_GCM,data:NwshGIsTvWSEyWiNf6dc5uNbytjk6z/OXx9juGYg7rS62jdj5UyOMZDzpFgv6FBk6Bk7RI4qGkA/oIuXCx8DP4vC3kY+3uGkMJk7ENd4Db/nUQm4oRRuADSpHtRk34K1eJkdS3+4jhzwPq7EnXFcmKqySMn2ccegEUjLqFzdlfQ=,iv:hxhXYnnVfb5KikTTs2DjTxaCo9UU5oxcegOW1Hl5LXI=,tag:nOfBRCjL7VqWGZ1hUaA86A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
