# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-mcp-api-keys
    namespace: traefik
type: Opaque
stringData:
    BRAVE_SEARCH_MCP_API_KEY: ENC[AES256_GCM,data:f7MSWCC6cleV/6bFuGSpeFn12EAm+B5iMNYe/WHDd0YufZFCbI6eo1gx83vKaf7J9sTR3Zg/8dV1ZMcA6oMkmQ==,iv:fjH/FTIkpj0cZev6wspIRA7vtIbUq6Q8Ebp6yawejTs=,tag:uwi9/INLI3NDDA6tRnm9rg==,type:str]
    VM_MCP_API_KEY: ENC[AES256_GCM,data:raxRoJRuRuOibgyncSjnv1Gg2d8jjA0Z310UBaw2DRZIzVWAV/FTuGu0p3w0CWTu8CCsk1U97ULRzrpF7dhqhA==,iv:n7TKGn06AAW2lHJYAiWSlbzL3nD13jKI+JVvaxpzEWk=,tag:t1wBOzPfMXXDCtmnQhnR0Q==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK0d2azFRbFVoTjFaZ2Er
            MndWWlhnNzAzSjc4elpNTTZKMjRlYlBMZ2hNCjZtOGQwWVZ3VThNV1ZJY3BJN1pi
            QktHdXdYUmR5WmJnaGFpV0h6ajZOd28KLS0tIHZVczJvSFVEMVdvQWY3R0Y5RDJn
            T2pIMnlaUzI0dHE4Rytzdkhodi9ZL3cKZp90SkgMyz2sAMDOdaUAFcLN2BZIN7WO
            zrjKcLlsfRuALi5J/S2CJXKaTtAEoLCpBo7KC8gRdbVvxTihd6E9kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T12:57:24Z"
    mac: ENC[AES256_GCM,data:VZA+ouwhSxS14grI0K5rMyrVXv/WFGtPZio137Ilpzijubti1g6XjIjH244PCUV8Ey3n2p1nsTbQhnfb7fru1+17TJkLCQ8tDKXNEt1q6LT3woi8jPOn9lxSIFFM0lYsUJGKa4ovW9rIMu68hrhWk1MJrk1oLvIsQhfQAhPWrsE=,iv:WMJWiZi1LjagZSBrbjFkyGwKcvR2N4R7a88089bfgx8=,tag:yowmsNevRh7vjJTL+Nhybg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
