# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secrets
    namespace: mosquitto
type: Opaque
stringData:
    credentials.txt: ENC[AES256_GCM,data:ShDa2i1cY5sMNZfhJtnBrwd/WBivprnchOAjtpfkohfvHP9a+lb17SdKfZRwsk7nvkSLMA6EpT8y/MMGzbQsEIYQIdNi8LNc2OqY1fsKT6IYPyj2i1cn9KN44f6755/+I2hLsUypi3g/v/Q50ltTgNoDr/thIudKSwffmIPbk5tfYAM9e7b4KgMyKsMSpzXbj+D0HS1bPZgVzi2zTiduITWXyBsAguEY5Ej+iOnnkXMBKAC4PSYCk3FYwl0BrbboNIbM23uVR61FNcBWNSaNS2T4a1uXiJ74+GpMKSvZQHikq5UzciHwJPC0OWdgKPoc2JBKsmgPzoysf5Ix1Lep7mFU0Ungr5AhIJDNs1mxkvGb3T6frbaIbc05FvpTCg55yRZZAeXZnF7sojpTgTPI3HGe3oqND4rVGR0wRCfTUouImaNqKLOwcM4tbt6cUpDHCaNhWhi0S6xDYiHbRyyLt0hJqskhVrV7BMgFF5AB0LYkIoGiLVS1eXpJ,iv:vRw4cj88BiCKZIdZsXgQixhkx/8Ti7EycZn1wXEeFzQ=,tag:Vt/SatKIC+qwBiF9a/69Mg==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJenVZRjBWQ21yVFVzRXdE
            RUJmdU05QlNaa21pYkd3eTBPTUhQK0FkdTBzCk1nMUgwMTBydVpvS29ENklmT1lI
            cklENTF0SXh0M2dONEhOYmpXN0pkU1UKLS0tIHFVUVVRM00wTDk5TlFhQVVkWlBR
            QUFtL3pjUnJjMWZYSFRWUTNFNWZ5Q1kKJnmE+JrELZgaXwmbn92P0AOD3zx3O5JR
            yjzI+7He53SPTlaD2WgB9svUZXKrrt0HYw9Q83TuX/JHNHfu0AVr4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:LmfrnkQt5gSsmi2RThc1XqEEYz8bq+XEScTdqMoqnSqg2fLV0yFtUXgDMzNPhgrFfqP2ZDFkyI1Y7V73VBP0yE2pOt81SWGUP9yY/xk1I6GPi2QyVRjgt0jpRdLrxUsOz4LZrJZChqF+P+aYXsFFgKBZ2J+NYE5rtn2CB55odB8=,iv:+vH5cO5SruHpvZwcvtTtWHr8qoVQRbDInXbpooXDcN8=,tag:XKUDbT/asWqh8AMUVZijzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
