---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs-app-template
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: unifi-values
