# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unifi-secrets
    namespace: unifi
type: Opaque
stringData:
    UOS_UUID: ENC[AES256_GCM,data:U27hp14fSiRgrwD631KqUdK81lNAIkG/3t7n5mD0DVzGAX7w,iv:Kgea7neGYvKaer/dmN437/1L+LnLgAsfL9YEPdLEMjQ=,tag:73cZqShS08j2xe3zyBTZ7g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKKzdVRFNkMWoyZ0tCRmxx
            NU80RUhpRzQ4MlBwR0pkMmZFMkJQbzEyRkM4CmJsRmdWOUNvaW1tY053T2JVWFUz
            TFFaaDRjdWRqdjVaVWd2YzVTS3BSSm8KLS0tIDloWHZyZktJTVZUaHFYWDgyK0Zk
            ZG8yM0VscDkvNUd0dEtaVjdWRW1oSnMKXSngVl5MJUtNR2sEu2hImWCX0f3IVZud
            gEmeA27DQGC84OQ0FhglUlV5jN/1H4LNircK8ceUMynHin6FIFi2Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:LJRUIXejLAAlJpzBNNMb/vxlitZ+78/LHKcMBLb4e53z5d83aIq/WjyoSs56r2lz4XW0bQ+1ifcEUpZICsWAST9YnZQD3Ys+DoCqmnY64Rv9wryys2uNvie2oZT0vZ0siIb/QMZHi0wgKf9G3jLQzkAZsmB5mz80/1YUAm6f1tQ=,iv:JswI6x8qcZMYly/oveIWjAVFxd2e89G+56nDfG4rQUQ=,tag:BkzUL/c0MCFQzTmaViET1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
