---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/autoscaling.k8s.io/verticalpodautoscaler_v1.json
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-frontend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-frontend
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: temporal-frontend
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-history
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-history
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: temporal-history
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 2Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-matching
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-matching
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: temporal-matching
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-worker
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-worker
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: temporal-worker
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-web
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-web
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: temporal-web
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 256Mi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: temporal-admintools
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-admintools
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: admin-tools
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: 1m
          memory: 1Mi
        maxAllowed:
          memory: 256Mi
