# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: storage-encryption-secret
    namespace: rook-ceph
stringData:
    encryptionPassphrase: ENC[AES256_GCM,data:mlbRVGVm8eO6UXoNn/1CbHsrzHwbrMUlqaRxQxYrS9gJDie2tKbeBEy88XaMDk4PPSbd/S1lpYu/a9YcjQxr6A==,iv:qh0drxDiQBUsGkAm91Lpag8vJ4ZAZogMj4sYhe7nFIQ=,tag:++RcJ8zdWW3esXUxqwbDCw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbURickVaR0VaTzhyTnhr
            a054OTJJQmNCMFJ0KzQ5MXh5a3MwK0dGaVg0Cm42UnVmV1paUGtiQWNxY2V5ZVN2
            Y25yckpGaHpyKzRRUzNvRktQTk8rSk0KLS0tIFdNSi9Dc25ONGxrUTg4bS85WVJU
            YmwrSjErU2h6Zk5WWkdZdm1EWSs4QmMKVl94QRFsFlcGxV6L13W/dg5PgYCokaQr
            8IdY7ohJ7Jn09GxeB+oYtOy7rtIhaiD5KCl4hDyuUWCMaAX18iZWNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T13:04:40Z"
    mac: ENC[AES256_GCM,data:4g9A9q3z90prHDXT2/GvMQjIE6hSeHVB5Yucs9Tm/G+OEwnThxjNJ4nuXU5XN6uvZUGv0E/KvwMZiVY48D+qrmmPO3HTwqk+TBn81k/pXSs38BhelufNhRSrm+NaesrpDqv6fYcMmydMdCV7WCJnt4SzKhG7ODV1xMjqh1iZrNY=,iv:ZsEJbyUf8I5eONXusUzmn5WNgdfQ16sNUGxWq9XK8Cw=,tag:5LqvnHfYVrCaZuBR1QHxPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
