# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: storage-encryption-secret
    namespace: rook-ceph
stringData:
    encryptionPassphrase: ENC[AES256_GCM,data:2qrFSJCIQ3l5qacIlLnwKWpGV5BtkCdIQzPWOYyeDy7b/e40RmxbeDm3dvsBd9RfbaKmB0JPhhGNobGezgg9VA==,iv:fwpEoywLJwZ9lIhbIFciDgz8NaEuFSVVxrX6T1mo+9M=,tag:WuzYUuvehEzYaUID3b4pNA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeGpWV0hXYVRRNW9zRnlt
            RUNoOE8zUTlwNVpWZys3WGRsNEVxR3ZubEQwCmsxY0g5Y0NVQTFXWVJCSDFITXQ1
            Wkg5US9qVkZHcFU4eEFzZkRadHBpYnMKLS0tIEFWQ3VVUEpSd281a2VETlU2RWJM
            NTZ6eGp1SFhuTW5oVHk1ZTZJei9TTkkKC015+jWgIHUfD1CCtjeYAMdqExXhL0WI
            77BQ4orkr69folufuLjFDX1HwjqBfo2hhiM91oPWoXNKlIyaLaH+9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T12:10:19Z"
    mac: ENC[AES256_GCM,data:y3lY6zbxOhLUfcYBX2LMsLFCTwkyA8f/j3FHgEE2CO83fVPUWJLmmSWk1TWZg/A5T0hY7rTToRa9GDS96RifASz2ckCIVF0A0qHpr8YlSGdh7o8jylvLbgY4Q3UjbZ0zx7FB8l1Ab/UT9DUqfw7FBcntymXDoyVw902WYCq/JEM=,iv:Tha/lLwSRfG4DMCTthmlTiEVNNfb/Qu56NNExqFrnc8=,tag:snBwePc7D97Za3CE44Dw+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
