# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: storage-encryption-secret
    namespace: rook-ceph
stringData:
    encryptionPassphrase: ENC[AES256_GCM,data:16+/9muRMfRbeB/L/zG8U1x2QCDjTBoo2JG/GE+WnmraEESTm3hMDRD32+29huT+huim2XDggyv6uvDAoqCdUg==,iv:6vEt//IGDQnCP++AwC9F6l/Q1LiO1ZtgIQNO500lOGA=,tag:4ULDoBlvdOYOHMZP0+v5AQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcjJsRW91R0dNbUN4L3Vo
            NGZ2VkFLZzdvZ2NPckx2aDlzVm1udThCN1NRCkVZSXFlWVVFQm93cHcybnNhUEVY
            U3pxbUdWRFMxNUwrS3k0SFN1M2t3bUEKLS0tIGZIYzVualoybmRyb3Uremplc2pO
            VUlCV0wvM1oxWEdXMXNOMFpiUm82L1kKjz1ZbL/K/1a0MO5SWAMrEs4rlYuMLmKe
            XZLr3EWIjJj900Y6VgslAa3GG1DzTWhahOKH1NFVOsUs25Cd2zwO2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T05:29:27Z"
    mac: ENC[AES256_GCM,data:BJ6nb1V+3/APh1F+ExVnKl2iIW+yPJt9jhJm2g2GuiGk7gF38ih5HHI5iKExFXsT55/u3JC+Eky9hcozmwhoT6qWsV9a9evoFDKo15B1zo2LVH+Wi4LolUIDjO/CiBJoWhX4iWs96jl/Z6MxG7g5/AFtIG0M6eDoFFa+JJw5MfA=,iv:aI96xRTh7fSLYmp35Xq8osi3nyw92NUk/SSjaFAwJ0c=,tag:TaCDZDnPAPtn1tTWJp2phA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
