---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./block
  #- ./filesystem
  # - ./object  # STEP 1: Comment out, push, wait for deletion, then go to STEP 2
