# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-backup-secrets
    namespace: vaultwarden
stringData:
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:2VIfceHjXpKB7Rnim4koh2rC3bwngIwOZyKrPpteZjrF3/pITkhtstKU1WZ8v8Qg12eoDy5C5zUFiXoZSM6WWw==,iv:C9Sqf6/aNgxM6NUXE+BUoJKQVRV9lo6bselizLZjzgM=,tag:Kf0LKvDfJq5L48hTqiAvbQ==,type:str]
    TIMESTAMP: ENC[AES256_GCM,data:fifuJg==,iv:f03rbhrqDvn51gBr14+RlofHBklvqwW2bPCxtmbxq7I=,tag:6DiNuVkBs703LyEVT2vJNg==,type:str]
    DELETE_AFTER: ENC[AES256_GCM,data:YQY=,iv:osDVREg+vtzSYoXwhhxcJturIJ/VFbGT3c+BgN6+K+w=,tag:KPJLDsSC4xrDY5l3t11ycQ==,type:str]
    CRON_TIME: ENC[AES256_GCM,data:ETpSXWGNL2Xp,iv:BqKqWxGWm5rBuimJVwcwjVgJzqedJmL7PvW0OBgfTAk=,tag:AkohkGw/ZNw7pGRbaTJJmw==,type:str]
    BACKUP_DIR: ENC[AES256_GCM,data:VTQJWi0oWtM=,iv:4B0c6EtfjDmqRzY7GgF2YNdRhxMo9eEsEhCBTudXxgo=,tag:75rfqF6ZNOQOfAztZP2GKw==,type:str]
    BACKUP_ON_STARTUP: ENC[AES256_GCM,data:RbL07A==,iv:4K8MbFZ8CVXJEim8goV5mWdpDt28V6gCy08q6VikKcg=,tag:UwkNNOz2CbxKyaHWAg3Ntg==,type:str]
    GID: ENC[AES256_GCM,data:zA==,iv:ttd+pYNFPkRnArvRVXYt7Gd6d5Mz4z/Jx9PGOz+ehiE=,tag:1f+cBYTgu5cIDakSrCw6pA==,type:str]
    UID: ENC[AES256_GCM,data:iA==,iv:KeRY9n9iuQsfOlnL2rH1hNs9ShM4KtYTU0Kot/AeVMw=,tag:hk04Mo91e3/xnVOepikunQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRjNhc0tScXRkRlpkMzh6
            d3hRdXh3WFViNlRKTHFBSUlDMXQwb3BLYWlBCmRTbUxCMDJFN0dNeWVLRUVvN3lH
            WEk3SS9vdDkrMWtkYmlVekhsSC9VS0EKLS0tIDBwV2FaYXB6ZnZnVTBkT2tKM3Nh
            VUcwd2pmNU5tNDc2VUZHU2ZQdHdOeTgKMXflaYLxoDOp156upAtjdtd1tC350Xk7
            /SQ3j0cQMtgUZJ6bA9QslPb575KIsIrh9/mT9H1CYL6qrzGvNIa/BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T12:50:41Z"
    mac: ENC[AES256_GCM,data:Ip2SwKVltKN38j4JkVzmxuRZdKQG5XSwyQUM3DfI/gBaK3tjqWa3dJU93nVLZRkJysklYkgK/y7clVNLLYyKOAzlkJT/g4AI9Vx4QwpHVNOvC0UVxdtIbqgSxVE0xLPqLhg6e6MJ5/31BJyuEzVfHc3x6KVNToQsJNN1XVOssBk=,iv:AqEcbbDjuCM897KmT2jEgPyC0m1xK/ThBMlN7ucURIA=,tag:S2PDuCWFCQ97s1kvdhm4IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
