# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_NAME: ENC[AES256_GCM,data:5mBnDesBylMNCEc=,iv:+MzF0jp8aMjIB/62YGvIZajbCYtOrKZxy1aG530WDVY=,tag:ayR1ivl37q6cKrIGVPbTLw==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:othpjKi316Lo0s8i8g==,iv:PYwZexuuDVHrxRSs2USx23jkcs7EKjg4TuXmK3H98EA=,tag:0jJrHBFWBfjq3ptHp7iWpA==,type:str]
    KUBEAPI_VIP: ENC[AES256_GCM,data:ARi905SMEA0OxZjN3Q==,iv:fNaL6WgMQyxnGftADHeo156ZnAmJrwJHu1VceNDzCRE=,tag:ZfV8/suskYsGUtMjleWh6Q==,type:str]
    E2_1_IP4: ENC[AES256_GCM,data:Xep4yiEjtONaXMc4Og==,iv:Try4QQKWscKgYma2yqmPlXHRjiqOrjpB8gNOGdu6FRM=,tag:hayqOhpViJWS5HXOXwjQmg==,type:str]
    E2_2_IP4: ENC[AES256_GCM,data:Qlf8Xu2AuEhvc5woZw==,iv:/zgJxNZG8ssiKWM5cjxMvjegI7ued3okKeUnB3vs81Q=,tag:lEJae2T48S2/tAFno08Wjw==,type:str]
    E2_3_IP4: ENC[AES256_GCM,data:5yoE7NsM/9zxjmlWTg==,iv:vW9LBcmHLDBllbPZnuzzlOm3S3gRodOmDZihnIK5Dkw=,tag:dHq50NzReS58wR3HaSvpAA==,type:str]
    MS_01_1_IP4: ENC[AES256_GCM,data:KkN8lZlQgbWb45QCBw==,iv:PB5x04k9laBfwsw8gdTGUxBrMbL5zr7c/+KNEdeVWFg=,tag:C95wsWWsMpwr0bBRDhvrBQ==,type:str]
    MS_01_2_IP4: ENC[AES256_GCM,data:g0P8KAP0hSu2N8viCg==,iv:7MnVA5UQDstexVdt74dlvSyjiBTlv7sk3nyoXVlBHNs=,tag:ASp6HCBgXicbQIIXythGgw==,type:str]
    MS_01_3_IP4: ENC[AES256_GCM,data:ZzhkhE8OKqC0srk+BA==,iv:OTo0V49fkhwcqWpEqibg46VjUOqSzFYmz2Lj4B9kUeE=,tag:tDAVvn2qSAZJ9C/KILzulw==,type:str]
    GATEWAY_IP4: ENC[AES256_GCM,data:WWjPNL5KofKfmtB8,iv:MHQBkdMGRlaVNowHSraIliu1SSwhOXlrRo0HOIL0tOc=,tag:4mZw1ThICgpzE9+EkeTuIQ==,type:str]
    CLUSTER_NODE_CIDR_IP4: ENC[AES256_GCM,data:eLMxxUwy+DyD7wUZGmoE,iv:yF+zMop3s0yuog6n59iDCsDbjx2Ko+lBaZ2mNOfnB/8=,tag:b0jD8ZrwZOKC2jkBUobdvQ==,type:str]
    CLUSTER_POD_CIDR_IP4: ENC[AES256_GCM,data:jd60ctpf3cE68TH/QQ==,iv:XOxHYeh1of6GH4RT/ouJEZIhza3F5xLz0FVboLhS15M=,tag:uUnYixGiwjEy21cJLxZLcQ==,type:str]
    CLUSTER_SVC_CIDR_IP4: ENC[AES256_GCM,data:+afwnK+XVj1KYnpu,iv:fbLWIfZX8ZPb+J14dygnz7fRFrkJ/0g7uaHeXrGEvvw=,tag:0YM0MeL5JoL8WObd1hqlIg==,type:str]
    CLUSTER_LB_CIDR_START_IP4: ENC[AES256_GCM,data:Y/Mu41d61BUsSgjfYg==,iv:sBVAjyNMK67kbenPPKI5MhDkMfOZDbRNh5sRPiWFxJg=,tag:I31caB6WxUoskI9xMMBmLw==,type:str]
    CLUSTER_LB_CIDR_STOP_IP4: ENC[AES256_GCM,data:31vprsUk9olG936G7r4=,iv:254/p3muzSmWBJiR9OaiXL//sEHyxaEjPjoZrYAaj7o=,tag:T+9GPJ4+07FkoIHxmtgYyA==,type:str]
    KUBELET_CSR_APPROVER_REGEX: ENC[AES256_GCM,data:a1JTxoQhKAL4wiWmnDn3P0uff98EdkiV,iv:P9h53BOk6AGBGQ7h1pkLMBR+/hLGHeeprGGN0xuaYtk=,tag:Uk9lwGTH1Ccp2lT3TVFAhg==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:EgCdG9yrsloA6g==,iv:TF5siunymDjNhP6ChjMd+74vy5RGD+lsnopH6wOqCec=,tag:plVDEUc5rSCqdRATg+CoWA==,type:str]
    LAN_CIDR_IP4: ENC[AES256_GCM,data:9R2ItA5HHQ+csF1T91Q=,iv:O5QeeUZxKaGjlMG95cwxQcOEHKUGIGGcOjYizqEf1yc=,tag:VNiknZnWwlVAcJx9lkFtlA==,type:str]
    TELEPORT_CIDR_IP4: ENC[AES256_GCM,data:+f77VYr2gALj4/ejzpA=,iv:ZHyq/s1tkNupFT7frWQzLM/QLo4nxi0KEIEA6uT6jWA=,tag:qlCxHyD77S9KeiY0i/apCQ==,type:str]
    VPN_CIDR_IP4: ENC[AES256_GCM,data:v9hiyf567TX7dKllvMQ=,iv:r5OVsi6/LNak7h2fvMZkERL/1/RjsyJjz6oncg7/wlk=,tag:/rmUD0rakLaWnKsB7fWlyA==,type:str]
    DEVCONTAINER_CIDR_IP4: ENC[AES256_GCM,data:HAgXSv52pBAH9RNLXw==,iv:JFR4T3oAXVnCZw4iynzr1bNNHhfKFLEuIIAQlWjlIZI=,tag:nUS31fnF/U7Fgw+DQJ8TMA==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:R2zvCmnBJb2KcFpw9rH5Lg==,iv:xIogzU1j0f8NWeQo5mREL0FdRndYIGf5SO+zbbeGjqI=,tag:2jaMn8iCkEq0xwKiux5+Zg==,type:str]
    MY_AUTHENTIK_USER_EMAIL: ENC[AES256_GCM,data:e3MPNge5AR51pTJHIDbruB4GrQ==,iv:UszYDfxaduOPgO0UGEKeoOmT9mNaZfahpioyXZD78Cs=,tag:7Ks3Tox+urKAnjhCJt6HWg==,type:str]
    ZEROSSL_EAB_KID: ENC[AES256_GCM,data:Mir819EoCxEyIM+jPW2XowQxUL7+rw==,iv:mqdzwZ+/oiykIeTNUqfEOOTxgrhpp46TCcIoJyJLdpU=,tag:QrMy6C0113fkf3aoqGOTCQ==,type:str]
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:GD421XDsMC4bR2GcaP8FUvyD,iv:yrrTrIQh+prh/+3JJpITiYlL6Sn4xit4NpXWd2xNQvE=,tag:k+yxNz43EmTYOxsO0Y6keA==,type:str]
    DNS_SERVER_SECONDARY_DOMAIN: ENC[AES256_GCM,data:9+M0BWt0l+14gidCWoQlYFCZMLlQ7jDCUFDThA==,iv:9FhoaOhC9lolLGdFXgWMHke+UHCbfx+mb3Jz1OfRuVU=,tag:SbtUeJDYxg8TPQyTZQ4iCg==,type:str]
    TECHNITIUM_IP4: ENC[AES256_GCM,data:ooRGGUtGufzHnImefA==,iv:98uGuYlXVoqQqKh20p8p7mL69xK9hkkfEKF4B2hW+is=,tag:1A+qRXCS2cvAHXR+KFBu5A==,type:str]
    TECHNITIUM_SECONDARY_IP4: ENC[AES256_GCM,data:7sk7BKCp6MDX2prGRw==,iv:BJAa3P5Fg8y2X7rdRiAXq5vygV1hkQX/jBSkBs6f2Cs=,tag:olk/CS2PG4fyvc26T5fRow==,type:str]
    NTP_IP4: ENC[AES256_GCM,data:5+aQ8VNaUsSv7qrLUQ==,iv:ye1yUS6gjydcoIO8p91Vv0eNkOFuHwaH8sjaY2siN2s=,tag:QCWouHAreeFiBDHe0Rq2uA==,type:str]
    BEDROCK_CONNECT_IP4: ENC[AES256_GCM,data:72FDJrrMp41W5x083w==,iv:Bk9ovi2VGBkiAsz/JWePFDWgEAgbVNqfozrSvYiIsio=,tag:BUALQQNABA0dWzMJ/6gC9A==,type:str]
    MINECRAFT_BEDROCK_1_IP4: ENC[AES256_GCM,data:VbW5nw4qZQLWCNj1xA==,iv:piKp7ytaTFlrwIojEgisk3x84Fmjhz6C0VWedD/+Rgc=,tag:ce1Pyjg+WLBACdimnKraMA==,type:str]
    MINECRAFT_BEDROCK_2_IP4: ENC[AES256_GCM,data:C3Yh5K/3tnGns5tB+Q==,iv:ouvkNiby4Xo0Yg3uRA1T8NACT8+oqON1vvCe69o89Eg=,tag:H38irLSR4vvlnu5+MTaRRA==,type:str]
    MOSQUITTO_IP4: ENC[AES256_GCM,data:U0bfoWHjCMWoMhRqlg==,iv:2DQ5fcG0SILCbInS8+7jVtmMLs6NSG+CV1yjnWu4Hbg=,tag:1+nyneL8SHXLen1u92MS7A==,type:str]
    MINECRAFT_BEDROCK_3_IP4: ENC[AES256_GCM,data:Cx392EOXfTxsvs88ww==,iv:f6URNASW5yM99l93euXgeki4eiPnIjotRyBQ+JPRyI4=,tag:kvp3r7uKVYyw6mobMFz+8w==,type:str]
    NUT_IP4: ENC[AES256_GCM,data:tcsrmVgAU1QhYJV7wA==,iv:+rp34C6a/SRExQfDKg6IbbfMY6DPOh/IdMWB/3AG3xk=,tag:axELMm2xC6jGbIAvOFOZiQ==,type:str]
    CRAFTY_CONTROLLER_IP4: ENC[AES256_GCM,data:vBp9bKb1Nd5OMv/c2g==,iv:y6dbYDehgw09H001AXP88GkAAPIQ6+9orIovDfQ/UH4=,tag:alVB9RnQk5JbsLKAng6i9g==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNFdSWGp1K05wOGcwS2Ur
            cU5DUXpiWDVyV1BoNlhSYzdGQTBnVDBIY3hFCjFPbFk2NS9GYk9BbmhYNFF2cDdm
            THA4WGFhRUNDc3laZzBnVVd2WlhyV3cKLS0tIEVGakh2NXNwRnBEUjYzbEkwMktr
            bUlRaGxLQWVnZmFSQ3dXRnp3Mk9yOHMK+4JreBaathrClqWu/6D6zFim6pUzpV45
            U4lHMkSoA0O7zAhsVejDEz/32aprNQ2JUswPvxKw7gNtE2ypOPtWew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T12:23:45Z"
    mac: ENC[AES256_GCM,data:JkMvRONSfqB02VHRje/A9dCfCLmym1x93gK2KDi6N8AvU10FZa6hCCejEyJ9ENWor3axfuDB9E+za45MCdD2SMmV4N2x+EOyiKgLKlBeXvxFHub7utiTNSLpxObMLyhi6N3W4EPAdqweVQX5gjEgs6IfnGFnAsqLYK53I/Rmz1Y=,iv:7357S+ahixPoXHDu+SmHII9w2LDUmx8EVo/UR3Jna68=,tag:Jqu/AYF8Kg6cvLDfJLTU0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
