---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.1/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Melbourne"
  CLUSTER_ISSUER: "zerossl-production" # letsencrypt-staging | letsencrypt-production | zerossl-production
