# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:caNNkZk2kuT8PGJAGg==,iv:6jNOQM+StWxhLcnaDDLlYHdDLbfm/WUOhsYqdXRPVW8=,tag:2DVEL/Sw/z+Xmi9nHft+Ig==,type:str]
    CLUSTER_SVC_NETS_IP4: ENC[AES256_GCM,data:vtQpvbv0aUDODOvM,iv:mqYggvkkm/lWGUD1vd70TKql1KknhPT4/r2QaHD9L/o=,tag:dmvFF1rAawpP7k7wzHgK2A==,type:str]
    CLUSTER_SVC_NETS_IP6: ENC[AES256_GCM,data:Z5I4hzlHKLf4SgAgnQ==,iv:Xfu9/gbaTYi4oFSOCsn46E8LYzMcGZbJnjfSobcUyP0=,tag:xSowNt7FEtbyeEnDejKC6g==,type:str]
    CLUSTER_POD_NETS_IP4: ENC[AES256_GCM,data:5HmDQF76K0T5hN1/AQ==,iv:NJwv+ACh8TG1uK5osQXa9vi/MI/ynv/X8+PBnS3/Rs8=,tag:gfUp85auSUelfUknPu9Jog==,type:str]
    CLUSTER_POD_NETS_IP6: ENC[AES256_GCM,data:dciMug+2uOp7S0rYJg==,iv:+jppb7bBjSB6RiLIYd0IMGF6qaHiZDHF6rmLLkd8zeo=,tag:jY8AJi3NAsktO+JTVFB0aQ==,type:str]
    GATEWAY_IP6: ENC[AES256_GCM,data:NfbrkT+C/zJVOWpx8ApOVkVB/dEM,iv:iQw44qyH0jFEh1ulx+8ImI17OWXTkTD9kATRzU51GZE=,tag:O84XUN2yyTDgk0tdSlfqhw==,type:str]
    NATIVE_ROUTING_CIDR_IP4: ENC[AES256_GCM,data:b6tql1jepaH5gHGTiqsq,iv:xnY9t0qXLZZ4FBjrq5zx38AwR577MpYnO2mJHy2pgD8=,tag:MJlQJHuG8bq50pvqMMfi6g==,type:str]
    NATIVE_ROUTING_CIDR_IP6: ENC[AES256_GCM,data:I8y/HBfAgvV4gozr5mOHoTyOzyx1JAA=,iv:aFq0pS1c1SpdtsE505R7zV25apLWhcSgkGf0arqOnfw=,tag:66qN2x2qMgM3d9p1Le6cOQ==,type:str]
    KUBEAPI_VIP_IP: ENC[AES256_GCM,data:gHppspMnNV/TymmyNQ==,iv:0dONA/tDFw8GUIR/CCJ0+6UxO9shEM/kWBDGkIthbqs=,tag:1S9HDi5cdntI2UdbIVN8SA==,type:str]
    DOMAIN_NAME_KUBEAPI: ENC[AES256_GCM,data:MR4ACoDi80P86bo9l5oSom1/,iv:1oVm/hDRP+6etfTFf5NOJU78rWQcNA0oL4jVT+VeoVA=,tag:ymLtW9QaVttz48R65L0A5g==,type:str]
    GATEWAY_IP4: ENC[AES256_GCM,data:JQCkbQTUnSPNKS0Z,iv:XjEuiCR4iAKMYLNLaHkF/vmvfn0o976H3zaL29PfTig=,tag:dU1OWgQ5w16h6ulH1JtNnA==,type:str]
    LAN_SUBNET: ENC[AES256_GCM,data:2985kKtztxouGU4EJaZB,iv:ZsyJdYsJ+wDAbMyOYKJvXM6MsrxtZhjx5gY2zH4eFKg=,tag:AOAy6lGKMvyFpV4kmTduTA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:OywC8GNY+hPPEqM=,iv:47BRXZxvItqy+oyuKfO2B23Ox1BT7SaOF/is5WW0QXA=,tag:JD92brJMrIb8j9b5IqN72g==,type:str]
    C1_HOST: ENC[AES256_GCM,data:CRz8ShcnaVTH,iv:arQxNyNntt0LAKTwdEsrnkfg8v07qnjRxA2eq9/FKJo=,tag:/mc0nxuNiOmVEoMyjKd2bQ==,type:str]
    C1_IP4: ENC[AES256_GCM,data:X0BC68s79pKIz/2ENA==,iv:44qsb3nY8s+a8PRi3hYtnfm1qkmyjnvFypiLyVAUxvE=,tag:U3gaUMG8a2pIBld3PzONsg==,type:str]
    C1_IP6: ENC[AES256_GCM,data:vduUObZ3ker0imJOGlVkXWZBhkKSW+UL,iv:enABJKrEu67e8Jlubpk5gSxF9UYWVgLo2oHVkSVvlKk=,tag:517IAFKn9vs4JzvNnycUUg==,type:str]
    C2_HOST: ENC[AES256_GCM,data:nPl1B2YkFylH,iv:EhVrR/ybT2wI3tkOVk/f58u9FdD3qW6w5kuDRAGXKaI=,tag:gG7uHEg2Yiv7dXth0tcTNw==,type:str]
    C2_IP4: ENC[AES256_GCM,data:PZJKQWoJzNW+t4D1/w==,iv:tVMXontODOw5RBb2TEOqq0F+7f6Y9rpcJp5Qen/V7/M=,tag:8ntQOY3sXZmZOeVsgIKAXw==,type:str]
    C2_IP6: ENC[AES256_GCM,data:Ipun6jAmTRoQk13fxIHW7NzNCx2Y4J1G,iv:2U2tSOMISxXRA5aecJZjEMkQcY0X+mhUQG6yzgn+3JY=,tag:2iRfdgbJ1XNLYOQIjz6hmQ==,type:str]
    C3_HOST: ENC[AES256_GCM,data:KJJ7FdawL/IL,iv:A9erKVQbZX5VmnMylaxHT+ZkzgI7Q1UUxZGgouX5Bf8=,tag:NoSekwKW5KkFOyJwuYXEew==,type:str]
    C3_IP4: ENC[AES256_GCM,data:NpTGBz8owszBfMoZdA==,iv:9f5/CBcj41FP/hOvHdl6NJfT9RAV/a0ehUDsJWYiQ1U=,tag:+VRR/oYPv4GKZax5TufMIQ==,type:str]
    C3_IP6: ENC[AES256_GCM,data:kFw/IOb/aKC7Oak0yAtJp8knVUC/eZEP,iv:cDq8KxYNuPxO3wXN+k5sp4CN6XXZAKDUg5OzQrjAjAA=,tag:5dF3cjsW9c57NQ9ZBeU0dQ==,type:str]
    W1_HOST: ENC[AES256_GCM,data:TriO9KJhOe9ukpvXqg==,iv:uwTYMt1lL5qJk3p9MLl9Ok1KBegkI6lE2Wcw0kk1N1k=,tag:rGoioDYszO6T2Ac6sD/RjA==,type:str]
    W1_IP4: ENC[AES256_GCM,data:TxJI9qoydRXpKp0+zA==,iv:wS1agMJ3QkwuwGdtNQJEEC2M35tgftJFMAXJNDCBXls=,tag:AZ7nCEyUwTh9UPZhwukc2w==,type:str]
    W1_IP6: ENC[AES256_GCM,data:DCLdquNsl495kNu2WCyKV/cEcTjv6nsq,iv:qNbVi5TbyzTSufVndE7pGvtPi7G8YgFfqCdNgx4uSwk=,tag:cSwXbNGM409lfB27/D/prQ==,type:str]
    W2_HOST: ENC[AES256_GCM,data:MrqAZ7lsq96CcttnBg==,iv:hvKmp+thVNk9dmuxmOoRhj0bibiNnibplSBY2ljSw/Y=,tag:vF803aOn71AP3fWr7fzzWg==,type:str]
    W2_IP4: ENC[AES256_GCM,data:P8ldM/UcJ5QJMUS1jQ==,iv:PDCzt39Gmfqovh/szww+b2ATSOVvqeMeihSJuG9nSgI=,tag:O3zM31Qd/K7JKoLv9UpX5g==,type:str]
    W2_IP6: ENC[AES256_GCM,data:PUVTZqwnn3wiAWXXjDp5BY43GJTmNg5C,iv:AU3Q3lI7+YCoA5B518RWayuYyuWIBW9twX5SbrY3Qo4=,tag:ntfNJT0OZl1P2YFEQcl2xg==,type:str]
    DEFAULT_DOMAIN: ENC[AES256_GCM,data:mXHlf27E36L8og==,iv:FiPXMVtfeZ4mg+mk2aCtc4W2x2s2AlNKFqQjijLdXZI=,tag:URJJC3i3EGUUIg4gP3WvVw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:IPWHklgNWZ/e4Q==,iv:2seYu3GHbDk4qsUtWqORcIxSWk/hGbdtndBwx+CQdLQ=,tag:ldWzVFgFeC41Nwm2CWiFfg==,type:str]
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:GMy9wVjbpXQ8ESFPEcyfPhx9,iv:NtZLaT/c1Foo3h00WS8Z6HFj9yMWudKFlNi6+AmSEuk=,tag:VcWRH6x6DJ0fhWD/PHBNqg==,type:str]
    NETWORK_LB_CIDR_IP4: ENC[AES256_GCM,data:q/uJNjaMCidtmA6F,iv:NxHxOZx0y4rNlkzfRp4zvyfHah3wmzQErDCls7gORy8=,tag:gztY1UojuTDm1ojNzfHnig==,type:str]
    NETWORK_LB_CIDR_IP6: ENC[AES256_GCM,data:38r4GLHZP/sRrK62DZJy0w0p69ColHmoEw==,iv:k3TNMH0MxMEynhstpY8YsTzDwg7gfwcIJah6bVBrinw=,tag:9zkwR/CG7kKp7sVDSo09TQ==,type:str]
    LB_IP4_KUBEAPI: ENC[AES256_GCM,data:RA3wJFDjAB7+jxo=,iv:UugY5eR9r5F/NC/qgO+H8EXzSOVlXOPckg4hij513OI=,tag:z4HPBwV9QHaxewzPcd0NyQ==,type:str]
    LB_IP6_KUBEAPI: ENC[AES256_GCM,data:DP2q5a97ojD5fwvm9btPCCtAYRG2TBA=,iv:B4ZxwTJ7grg9a/NtnQ2ndzewj3hx3OxQKO83QWMt2Wc=,tag:27DmRkWd4eE6Jop72ZPX9g==,type:str]
    LB_IP4_TRAEFIK: ENC[AES256_GCM,data:28ai//8ERJ7H2p0=,iv:Fcy9cOGEZ4CcIN7TQjOwZg0lpcIKU2B5D2A6Cv6XKCk=,tag:/FAqXGrqkIAW6lmHwWb/ew==,type:str]
    LB_IP6_TRAEFIK: ENC[AES256_GCM,data:KhP2Z80ZU4UMYgkWzL06XfSN5OujHyg=,iv:Cq+m/LHIeG7FqQacJvy3Gf37cWKAkaERNXFBf049OmE=,tag:8P8mv8xQRu+1APiTMC7lTQ==,type:str]
    LB_IP4_TECHNITIUM: ENC[AES256_GCM,data:2nyXHDAbWYzqxc4=,iv:4+EFwtsK203p0jZV7MqlFyFMY5U250fuPeKh4+RezQA=,tag:uKXEoM4KcRohNQH8zoCHoA==,type:str]
    LB_IP6_TECHNITIUM: ENC[AES256_GCM,data:alEcyJ3yR0oUlv4luO6u2a3LvZMG0fw=,iv:F9cUn6iPaCng+JOAOxvkxyyiz1KYwXl2A7CM9j2cO4M=,tag:8KuUgz3NwWv/YueHXHDkrg==,type:str]
    LB_IP4_MINECRAFT_BEDROCK_1: ENC[AES256_GCM,data:1dzacCn3ItifwBA=,iv:n00RQJII1sUxIAc/62YfAlbXOzw8OTFoRSixIXoH/Nc=,tag:g/coc5VJcvzbQY6Ud3y4jw==,type:str]
    LB_IP6_MINECRAFT_BEDROCK_1: ENC[AES256_GCM,data:g+yjbxY7ZBlwRMZnSOpkv7P1pCf6qcM=,iv:ZI6zsoLxRneheK0gVu+oszze85CKByZKK5tB+eHoiPU=,tag:ITtVH0oaik+vUZ3QwJebIQ==,type:str]
    LB_IP4_MINECRAFT_BEDROCK_2: ENC[AES256_GCM,data:K7LQJ4+fBcRpw8M=,iv:98RbrWTFztA/XE7qZEy4Cn2v2oqgD0zcXR0v1aKSHDE=,tag:pwvGadnuFTx2bO36S/+QPQ==,type:str]
    LB_IP6_MINECRAFT_BEDROCK_2: ENC[AES256_GCM,data:YFZkshb1jMTILxj+ACr/Wvh+ZDrkatw=,iv:WJBHIhh/yP0B5Cyg/hvH8sx7XYF1mlZR2Wt96cWAChU=,tag:1yhRtH48tWkaUMGvCYyArg==,type:str]
    LB_IP4_BEDROCK_CONNECT: ENC[AES256_GCM,data:wu7pn86lEZOkKDU=,iv:GTwt1TgBtCot1zUwAqfgJaUWW0nb9diTamR+9dvP8c8=,tag:RAPVT0A+PH5Xp9JJvSEUQg==,type:str]
    LB_IP6_BEDROCK_CONNECT: ENC[AES256_GCM,data:O2u/87JfW3YUCQjd4vmN8FBqHuJM6rI=,iv:rTgV4uQWeDo++UluHTm9oR0TmRBjtXwVGsAMgWG1nXw=,tag:9ZKPpbAuqeMlN0kux0A9Gw==,type:str]
    KUBELET_CSR_APPROVER_REGEX: ENC[AES256_GCM,data:UTjiVh0Aiw4PT3BmyZKTlJgzsDG4fBtmqhrZbccLyByDm1xQWvwHKlS4lg==,iv:czhErvMDF2/KYEynf8LgzLOucsQUWgFmg1yLHdx0/Jg=,tag:7O8LNiIBOS/evH0bmEHceg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tC3HpyCI6bKCqbok4OQeAA==,iv:4bSWz9juckCvwFsJzJer+dfEdeFhF376RQ8QnQAmJVs=,tag:+gjGQBHgTDH+87kyV3RfRQ==,type:str]
    GRAFANA_DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:z1sHM19LyoOMijFh117q683/RjW0dp6tSKCeggz+QFGghERYReFTdrrFyCwGoVN0101lx2APXme75S4mJ7qeuA==,iv:45etSSZ4SQVH2/ug7L0yD7DCOGQQGX7EGOBngDz/jgM=,tag:iiZuywzJ7tqpwdilIL/KOg==,type:str]
    ZEROSSL_EAB_KID: ENC[AES256_GCM,data:+KCKaI8bY0gh6tXDVDGagd9hRPMOPg==,iv:gtJ4bgOb4P9cRspcR+xdVoQ49u93Ul1CBn8A8+gH6Zw=,tag:4BVTTWoNdkJM5UnGTU2o2w==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYlZYOHlyTFN2UnVsV2Q4
            QURzemJRd3V0NWhpVDYxOXZ1dks4OTRtLzJnClBMQS8vVXZBQS9GVUpWNE9CenM3
            ZFEyaUtwckpqQjJ4bXF4OXRhTUxMajQKLS0tIGl4QklQTXNUUDhjUGwzcXNvVGQ0
            a1hIUFNSS0wzOUJqWkUvaFNnTlVKMmsKgEJNTJpCEeZhHzeUW3Dm7RdWays87JWU
            EutRqvWlYFG5gvmfrJFRUizOsc30TIjuQJ26OkQC+y+7mnOYusbmQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T09:34:15Z"
    mac: ENC[AES256_GCM,data:y5qYarL86aC5rbwI4L5vFJQSCv+Ds7fwy14C6G5/2cU01BJXd3oZl6E/YVqUlGXqmvhoX6v1FIU2bE1mwDIS2WmhTW5ADoT5X/rFVLs6umLoCJjBvT1/20oGW8VFxwokhDBl86SzY+rVgAF7/fB0fqFd9AY/xQPy8cDD1ljItSY=,iv:yTRG8C6nKL6dB6H/kg/04av2wMnKesedBrUYZ31UMzE=,tag:2VL8QJlh5mAMY67pl0G+Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
