# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:m3te5pvZZqr+qu4jEg==,iv:I8YKr4HfwpjdeHT733wvHj6LaO9a6Kb9fgoxi38Lg+o=,tag:m0WJ0jzhYYrL2ONuYh0zPg==,type:str]
    CLUSTER_SVC_NETS_IP4: ENC[AES256_GCM,data:IYxzwbqQzPQi0EM3,iv:4bGpgzYbtZXJ3wozAu+E+RIo65gifSr858WVGVwtgjw=,tag:idUP0+NwKoUnyTvmicl4JA==,type:str]
    CLUSTER_SVC_NETS_IP6: ENC[AES256_GCM,data:Q2uIsLI96OFqf7g6Gw==,iv:0ByTXmk6WAGNoGFGhwi7Fbs8OppopcEGE2W0ovID6sw=,tag:qQCqxmGv7bniw0rE0zj5Fg==,type:str]
    CLUSTER_POD_NETS_IP4: ENC[AES256_GCM,data:FQAbXpV49I2TPZm4cw==,iv:uqTwzqipOpGvSS3piCI0Ac8aT3aiyhoT88/GbxOZUGc=,tag:3nnLx9nQuD0CxDoUSS0TBA==,type:str]
    CLUSTER_POD_NETS_IP6: ENC[AES256_GCM,data:i+hWnm5YnXf6cbV9lA==,iv:Dvi/xd9zwe2/ZWOBOkCJLTZfk2ZCIvoUoN/eYZzHHgA=,tag:UxKSnd4/SukPaJb9u3Y+hw==,type:str]
    GATEWAY_IP6: ENC[AES256_GCM,data:0n/zfWWZaUvqDVI8GJx7v4PUyb/g,iv:27O15a/bhrucRFYxriNHfk780OG0Fl59+uzQOORRsR8=,tag:Ds90tS1z3Im5f/VxNukRMQ==,type:str]
    NATIVE_ROUTING_CIDR_IP4: ENC[AES256_GCM,data:WyYP1zjKdS0hnp6Fgoh1,iv:+Nvus2AgD3aUEpzhmvBwBcRk/A1xKdqiPlh8EFXzDEk=,tag:+mKg5lRZfQ7NksH4mFVbQA==,type:str]
    NATIVE_ROUTING_CIDR_IP6: ENC[AES256_GCM,data:axA5WHH0nL65SkNqUD/CRq2FAE+rzjg=,iv:mNJICP+bdHc9vCYRh5gbGtqmYfHPTcG/0iqjW5LQNaw=,tag:94GPR4sQYaBWJBNDeSyxQA==,type:str]
    KUBEAPI_VIP_IP: ENC[AES256_GCM,data:Sa2yeushhhJTPbUFUw==,iv:O6kMhR1bRrHoscAu9p2zYRSQ+Pj9jB2J8ufJg8sXj1Y=,tag:vTj3DhFhV7HgFp7j4uRF0w==,type:str]
    DOMAIN_NAME_KUBEAPI: ENC[AES256_GCM,data:xid/HZqsXzAwhssd6SuL+3Dm,iv:D/SA1qO+0rN5P+GxxPf9Azo/zUYU2IeX6naE7i7MyeI=,tag:pVvsaL8vneYTKsPbnQULuQ==,type:str]
    GATEWAY_IP4: ENC[AES256_GCM,data:k2bDZgKhxlsbqu26,iv:igRVT+6hBJcynaTMmm4quaL0HiRgojeiIxxO6XL/P24=,tag:kjQCq52EKAA/tulROnGC/A==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:Cyi+t59CpNp7LAg=,iv:Akk7WHc02153HIXhChllCxVkc8YAHm0iCWTunYuW6no=,tag:odsvAZ6cjrPvNDv9gtMwsA==,type:str]
    C1_HOST: ENC[AES256_GCM,data:uEB4bgXTMMlC,iv:3zYPbk7ztH8EydDKZ9m9qfc2T38DTq1d6Q765axPnIw=,tag:rS1aAm3o0jc2sBjQP83zYg==,type:str]
    C1_IP4: ENC[AES256_GCM,data:20VYm5bHLhGjg848XA==,iv:74dPqDX5IZXo0s5wAv8XNCMdXzBs3Hr6t79AtEbZgF0=,tag:bUMo0fQPfixRutMpN8244g==,type:str]
    C1_IP6: ENC[AES256_GCM,data:X0YcmkeAHOFqt9JhJKdQSP8QqviDpXVR,iv:fw3WAKwYqhd5SD9xCzlwWTp46impfDiuTi+wk8VxX6Y=,tag:pcgiL7Scyy16IC+sJYwxqQ==,type:str]
    C2_HOST: ENC[AES256_GCM,data:oyarGKc0s2R1,iv:WjLQg9jDBAyeg3O+Bq/wXgbspp88BgsgsqNgGGNkAg4=,tag:2NQSxwRD/8+GepmtnKxuGg==,type:str]
    C2_IP4: ENC[AES256_GCM,data:Ks29AGAf1253Albgew==,iv:Gviz8E2lymyU0Uv2o2LrPWED6Nsya8rhGHAqXSIYKkk=,tag:4JIBDGMIeMpNVs8FSb8afg==,type:str]
    C2_IP6: ENC[AES256_GCM,data:FMEcdxKgvmqVJRmoK4nmp+Axhm4p3rWi,iv:YdSUGpnDNcyAC0WmY6tSeZcvyj0Tmb/X8OF26VBCPN0=,tag:RL1wHPEodqjphVRIsF1MZw==,type:str]
    C3_HOST: ENC[AES256_GCM,data:ohCFLyS7lI0G,iv:bXn8AZMrq/U8RJj7vNAYq23wA4Gadp4obRTi2wvOxNM=,tag:SUU421Vk49x+5yzyU2Ogag==,type:str]
    C3_IP4: ENC[AES256_GCM,data:b7WsfKkMZDPo0BwKlQ==,iv:Ngau6c9hvySwA7iVz8nigX937O59InMB/ff0UN1E+gQ=,tag:bUpNEbHIYvk5wlXZhpx2WQ==,type:str]
    C3_IP6: ENC[AES256_GCM,data:ErdoQDLIuZdHoexQlDjW+/4MtuWfAtsa,iv:XMvY6HMzHdQ3vMO7fzbDfL6cIWiShGj8NbMNJ/bMtYA=,tag:vRQoIlC89qUNJIvz0WRpFA==,type:str]
    W1_HOST: ENC[AES256_GCM,data:Ch5X/iQ4J7/Ku3Gc3w==,iv:XaDRvkv4DNyb0KFqaksg2+ZmHv+LzRdpZ7CU0ff+v2E=,tag:LMmHkwt+vpMxe15uBzVdPQ==,type:str]
    W1_IP4: ENC[AES256_GCM,data:go2IvnlyAdDZF7urgA==,iv:Jldu53d4C7yYsLf6wugfUyDVazYADgQKNG3p1VTbWTg=,tag:uDuU6v7g+U8ny0cWF5Sx9Q==,type:str]
    W1_IP6: ENC[AES256_GCM,data:kPh02xtW5fZ9FXRZ7X3K307/Smp/7PnX,iv:UZj8xnpzcDriz48xgEH/EK3IW/n/ALv/4TrRnTAD3Yo=,tag:UJRFE6DCbzDMVjbPj7XZ8Q==,type:str]
    W2_HOST: ENC[AES256_GCM,data:WPQOxxkOdj7YhmYXXg==,iv:6xPdf4TMS4FMrZvO49in8GcNsxh+x40eQpF+0bGWIyk=,tag:RreCYdbNONjO9pPvRHMYKQ==,type:str]
    W2_IP4: ENC[AES256_GCM,data:dDSm9StdYUvOe8bWhw==,iv:e57uiLUjAH7tazGFtMh18yZoi4R9p6pDBT9dR98riHA=,tag:2lIUMXNekxM28Q8qPLqiog==,type:str]
    W2_IP6: ENC[AES256_GCM,data:nIDPQX8v6OOrfOm6Cq0v0NM1Hzr2d59U,iv:eXQeAcVJV06KmJLd8880kT/HcUTAXO20EYV+FxeFIzk=,tag:fWE4J8eZW3mc+DCz09Cu3w==,type:str]
    DEFAULT_DOMAIN: ENC[AES256_GCM,data:/cOgF7dv+Itrqw==,iv:AGjC0V/PxVgOF5E89o1p3dhwcc7sNszKw+Tz2VMNW5A=,tag:r95SGm+FFDw6175wl0NerQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:cvLzUhXWPScg8Q==,iv:RrcwgU8GmTzS8wvRgSn6VlasKNtLJHCeUausTo/TFXU=,tag:Lgf4or2hanuTR/+MnEi8cA==,type:str]
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:FHsfLcrFLPjh06TCV2kX++JX,iv:xapBk2xIYYiTD+jFO9WYS31vLAag+M7qKvnwf/CjdDg=,tag:Ac9dw5OxHvtKagv28+NUug==,type:str]
    NETWORK_LB_CIDR_IP4: ENC[AES256_GCM,data:Vmz4akpyNvlQ9pod,iv:yKqTzPA2obhq8WWurNQsD1bKcR84TFyts1wc0PtR/g4=,tag:L/2Tg7mLsRwlQkP9uthlsg==,type:str]
    NETWORK_LB_CIDR_IP6: ENC[AES256_GCM,data:47tioU9C3PUHrF4AhtafZfZsWaY67szyHQ==,iv:+Rl+TpVgSsn0BQnDvNRGUFNx513fZY2ZIlf0Q4zTP4I=,tag:UiCYESMMu30eN8iteF/Caw==,type:str]
    LB_IP4_KUBEAPI: ENC[AES256_GCM,data:ZIvovv17ArEDbeA=,iv:RTJmB4DucBcPqecDpixiKF1SY6edw9uq4TNQAbb+mMs=,tag:jRKgMkDg+5oVYYgoKttlcg==,type:str]
    LB_IP6_KUBEAPI: ENC[AES256_GCM,data:45/qfvEVKEap9fk/bMNv8LK0qrrrMMA=,iv:BQHjxL/wM2S/9EMWeMrC4q3bq6YQqv2WzxCjBK8pcBM=,tag:Gwfz9zOtKAbUxgcBh9fGnw==,type:str]
    LB_IP4_TRAEFIK: ENC[AES256_GCM,data:6Fyt9D2uU6oTQcQ=,iv:riCqemIhw9HlxSl9upeAT6qjH/Gzks7zbSzwjcEXtv4=,tag:lTnN4RKnzrOf5E93+x1Y8Q==,type:str]
    LB_IP6_TRAEFIK: ENC[AES256_GCM,data:Wnpi5A5vFWJfq4PeCZxOhLKSIX8fkiI=,iv:Seg9wfM8SQZOXdwFDQm+dECTwL1tmeF8MxjiNIjIMBI=,tag:1YgSsT+LnSSg7aTFN4NMDQ==,type:str]
    LB_IP4_TECHNITIUM: ENC[AES256_GCM,data:8xqMIeYex9v4zT0=,iv:sul5tbti6tSHDazVBSWgq1tVeCBc/mwsy5jCL1tBHMo=,tag:HX+ZrCLBx4zu929re1yrnw==,type:str]
    LB_IP6_TECHNITIUM: ENC[AES256_GCM,data:K9NBqSrXXAALLmTfbed1zdEsfRLrOTU=,iv:lzJTdSvXelFgbo0ICfh6UeHrcNBCfq79LFsJO99s0y0=,tag:wP5qrz6QAN9YmvOvQ+9xJA==,type:str]
    LB_IP4_MINECRAFT_BEDROCK_1: ENC[AES256_GCM,data:N2OlKpYCuJXrN/U=,iv:Mlix//NEkuu5wT/WIelYOGZxxjZpraGdrnFXm3uIOmU=,tag:rlI2IkJfOkanXwPDnAGUKQ==,type:str]
    LB_IP6_MINECRAFT_BEDROCK_1: ENC[AES256_GCM,data:yo8o8n/56VK4g4OnjA5EmXD35XETG5Q=,iv:KxCi3OcfAgf324d0LevVzKh/ojlPnkyBdh7rSF2fUPs=,tag:MQi2CXcPZStNL5DHdsLxDQ==,type:str]
    LB_IP4_MINECRAFT_BEDROCK_2: ENC[AES256_GCM,data:IOeHKmELwa8bKE0=,iv:O5uAMOEKMimPaLepdMvtXWmGSgL1i07u2NcwyVz8dBE=,tag:NEWTThJ+uQlfr0VNVXeuVg==,type:str]
    LB_IP6_MINECRAFT_BEDROCK_2: ENC[AES256_GCM,data:L3n36Q2rtK0V+zbmnXywg3RrkCOWESw=,iv:2I5joNO2gg0ZgjykcK5klVIg+Q9KNclVgrBkXlmAb8M=,tag:zgVY9toQ4VGkOn/pJ2Cajw==,type:str]
    LB_IP4_BEDROCK_CONNECT: ENC[AES256_GCM,data:fypwpwfLNZIq5Yo=,iv:dRH5lvLnMT4euJkXAkM/C4WeMaAyCti0c0YTZEfSJoA=,tag:kq5tcMO1l6gvu6rmC8XoLw==,type:str]
    LB_IP6_BEDROCK_CONNECT: ENC[AES256_GCM,data:Lt/fVDEsSkRpIy5mwerKCqyjeRZwMgk=,iv:/D4cHVeY39caq4FP4/IPa9Z+RzpF68hzsA8R5t1gnmA=,tag:VVHBSxafBGKrBHoPiGtOvg==,type:str]
    KUBELET_CSR_APPROVER_REGEX: ENC[AES256_GCM,data:JLp9xRxcRp3sTFNSxr4Yu36tXrnlh53JaEIllgT4hWLsjHOWi0gRhyjrtQ==,iv:+NnkpOrMqpy4bJg/w36k7FXOABpqX5Cai/OMt4g7VG8=,tag:/+CwF9WzH9qIsWJfmYWCNQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ntjJ2GTEE64JEgLimI/g3g==,iv:NZHse2r+WAd14CtXmSETzzR4KieY0rnr+P8erYa8YSw=,tag:B/vHXQscxvOlbedjzYEX0Q==,type:str]
    GRAFANA_DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:Dyv0sS+ipkGxUG2EExAtamts2JWk7phPY+izEGcrwRrFE0+Yvy/JnCLOY3V6b7zYC43jvgbxlnCO/JGl4Z8hzQ==,iv:VhTeXfztL1wVeidii5uFu/JgEtGcD/x8eEEB29Tv0r4=,tag:EU1feD8LlLxpGW4PYrJadA==,type:str]
    ZEROSSL_EAB_KID: ENC[AES256_GCM,data:v84w+ZxkI48Xd+kALfYBqZDadq/o4Q==,iv:c+/3PS7+UOvPJSlfCtIZg/K3weVZcHRqQuTaPx6CbMk=,tag:/fjKQtiiil+ZKAqlVVZViw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnhSWE9aNzZEdG5LdURm
            em9QYm5JOHhMaFR5TElveDhYREdkMDVVeEcwClJYbnUzU2VWZnBveUcxOUJtc3U1
            MkVGVVBRZWcwNGVNQWlPanpRci8wWTgKLS0tIHFnNlk3L2cvUlJ1Q3VaaWJRd0Vz
            cnFKeU9oSllHYS9lT2VWRkJwdGRQTFkKogQzt+CevjS37iFg0Bk10NYPPrQfVkxd
            ojAAekYv3+A0XwoxzBALXjOGPL+tXJ+mVYWeQQpdxS5FeIS6BTsnfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T09:06:14Z"
    mac: ENC[AES256_GCM,data:YR2YvTxVyOhf2r9Fc/uqJkFHMVPb6lzezX6yqFUoW3joIY2v7ZTw60bL8QNpK9ki4d+CGFCky737ZCReFUGNx7g5vhmOfm9s80kQUGx/swD/oj8XT1UUaR5Km3MNISe+e3J8WmAT1xiZiSwHh8+EDjcOmpWuaryPwO05rrPmjBQ=,iv:Ml/NlEY/25sw2s6atNsd1G9jp7h9xZVgsFD8GSn6WuQ=,tag:X9nJf7Svn3NqJvZU/Ye+OQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
