---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/refs/heads/main/charts/cluster/values.schema.json
# Documentation: https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/README.md
# Default values: https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/values.yaml
type: postgresql
mode: standalone
version:
  postgresql: "18"
cluster:
  instances: 3
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required # preferred
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 8Gi
  storage:
    size: 50Gi
    storageClass: rbd-fast
poolers:
  - name: rw
    type: rw
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: rw
  - name: ro
    type: ro
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: ro
backups:
  enabled: false
