# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sre-credentials
type: Opaque
stringData:
    sre-mcp-auth-token: ENC[AES256_GCM,data:4cTjW6WxTwT3M/O3jgw1qjaxa3nep8LKhmJ7xP+Tc9IEM1Rac0CZ6E5rNSrlfNCIXFC1wby0G6QHZWy9YP4WRg==,iv:VfNWAL5mWFTbiGUt698II7Ah2jmvULWUptJEYKYgZ7Q=,tag:eZZoGEKvi4/P9hm0s0A5oQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM2RUUk9DampzM1pqOFAw
            K284VjliQllPQUtvdnkxby9UaHZ1TmYyZ0ZZClJWbTNxQ24xQTdablBLdmxTVDlU
            N253allSaW9hbjJNNTZRcFB0U3lGbUkKLS0tIHhnY1NnRzZKMWdvRU1nVm9LZk9N
            blUrZHNPODFWY2dhRUc0REtDK0YzU3MKVXfaKqytxJM64vbK0aqW9NxZs9tkKtmQ
            Z717DroDHrAhMbiAk9a/FvdtIfqtMPuE+T+XkP/R/stRTLoGUR+YgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T01:59:42Z"
    mac: ENC[AES256_GCM,data:iFhAp1K8xnp7oUnJoi9pGqg6WUXlLMcsJdOvKiHdW4hh4SFcTpicpt3/d7MkpB5P0glID9rJGa1K3ORgu2NT1WM9neJ28JlXBgM61I7nRzx7f7JG69gjBK41dwfFqgiTwPXvNUsk4NxkD7HiZVdBNH+92dbqLoGu/Oo/Wz0VuIk=,iv:rE2XtamoSCzWllT1hgUpIffQYWat213c60EQ94oT7VQ=,tag:N2OKPTa5wL5fu8CsrN6N5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
