# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-secrets
    namespace: cnpg-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CtJBr++9ysqX4kn5IVGeexLPQkM=,iv:hNgyw3Fhy60tT2ccvDbzq0NuaBHzDkYZ5yPRGDlsH8w=,tag:syOv+I7iwazh+RQHK4QM4g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:q4YCdISm6sL2omQso55EjUwVgdQbE/JD3g6xw/qSJbGQ3QZd4Ik5nw==,iv:F8OE5beE9wccu1cXMuj9VKSmgtK2rkmFWTYXKEevnfY=,tag:wh0jfwrSXeAk0RYat2CUfQ==,type:str]
    #ENC[AES256_GCM,data:mlETaFWxZvt6rrRhEYpFL0af4nqjtA+WnuWSOiMi,iv:L+8S0nvUkBH+DXndLSo3mx+575G9TtMVrMKl5Gs4uVw=,tag:hXQO8fXk4GHijk2CgVul0A==,type:comment]
    #ENC[AES256_GCM,data:0iwnL/EUpdkzHRm/il5kkwf5StmJS65NZaFBJg==,iv:wCT+8N/SC2gImfRnVQNuQaitBoWokyn07+VT3afP0Gk=,tag:mR0G3fLrQfmposrBsF/JrQ==,type:comment]
    #ENC[AES256_GCM,data:C1hPcdtYji7CT3AAZkfgHIqfYO8F/49z,iv:3o2owKdC9NPjKHvTKvDhTc2HPXSk7AxkhfNh7pr8fSk=,tag:xNO30sMMs5ezwrpAvhWOBQ==,type:comment]
    #ENC[AES256_GCM,data:ja8q+IPHfZGo+SGclvPDaYx7rZcAApkgvBS8gPmn,iv:6TZ5ICC4WjAjjQyxRQJqsdVU56QZa9daKuzODmYTDPQ=,tag:wSRuDtUgrKupFZKJgqLK6w==,type:comment]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdkRhWG1Pc1RqZm9uc3NV
            NVdXSHBRdDd5Z1lySjdWektNOE81QTcwRVNvCmpzRUdqbmVWTkdRVi82WWRpZThy
            bjVxUk5OVlVabzFaanJ4WG1kbnQ5a00KLS0tIHdMVEczaExhcEhKZk5YZVFBcGtW
            T2QvNzhxRk1xUkowUHlQdmM3WURWODQK7SXd2JiOa6+cFCK5m7WNeaCFQ6oR9hea
            7/7agU+u70tEyKs0dq2ZYSFwqJTld3K56WTFXBWpFqvvsw60/aMfSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T11:11:23Z"
    mac: ENC[AES256_GCM,data:UDT0OlOrNZuaPRdMVs4bRB9aX/sm7DOC2Fn9pWHN9uKbkndOGIvN3GkSGKDCSa5uz0/HxA26464YlFWMnzWKTHnD6KtFh5Z1qfO6/2GBoPSYJ9U+KekMKCIQsQiLIs97rJHYrJJyy5H5dRX7saQ46/Dm1xZbcvmDWP7kCv2VwEQ=,iv:YGHXV7H2AoKtLfWKlY922/bOHxPhQjJAgvxz3rYX3qY=,tag:++3rwtGKSzUEbY3HkWmShQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
