---
# Default values: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.2.0/charts/library/common/values.schema.json
defaultPodOptions:
  priorityClassName: standard
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
controllers:
  sungather:
    # Must be 1 - Modbus inverters accept only one connection at a time
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/anthony-spruyt/sungather
          tag: 1.0.4@sha256:b6d5efc33ffc08205fee04b42d58b47f7a016968e5375546d956edd055e9193d
          pullPolicy: IfNotPresent
        env:
          TZ: ${TIMEZONE}
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8099
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
persistence:
  config:
    type: emptyDir
    globalMounts:
      - path: /config
  logs:
    type: emptyDir
    globalMounts:
      - path: /logs
  sungather-config:
    type: secret
    name: sungather-secrets
    advancedMounts:
      sungather:
        app:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
service:
  app:
    controller: sungather
    ports:
      http:
        port: 8099
