---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./n8n-mcp-secrets.sops.yaml
  - ./release.yaml
  - ./network-policies.yaml
  - ./vpa.yaml
configMapGenerator:
  - name: n8n-mcp-server-values
    namespace: n8n-mcp
    files:
      - values.yaml
configurations:
  - ./kustomizeconfig.yaml
