# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-mcp-secrets
    namespace: n8n-mcp
stringData:
    N8N_API_KEY: ENC[AES256_GCM,data:hBw1ammhd38hbPZkSS4P+CffYJvgRn+iJEenhvNZtaO8f7O2K8aJzAocZCeElur7THH7JS4Z6ub3jzDTMDFpMW6ClgJFzdN8Uep7c0+LOOGWTDE6Iu7pv2BL4h0n1riXZuNiXlcs6jvLjoeRgPPTaZagKKiLYMoD+ybsQvjGp4zFXtA1N5SGBUt4gIjqakt+JO69XBvE535KOw7XyvuNLZQq4xr2eUMbx5zvmHYrfR1RzMlu/PAqPZiWRyxfcd11sIcl+bUPiwtxy5YayoTCTynXKbhcyr8YQY1CVwFVDlqpuknuyVJ3rKYptzUDSh0LLfvVEbqSMUGl8sb7tUu0W9jnoMl85tQjWuo5,iv:ZGWiHjzz4s5pDiblJyAkz8mC9SbYqGVgzlzj+ZpGwX4=,tag:GGz/P7CZseM+kU0LPMauRA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoajVBVjR2WklnUVRualZ6
            Y0VBS1l5UWFrOXp3SVlWOS9DV29KQmtMNmdRCkJ2SmhTTUhldWhyL2YrTlRSc3pL
            NzlwSWx4YS9IMVk4by9NZlN4UjJNV28KLS0tIHN5eXNheWtxUHpuWTVzMVQveU1M
            dlRSNmk3VHhaY2tDOVNjdEtyNGt4UEEKAqMA3l/tZRlIJZJ9SAkbkv/lWIJ/EXBH
            RjCUNXLFGU6AiwpuNIj5CobR/Yl/8fAxd+Ms/tJHVuhWEKQjbnEFhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T12:02:02Z"
    mac: ENC[AES256_GCM,data:BUeThojxPTVPCvDr3TFudxbNzFhqnVRf++brW7m+jnVRJLnvBjd76cl0HHSxVTiLciLNcR3CeNqUeRzg5fSA8uKtRhRscKI0J4zk6/Xoi9eWzGc62SgSag74Rzygenjip2wqioHQTd2na+9EGkJ7TDskmZklQ17aMrynYg2Syww=,iv:S5D9Fc9dgyji8tJPQ54B20oCZ+SWCjD/LbOZzQ8ZHAs=,tag:Q5I/pc+9oPUhVLrBxVF/cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
