# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-terraform-credentials
    namespace: coder-workspaces
stringData:
    credentials.tfrc.json: ENC[AES256_GCM,data:FlyrZ03blw1vim48GbNih7sQCq5FJv+MFgUwCgLVleAHXTJdfoWdgWzoSzxzYw+ySQoivcGlStNQlulVjBKJ19g37kpVtADMJ5ROu588knRHEhIGXGpOdnpxENVfX6JjrZWWkxyJVr61xOmuekp61R0cA7dOjqk/D0EZY3Eg4XkuSGER5Y9esJKKQLjyLhbp9r9bsWrqKg9MDJX9nR9/ctb+KR+15Q==,iv:Q+xB5iLHTp3Mi+whhK7MVrTcK6/87la/nIZ8Jihjfgs=,tag:mN2tKgS74AhCxccdftVvHw==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYazhoM3dxZTVIam92UTRQ
            VUxORks2SGNvZG5YazNIUnJOangrWXBKcFdNClB1LzROUXlmbTZuRmNCQzFvNkdM
            VzQ1VVB3c2c3UnE1TGw2S0J5QVNmZWMKLS0tIHhWdHhua0xvNXB5empCS254R1l5
            NXJ3TVNUWnhiVnJ6NjZKTUVNYWZDSEUK6Azewif/QyKFAwORfXFTGcMwHL8e8mI9
            1Sx4uTYIZnQqUjKAcYcho271zZpWHwnLY04OnU60OkaNc4cvGd80Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T23:12:13Z"
    mac: ENC[AES256_GCM,data:QoedyUmW9oMb93B22uYTCB4ctb9igYDJUsbrjD5uRob6oRNpD5YoNIXNYj+c+VERg5niKDjqMvXHhJQpG4vaLtwpCxlS2m5t4FnVmrSaUSHjmV1sNcQq9ETuQK6NLZVlnJyt4viNnrZJwlHElDG5YDpW5hg4ILkJJb+rPxAOMkY=,iv:lgjqNc1o/GjC8mfpIGPdwPZE+z+aaMLjV/sjDf9Fdlc=,tag:nXlCyCXqViPZXTBeTW/EnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
