# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-workspace-env
    namespace: coder-workspaces
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:0NHZTDEg2HUOET5qv2WjhlURCNQmtYIWFw==,iv:aiEUAqutlZbsw6J0FnnjgcgwnHRbDtw5pQhIWLaEiRc=,tag:TG3tRLQScAdVl30Z+PcajA==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:4hQ7Wd63r6w+c4Ty94pYqAQ4gW/rJthz5kzOXDZSVdqB98cYdv7xc7hla5jN,iv:N1IqbLROqCc72RMVdW7qCtJmezl9qTd6WgHEHcTKezY=,tag:1sZr6nxUu9ifwf1Rkw+nPQ==,type:str]
    AZURE_DEVOPS_EXT_PAT: ENC[AES256_GCM,data:p74ZuEvIVwreSWVbxd5VM0u2iAVMVi+2pt7rCe91mDjif/J3sMQSNfBi9csoUKlCw44Zm8sndQQVDKKhHW/SvJ7tGHrbidYYOa4qhcjOzAo8jtLv,iv:81sqNx5NRYLBH/VjEK+bQ4FAZphgTo3gkA3GrUMs2qc=,tag:+PzzO71oH+YnoHzWDFG3Wg==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:f1m6KtMyvKXCiYsdc6bB6lMRQBKT/QqltS5EZ6Fsrm47zJnT8WL8W+5vEg==,iv:Xso9FTr06oU7NLCtRrrlhgalWzG3jeOSGzVgX7NniNI=,tag:bXPeVjO0aIFYT1XcJzLfHw==,type:str]
    ENVBUILDER_DOCKER_CONFIG_BASE64: ENC[AES256_GCM,data:Z8F8YGgqMhYqKc7hDR0EV5HwnrWCRfv8BfwRMe5zckF4DYzHfICUx/NVXjE7nubtGlzu26/hJRLcH2KIT3wCnrnG6eeXvw0NR/9BsVr+GE4UhqMmDBD4N75bzirv94dIGd66U0po/upP6beuoSAuoxlBZLw/uuT5DL4ktLthPnHh1q50FQrSAAgZOAKcnxDz92wJPYv11kzRr3HWJgGYGqj0syX1CCBDwYRM9wB2fP5rheDH9sSWHWvIwubqg5e6JUur+YvQBnGPNKIln7f4WAdIAkG3ZXETatS+oCvZpIbwsDBYYU51UE6jBBaDtC8NjuIzvjPmFPadpo10hXv74mOXZZm2YbUmVzyXl3XyslsLNywRtn28+PQlu9H1q08CLOWCn66rzfIWtc+bugT+HP4k1bR5d+xTHs6F4fuZGxYueBWUya9VDFNRFOZuXprchySk3KuO0JQsx604ihZOZPHiUazHVbirTozt6wxlEI4VIzWehVd3bgogtFmrSiXisof754CUeFfN3KxhroTz2DQkRkcoVI5yUGYdeF/NGc6LtMty,iv:WNc8FqGmEHCV3VASt7S5Gf67MZq8kKQ4lFs+ITCcYT4=,tag:HZskh1jRmBULOx2gy3i7rQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:BtCTB3ttDzlh/Q==,iv:ayjvAGvhJGBQP0/VpAKw9aZmbmFMXdPiEuUYjsBTeJU=,tag:BB3EjiqUXThacal5F0Vsrg==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:mAPsRlXMdtqY/W89WBiaSUV7Wcqlxibs/RzsXPaqqZgTOtui9TzAF52odCMXtH9l5OiNs5j7Lf1O,iv:U5zL+1scCxI0lIXtmJIBtgWVDb7WI6l6Yy1snxKL/zc=,tag:CAr+F2cgO+ceWf030LRe+A==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2tEM3V6ZUduUXJlRDlX
            WmsvRVE3QmhxbGg2dUZvSU1SNDJHSUZkSzFZCjFEbG5BTzRBZkdVWlBQcm5TNXM0
            OTBIeHlQcldTR3dLUVdTNmFxOTlBM28KLS0tIHo0STRHOTcya2grTEdKand0WDQr
            UjZTcHNUNzF1ZlNCM25RSU9SWURaM0UKe9R7uZbzEE81or0kEYxgZgCW3reL71fP
            kh2jhxuhY2BFPXGeB8qaBegIF9Hx/p14wlymue14P6t3V5Mc6l6AgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:46:45Z"
    mac: ENC[AES256_GCM,data:hMAop4hTl5ZAoENrIhojjHCa8niPtN92s1rDlGGsaZIyV6fsKs3sg7DKUVazX4ZVRfbIUSNbrmbsbwaKagVMtFs5n3vNMpeJsVxcA7+J3NpsMU9hJD9zmGnERluE6xV23L7SsWjz6tXDCWluzq70xLgC1XmNb/gQhicVKeXYLp4=,iv:NYtbJn/1huzVkJtBFcrJFSmvIh9E3xxEO+0E9MJPgms=,tag:8XT/8YBU727MLMJJHt//rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
