# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-workspace-env
    namespace: coder-workspaces
stringData:
    AZURE_DEVOPS_EXT_PAT: ENC[AES256_GCM,data:hiTAL5zNBAlcaUDpLk0Fi9aCpwibqrxEuryLm5h3CnovtkqKLK6S1K7szRYYRPjYoxG+ql7/dMdU+ueg9Mti1p04gmG43MoMwp+Rfr7ikXozHJdW,iv:vcGTUcrk9SVVkgDr96hkKlmu6VzD/TkyRqMiEYJrXgY=,tag:HmkqV1jwD+KfNm0SG8s68Q==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:HEsD+s8ADhg45bbjZPKDCLoWqorhLd8EOvpjZXZOpT9tZVgjaimO/S30og==,iv:ayxu29+7uR/fGY7WdLRSWlCRUZViSLxFIdGvZa8CuUQ=,tag:mc3n1mAdNogDsxXdctB2aQ==,type:str]
    ENVBUILDER_DOCKER_CONFIG_BASE64: ENC[AES256_GCM,data:snSvesjHt/xSLICPMaBWRIks7PNTfGQAyh7oCiI2w/cuF3aO03x3CeoIPEVz/Jg3pzFbH9h7CrVE/Z0qUlZAaDpQuyYrxAeaYwP7u68tz7XEDhXcybbXFOD1dyPFOdyJvf387aSqEPjYPVvaiCrtCpNK0722L5y5cE8tQ71TTzRR3sJg3qSGGkE0Upxaub7CwI0IfGHVQzUMX4v4GEqMwPANhQAAc4zxyQ4gGGdDH3r6HIYXrHnGLSEW32T7kTiGMjTjuJ0anf88qrDCnTynYOPixUk0EhzZg29maCz2673RdP1UVPxgjn3I0mwQdr8BOtlaxXes+2NFQ6OoBxixbo6+71ZjoFRNfTAmJlHFgLXhFONInikjFuCnNAGdUrC6vLld94WjRnADeS4KA71ll/OnvKysq4cDQec3va8oIFyiAuMguQjjHA1KhDgvYOtAObdNeUX4TTaIt4GdOGkOl7xIgVRaqi5jpyFzmZrc/+Ia5OsfQBAEbom1MAoMfx9etMIr5n0SZzsPHVMADlRhPy4u2e1Zek8yHlVJpR4y8idQ65h9,iv:rFEAWX2V9ZkZ8T9jjtErNMQTejHLakPgNsIX1kprIl0=,tag:/uQ4rKC1Ulxz6HxDKkXFjw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:FsQl0ElpF7rPNA==,iv:bRLPlMbynfO5Wjaq7Ohol2TCHQWBrCx9G6YJVnvKvsk=,tag:WRWSZZEPp2V9bo0THItBJw==,type:str]
    GITLAB_TOKEN: ENC[AES256_GCM,data:qptrv53kckq51G47hz1q/5+ym7fWy4z2RaodnMlQMt/xyy2/9bYxOyjGHNmiv0Ag3k3O0oCaQwMR,iv:SX7MGFhh+bCBvTb5Y5SenP/zOTPCZauaMNaPn3tWjrs=,tag:pnSH6PNjptpqsrpZVeDs+A==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WjIxNHozYUNEQy9FMTRa
            RUNjdzhpRi9tdWxjNkNSMktKdkRXN2czazF3CnIzMERHblM1YnIyQVY2ZXNkMXV5
            RlFCUFRlY0lFODdDNnoyRHBMRm9qQncKLS0tIHRLY0ljOGZpUHZLS2tlK1VQR0RL
            NzJZUVF2bm9VN0hudU9Ua0FMdjdJRFEKq6qUFj9NpOgRdtFQD2hDc0W5RHZkHDfR
            nfW6sKY3rMK2ao+QB7mdaEe/LqpSri5w2c9PZLP2Yc6nLegKLWBDQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T07:10:29Z"
    mac: ENC[AES256_GCM,data:Lm50DhupeT8sM83KnDHyYouChLGa1TzF+5/NjxauprjvR8cnHIxfvwD2EJ942ija809qnzDbXKaz96WSz0TbosaO91HVZsK6+Era7hGHT+RU/YXYc/9D5CsbTDYHN5knmFpKPCC42aCwEvwGmaxARCzhxyGQiF7UKieY/R7UaEI=,iv:Z5BEAfTPQrcHWph9VmgLLKqeGn2FGbTH01d4jrCd368=,tag:veQqL7A6eFliWkzpf+SLKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
