---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-ssh-signing-key
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: github-secret-store
  target:
    name: coder-ssh-signing-key
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: coder-ssh-signing-key
        property: id_ed25519
    - secretKey: id_ed25519.pub
      remoteRef:
        key: coder-ssh-signing-key
        property: id_ed25519.pub
