---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/role-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-ssh-key-rotation
rules:
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    resourceNames: ["coder-ssh-signing-key"]
    verbs: ["get", "patch"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/rolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-ssh-key-rotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-ssh-key-rotation
subjects:
  - kind: ServiceAccount
    name: coder-ssh-key-rotation
    namespace: github-system
