---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: claude-mcp-config
data:
  mcp.json: |
    {
      "mcpServers": {
        "bravesearch": {
          "type": "http",
          "url": "http://brave-search-mcp.brave-search-mcp.svc:8000/mcp"
        },
        "context7": {
          "type": "http",
          "url": "https://mcp.context7.com/mcp",
          "headers": {
            "CONTEXT7_API_KEY": "$${CONTEXT7_API_KEY}"
          }
        },
        "discord": {
          "type": "sse",
          "url": "http://discord-mcp.discord-mcp.svc:8080/sse"
        },
        "github": {
          "type": "http",
          "url": "http://github-mcp-server.github-mcp.svc:8082/mcp"
        },
        "homeassistant": {
          "type": "http",
          "url": "http://${HOME_ASSISTANT_IP4}:8123/api/mcp",
          "headers": {
            "Authorization": "Bearer $${HA_API_KEY}"
          }
        },
        "kubectl": {
          "type": "http",
          "url": "http://kubectl-mcp-server.kubectl-mcp.svc:8000/mcp"
        },
        "victoriametrics": {
          "type": "http",
          "url": "http://mcp-victoriametrics.observability.svc:8080/mcp"
        },
        "sre": {
          "type": "http",
          "url": "http://n8n-webhook.n8n-system.svc/mcp/sre",
          "headers": {
            "Authorization": "Bearer $${SRE_MCP_AUTH_TOKEN}"
          }
        }
      }
    }
