# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mcp-credentials
type: Opaque
stringData:
    context7-api-key: ENC[AES256_GCM,data:Evc2B9NwgnwDCWcpOLlh2EsDLBZ/T0ANxnv8/hH+7KXm4fvldRcVwxJQcA==,iv:IAmuzQ3l+ndoRJSnBne30yRxa6iE0qt0eGlQMQwdjC8=,tag:k4/B+7lABOQ7LBYFUVKzTg==,type:str]
    ha-api-key: ENC[AES256_GCM,data:EM2gguOUFEXfLQGhXaKkHzQpM6Pdo5nMKjE5NpTTKTe1E8SoniXnfv0xhU2qQuRu2oGcuSZxRFGERQUgTmTXn6KZ7pQ+XWnYLApACWoJtpKcHT/H7lmuzPmHrjKVn3fUwuVJn2Me8NSq35T6gWueDSoi6frANzeNOEM69a5vZ12LMPm5TBXAPjsX8cYgxUrbj0vNDhsoB9nieIYMPr7kqoLq7wtgRRv16sKyzdhPG3khK+I3U1r5,iv:NnAKK2cEwq6cru4iU45Z56NPKq2HXxka9U/6ROD5O/g=,tag:Uu1y1wdRa8dRNsRjfaDCew==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UDZNUDYzMXRjQUhsTk9t
            Nk9NcGp6NW50NEw3dmx3blFySzRCb2tIS0hBCmd4aE45V3NoakNMY1ZkNUtISlpk
            RERNZ3JwK2UxcWRLZEtjcG9OL1JWWGcKLS0tIGlFU1F4emZ1eE92UUdvcDBYNUVJ
            SDlsT3k5bWZYRzllRTNZSjZDaEtxbG8K2N6PR/QyvEObXWHqfs58p+hmoMlzsmsm
            n2dfZ9l4j8njozYT0qzIrfVeIT+lOiFWkdGap7uQSSptgPyWRInArA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T04:38:57Z"
    mac: ENC[AES256_GCM,data:oZLh6uxeqJbF1rxzHE65sXYm3a/SDBNMH/99nJyp/a0BkpMweEpCcCApX7QrLHc1wn4Ea+B2UpbmeN2LaGn5gPXLHqEocvvLoTDPsE8KKP1mJjU+zimOoPMq0FAJCIbyzAZSFI3+TmFOu1RSQURSKjhCq+avRKhzkKdStOo8tpM=,iv:m7x6bXgwoQ32MrOCmlj5pRuH0UV4ldzuwhgHGwKEoeQ=,tag:Kl75HKBd+ZhjpiCi2ZEr1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
