# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mcp-credentials
type: Opaque
stringData:
    context7-api-key: ENC[AES256_GCM,data:1aoayyY3mUh3qcTJj5UGlFeVKm65fNhUsgxGbbNynCWQxBZsI9Azj4bHUg==,iv:kqgOGXIuNZh0w/wFM89mJvZj+BcTycZWUZQWoq4CBuE=,tag:+ZYmq8b2Rao4MSd4nfPonw==,type:str]
    ha-api-key: ENC[AES256_GCM,data:6IunnoDxKfGXj0K0oV1l1YFYh6sJ+P4rZWiRGwtl3mKY/+SdAhmUiDdooibSZ/CaAHNoiOkpFE8zJAAi7ayRvME1UIe+4M7gvlHtNE4/zAd/+I5AheAYXiAkX0zq3tscsqc22dGp/dFSuSPfJNEqUelru+5nbin+SdTaF1diBX2OFuWI0KxfhJhrIPhMUfr/7PYRinm9Qv83dFVwBYDHZBeMyNQvuyncvcZBoezcIoyq6NC8CZmb,iv:K4/6h2gGtVd22zA1y8s9FqPDwL5zexXyoDPmxiOXI7w=,tag:gEhTMT7ohW09gku6YumBZA==,type:str]
    sre-mcp-auth-token: ENC[AES256_GCM,data:zkmIO459xOfUXFNelBCYJf8UHnGXgElE5JFZapwDImgYoUPPAR7iStjO1ggfC7vJ8nohmhaEjCtxk6QTSeEBfA==,iv:IstoR9KPGr1Aip2Ytex2LCF1OtxpCsMEK0YW9bzGb1Y=,tag:PV/lDSd7DBy0vgURxCTL9A==,type:str]
    renovate-mcp-auth-token: ENC[AES256_GCM,data:HIAqYk+rxLO6yNC0mP6NMX0/S+PAPl9bUusGZcU5pcypJA/dm/gcxzavXQvf2JPlTbMhNXspmp5IhEGO8ste7xmlIQhBnhLzKZsK+gSuZA/hH8TKITF5rqRml9plJaPHbVHaXY/GqljtCvMV1tQof6zqPcVVCj6EqkRifuBkDNs=,iv:t7UmnBdi3KiymzQiggU4kA7Yvr2fl429h1fS052pTVY=,tag:iQfG/sLrLg2ciZ4ltn5JHA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL295OWw0YXIvZnVzbnp6
            S0UycmhXSUdqUFhKS1RrLy9TWktRQmkyS1dzCkJQdkF6dUtSN0tVNDZFNGg0Uy9y
            akROUzI0T1lpcEpPeUEzSW14MnE2U28KLS0tIFV5YnArdHNaMDE0ZlMyd0t4eEtD
            Nzd1SFdhRnZCcjdTTDUzU2NyQXRBd2cKM9g87HtuHlepkP9iX3pstlri3bhsSj0B
            U/55P+StzR6kNMjvSv6p1H0CXXoKbg2RWu1Vc6pDzwWrKkEFsG3DuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:25:15Z"
    mac: ENC[AES256_GCM,data:OnqVU67+G17DbKgu5NOU1Pwu0US+kEa+6AFN+pHM3ozJ8uYTDyNp1AM8s2PeeMmCqXWj42kGDFi+JAfz1dM1jgGLZiGsPNCCT48KTmaO/xZ8TTHDcTmGZIu7rjWKx0mF0/NphI7oKS55oisg660Agojyal/ZEFtPELvJCfHFHtw=,iv:bdCpyJPlpUOe0kkEdB3kehyCkZ9dpZKaV0kXJcw/34I=,tag:5NJZOEYNWfjMUyOkRY6w6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
