# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mcp-credentials
type: Opaque
stringData:
    context7-api-key: ENC[AES256_GCM,data:O4nAaxUSRxXkQGg/iiwBTPhvbk7t8c+gmA2G9fUV+qEaXDLeB5lBxrTYOA==,iv:C13P9Vr+n8tPbrYWBrvKcqITNNSFpTHIMf4rxWjaRRA=,tag:76DxGUB6uboRgv1BPeikYg==,type:str]
    agent-platform-mcp-auth-token: ENC[AES256_GCM,data:g/IZZsar0U44kLr01AHhob4fs5db1YVUOB39brtm9ZXNz2T1w/LJFdiuGrblrcedr6Ewf6A83MYZM8Nbg0k1a49YI05ilzbVNVxQuFtWzitr91e1eQxPzjGxWqRjSXLvRHrv+44xdu/R7Cdvnaid8bmNu8+DajwVvSkP72OJ9U4=,iv:JUXXohC/AYWTSPMV9YtA0K2+AtOnpzpVMzb0RXSNahw=,tag:yt8/I6gzmK2fEn4HbMDPrA==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVW4xZVV1US9RcGFJS2hs
            K3BrVzRvQkZRMWY0Z3JTM1d1TlY1aFkzQ2s0CnN5Y25qVjBwTnBQZzJtR0FTSTVR
            ZXB2bTBJclRONUd5SFdXTU5mQmlDOWcKLS0tIDNPVm41cFlzSS9FZHNEeDJDWWNG
            Q2ZJOXFMWUxMWG85WENzM2NlazErNVUKDfQ0yz/e+2EMqOgoDoKoNhn0v4tMNldA
            kXApgoApIsP+3fn0Fpb5GoUXYOK3ja5DQJsmHWxAWWXia2Cb86xg8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T13:04:36Z"
    mac: ENC[AES256_GCM,data:n3+GkiiYx0hLvU7fSO1/i1a3N4AeyTfktJyplBSHAujMYo5Y38wI+20x6EKlgojzLvZdXOqxhqjG7+p0ijuMbvX8QfoxKKV+Sl+sTVEitmPcRRF97qxyJURbB7Oy1nsyAAQRjFcK/x+DzxOcZ2rJtZ6n1sFUF+K3oQdoFhnr+zQ=,iv:Dg639wOl5+CzV522LtF4KlCBd5zbAU88FixWxei2Ch8=,tag:PzlmmbEBDtqwkNCChsTwjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
