# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zerossl-eab-secret
    namespace: cert-manager
data:
    EAB_HMAC_Key: ENC[AES256_GCM,data:ANpGqFQBVdhd18tROmbRvP7KRm2zCgcB2FTeRKpvJ4Gy2wYeEnQnyJHetn9jHiZAanQwVJPUbvRle8JadCurAMwZzsqzSSFrkKXM1OsagLFEVLG/t5KpDFRmU46obVGwfOyw2WMIy0X3C8ERJxj1Z3wdy3Y=,iv:+HzMt02Kw4xNlTUcFYdnb+M0CaXo6Af2os7usPxX/DU=,tag:i/Su19C8QAi9UlFNBLP1EQ==,type:str]
sops:
    age:
        - recipient: age1lt4xakktwyjvsqe6e09ca8f7nsljua3lynd7d9lzcs39fyqt8ggq87glw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrendPU0VNcWErcy9JNU4y
            eFh3eTk5K0ZjL0h4U2d1bVQ2UDNESUJnd0U0CkNhUWlqOHp1YU5MM01GaDdHaU5Z
            K3NaY0tEY3kzTHBXWEhCUUdEeFVOY3cKLS0tIGplQnpnNnlycmJJZ3JRdWVJS29j
            NDZpLzJWR0t6UWNYa21SeXZ2ZVNGMGcKfIRCy5JrEpBclavxpuana2mVc4zkmOB6
            Ax21URcEO7/4FNzW+JtpG69MNwev/9LYyETO5aE5wRhCGlxAfBoZjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T04:09:19Z"
    mac: ENC[AES256_GCM,data:iuf4tG0rr58pvHxUZynpqDg/yV6IGBpCkcO0+5uS/2L5OP5V5L5UnARWd1l6mEPzPT52uOQlDAV86PoKug90pqww/Cx2mGTOnuUHoPWFpjM1WwEUfNu5gb6zq6b7JVwxk96B4itoOXC0abTwhIXI/nQxypx207ZRp5x4fsqlMdQ=,iv:QwwlTlU+1o9mFnOUM/AUFYdsFZ6/TqP8blexU5z9Ul4=,tag:lVPz4QYtWQtZfUuKER0jvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
