---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kata-tap-qdisc-fix
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./cluster/apps/kube-system/kata-tap-qdisc-fix/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kata-runtimeclass
      namespace: flux-system
  prune: true
  wait: true
  timeout: 5m
